Blockly.Msg.KNN_CLASSIFIER_OPEN_SHOW = "Machine Learning(KNN) Initialize";
Blockly.Msg.KNN_CLASSIFIER_PROPORTION_SHOW = "Machine Learning(KNN) Max";
Blockly.Msg.KNN_CLASSIFIER_WIDTH_SHOW = "Video (KNN) Width";
Blockly.Msg.KNN_CLASSIFIER_HEIGHT_SHOW = "Height";
Blockly.Msg.KNN_CLASSIFIER_MIRRORIMAGE_SHOW = "MirrorImage";
Blockly.Msg.KNN_CLASSIFIER_RESULT_SHOW = "Result";
Blockly.Msg.KNN_CLASSIFIER_OPACITY_SHOW = "Opacity";
Blockly.Msg.KNN_CLASSIFIER_TRAIN_SHOW = "Train";
Blockly.Msg.KNN_CLASSIFIER_STARTDETECT_SHOW = "Start Detection";
