Blockly.Msg.TRACKINGFACE_SHOW = "追蹤人臉 (Tracking)";
Blockly.Msg.TRACKINGFACE_SET_SHOW = "追蹤人臉 (Tracking) 視窗設定";
Blockly.Msg.TRACKINGFACE_GET_SHOW = "追蹤人臉 (Tracking) 取得";
Blockly.Msg.TRACKINGFACE_WIDTH_SHOW = "寬度";
Blockly.Msg.TRACKINGFACE_HEIGHT_SHOW = "高度";
Blockly.Msg.TRACKINGFACE_DISPLAY_SHOW = "顯示";
Blockly.Msg.TRACKINGFACE_LEFT_SHOW = "靠左距離";
Blockly.Msg.TRACKINGFACE_TOP_SHOW = "靠上距離"
Blockly.Msg.TRACKINGFACE_MIRRORIMAGE_SHOW = "鏡像";
Blockly.Msg.TRACKINGFACE_RESULT_SHOW = "結果";
Blockly.Msg.TRACKINGFACE_OPACITY_SHOW = "透明度";
Blockly.Msg.TRACKINGFACE_FRAME_SHOW = "框架";
Blockly.Msg.TRACKINGFACE_DRAWIMAGE_SHOW = "視訊畫面描繪至";
Blockly.Msg.CANVAS_ID_SHOW = "畫布代碼";
Blockly.Msg.TRACKINGFACE_INDEX_SHOW = "索引";
Blockly.Msg.TRACKINGFACE_FACING_SHOW = "鏡頭";
Blockly.Msg.TRACKINGFACE_FACING_FRONT_SHOW = "前置";
Blockly.Msg.TRACKINGFACE_FACING_BACK_SHOW = "後置";
Blockly.Msg.TRACKINGFACE_SRC_SHOW = "串流網址";