// This file was automatically generated.  Do not modify.

'use strict';

Blockly.Msg.ADD_COMMENT = "加入註解";

Blockly.Msg.ARDUINO = "ARDUINO";
Blockly.Msg.ARDUINO_CODE = "程式碼　　　";
Blockly.Msg.ARRAY_CREATE_WITH_CONTAINER_TITLE_ADD = "陣列";
Blockly.Msg.ARRAY_CREATE_WITH_CONTAINER_TOOLTIP = "新增、移除或重新排列以重新設定陣列積木。";
Blockly.Msg.ARRAY_CREATE_WITH_HELPURL = "";
Blockly.Msg.ARRAY_CREATE_WITH_INPUT_WITH = "建立陣列使用 ";
Blockly.Msg.ARRAY_CREATE_WITH_ITEM_TITLE = "物件";
Blockly.Msg.ARRAY_CREATE_WITH_ITEM_TOOLTIP = "新增一個物件至陣列";
Blockly.Msg.ARRAY_CREATE_WITH_TOOLTIP = "使用任意數量的物件來建立一個陣列。";
Blockly.Msg.ARRAY_GETINDEX_AT = "取得第";
Blockly.Msg.ARRAY_GETINDEX_AT1 = "取得第";
Blockly.Msg.ARRAY_GETINDEX_AT2 = "索引";
Blockly.Msg.ARRAY_GETINDEX_HELPURL = "";
Blockly.Msg.ARRAY_GETINDEX_ITEM = "於陣列中";
Blockly.Msg.ARRAY_GETSIZE_ITEM = "取得陣列長度";
Blockly.Msg.ARRAY_GETINDEX_TOOLTIP = "";
Blockly.Msg.ARRAY_MODIFY_INDICE = "設定第";
Blockly.Msg.ARRAY_MODIFY_NAME = "將陣列";
Blockly.Msg.ARRAY_MODIFY_VALUE = "資料為";
Blockly.Msg.ARRAY_MODIFY_TOOLTIP = "set a specific value to an elemnt of an array";
Blockly.Msg.ARRAY_FOR_INPUT_FROM_TO = "從範圍 %1 到取得 %2 陣列長度" ;
Blockly.Msg.ARRAY_FOR_INPUT_FROM_TO1 = "從範圍 " ;
Blockly.Msg.ARRAY_FOR_INPUT_FROM_TO2 = " 到取得 " ;
Blockly.Msg.ARRAY_FOR_INPUT_FROM_TO3 = " 陣列長度" ;
Blockly.Msg.AUTH = "Please authorize this app to enable your work to be saved and to allow it to be shared by you.";  // untranslated
Blockly.Msg.AUTO_SAVE_TITLE = "自動儲存";
Blockly.Msg.BLOCKS = "　積木　";
Blockly.Msg.BLUE = "藍";

Blockly.Msg.BUTTON_EXPORT = "匯出";
Blockly.Msg.BUTTON_IMPORT = "匯入";
Blockly.Msg.BUTTON_NEW = "新建";
Blockly.Msg.BUTTON_OPEN = "開啟";
Blockly.Msg.BUTTON_SAVE = "儲存";
Blockly.Msg.CAST_NUMBER_HELPURL = "https://www.arduino.cc/en/Reference/Cast";
Blockly.Msg.CAST_NUMBER_TITLE = "轉換成";
Blockly.Msg.CAST_NUMBER_TOOLTIP = "The cast operator translates one variable type into another and forces calculations to be performed in the cast type.";  // untranslated
Blockly.Msg.CATEGORY_ADAFRUIT = "Adafruit";
Blockly.Msg.CATEGORY_AEROBOT = "AERobot";
Blockly.Msg.CATEGORY_ANALOG = "類比 I/O";
Blockly.Msg.CATEGORY_ARRAY = "陣列";
Blockly.Msg.CATEGORY_BYLNK = "Blynk";
Blockly.Msg.CATEGORY_CLOUD_SERVICE = "雲端服務";
Blockly.Msg.CATEGORY_DIGITAL = "數位 I/O";
Blockly.Msg.CATEGORY_ETHERNET = "乙太網路";
Blockly.Msg.CATEGORY_ETHERNET_CLIENT = "連線端";
Blockly.Msg.CATEGORY_ETHERNET_INIT = "初始化";
Blockly.Msg.CATEGORY_FUNCTIONS = "函數";
Blockly.Msg.CATEGORY_GROVE = "Grove模組";
Blockly.Msg.CATEGORY_GROVE_ANALOG = "Grove 類比";
Blockly.Msg.CATEGORY_GROVE_INPUT = "輸入";
Blockly.Msg.CATEGORY_GROVE_LCD_RGB = "LCD RGB";
Blockly.Msg.CATEGORY_GROVE_MOTOR = "Grove 馬達";
Blockly.Msg.CATEGORY_GROVE_OUTPUT = "輸出";
Blockly.Msg.CATEGORY_GROVE_ACTUATOR = "執行器";
Blockly.Msg.CATEGORY_GROVE_DISPLAY = "顯示";
Blockly.Msg.CATEGORY_GROVE_SENSOR = "感應器";
Blockly.Msg.CATEGORY_OTTO = "Otto";
Blockly.Msg.CATEGORY_I2C_MATRIX = "LED 矩陣";
Blockly.Msg.CATEGORY_I2C_SEVENSEG = "7 段 LED";
Blockly.Msg.CATEGORY_IFTTT = "IFTTT";
Blockly.Msg.CATEGORY_INITIALIZES = "程式流程";
Blockly.Msg.CATEGORY_INOUT = "輸入/輸出";
Blockly.Msg.CATEGORY_INTERRUPTS = "中斷訊號";
Blockly.Msg.CATEGORY_EEPROM = "EEPROM";
Blockly.Msg.CATEGORY_INVOLT = "involt";  // untranslated
Blockly.Msg.CATEGORY_LCD = "液晶顯示";  // untranslated
Blockly.Msg.CATEGORY_LOGIC = "邏輯";
Blockly.Msg.CATEGORY_LOOPS = "迴圈";  // untranslated
Blockly.Msg.CATEGORY_M2X = "M2X";  // untranslated
Blockly.Msg.CATEGORY_MATH = "數學";
Blockly.Msg.CATEGORY_MPR121 = "電容感應器";
Blockly.Msg.CATEGORY_NEOPIXEL = "彩色燈條";  // untranslated
Blockly.Msg.CATEGORY_OTHERS = "音調";
Blockly.Msg.CATEGORY_OTHER_SENSOR = "其他感應器";
Blockly.Msg.CATEGORY_RGBLED = "RGBLed(ws8211)";  // untranslated
Blockly.Msg.CATEGORY_ROBOT = "機器人";
Blockly.Msg.CATEGORY_SERIAL = "序列埠 I/O";
Blockly.Msg.CATEGORY_SERVO = "伺服馬達";  // untranslated
Blockly.Msg.CATEGORY_SHIELD_BOT = "ShieldBot";  // untranslated
Blockly.Msg.CATEGORY_TEXT = "字串";
Blockly.Msg.CATEGORY_TIME = "時間";
Blockly.Msg.CATEGORY_ULTRA_SONIC = "超音波";
Blockly.Msg.CATEGORY_VARIABLES = "變數";
Blockly.Msg.CHANGE = "變更";
Blockly.Msg.CHANGE_LANG = "變更語言";
Blockly.Msg.CHANGE_VALUE_TITLE = "修改值：";
Blockly.Msg.CHAT = "與您的合作者洽談藉由在此框輸入！";
Blockly.Msg.COL = "Col";  // untranslated
Blockly.Msg.COLLAPSE_ALL = "收合積木";
Blockly.Msg.COLLAPSE_BLOCK = "收合積木";
Blockly.Msg.COLOR = "顏色";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "顏色 1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "顏色 2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";
Blockly.Msg.COLOUR_BLEND_RATIO = "比例";
Blockly.Msg.COLOUR_BLEND_TITLE = "混合";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "透過一個比率 (0.0-1.0)來混合兩種顏色。";
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://en.wikipedia.org/wiki/Color";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "從調色板中選擇一種顏色。";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "隨機顏色";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "隨機選擇一種顏色。";
Blockly.Msg.COLOUR_RGB_BLUE = "藍";
Blockly.Msg.COLOUR_RGB_GREEN = "綠";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";
Blockly.Msg.COLOUR_RGB_RED = "紅";
Blockly.Msg.COLOUR_RGB_TITLE = "顏色";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "透過指定紅、綠、 藍色的值來建立一種顏色。所有的值必須介於 0 和 100 之間。";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "停止 迴圈";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "繼續下一個 迴圈";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "離開當前的 迴圈";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "跳過這個迴圈的其餘步驟，並繼續下一次的迴圈運算。";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "警告： 此積木僅可用於迴圈內。";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each 查看積木細節";
Blockly.Msg.CONTROLS_FOREACH_INPUT_INLIST = "自列表";
Blockly.Msg.CONTROLS_FOREACH_INPUT_INLIST_TAIL = "";
Blockly.Msg.CONTROLS_FOREACH_INPUT_ITEM = "取出每個";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "遍歷每個列表中的項目，將變數  '%1' 設定到該項目中，然後執行某些語句";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP1 = "遍歷每個列表中的項目，將變數  '";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP2 = "' 設定到該項目中，然後執行某些語句";
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO = "從範圍 %1 到 %2";
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO1 = "從範圍 ";
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO2 = " 到 ";
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO_BY = "從範圍 %1 到 %2 每隔 %3";
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO_BY1 = "從範圍 ";
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO_BY2 = " 到 ";
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO_BY3 = " 每隔 ";
Blockly.Msg.CONTROLS_FOR_INPUT_WITH = "使用";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "從起始數到結尾數中取出變數 %1 的值，按指定的時間間隔，執行指定的積木。";
Blockly.Msg.CONTROLS_FOR_TOOLTIP1 = "從起始數到結尾數中取出變數 ";
Blockly.Msg.CONTROLS_FOR_TOOLTIP2 = " 的值，按指定的時間間隔，執行指定的積木。";
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "將條件添加到'如果'積木。";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "加入一個最終，所有條件下都都執行的區塊到'如果'積木中";
Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "添加、 刪除或重新排列各區塊來此重新配置這個'如果'積木。";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "否則";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "否則如果";
Blockly.Msg.CONTROLS_IF_MSG_IF = "如果";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "當值為真時，執行一些語句";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "當值為真時，執行第一個語句，否則則執行第二個語句";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "如果第一個值為真，則執行第一個語句。否則當第二個值為真時，則執行第二個語句";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "如果第一個值為真，則執行第一個語句。否則當第二個值為真時，則執行第二個語句。如果前幾個敘述都不為真，則執行最後一個語句";
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://en.wikipedia.org/wiki/For_loop";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "執行";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "重複 %1 次";
Blockly.Msg.CONTROLS_REPEAT_TITLE1 = "重複 ";
Blockly.Msg.CONTROLS_REPEAT_TITLE2 = " 次";
Blockly.Msg.CONTROLS_REPEAT_TITLE_REPEAT = "重複 ";
Blockly.Msg.CONTROLS_REPEAT_TITLE_TIMES = " 次數";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "多次執行一些語句";
Blockly.Msg.CONTROLS_RETURN_HELPURL = "https://www.arduino.cc/en/Reference/Return";
Blockly.Msg.CONTROLS_RETURN_TITLE = "返回";
Blockly.Msg.CONTROLS_RETURN_TOOLTIP = "Terminate a function and return a value from a function to the calling function, if desired.";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "重複 直到";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "重複 當";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "當值為否時，執行一些語句";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "當值為真時，執行一些語句";
Blockly.Msg.CONTROLS_WHILE_HELPURL = "https://www.arduino.cc/en/Reference/While";  // untranslated
Blockly.Msg.CONTROLS_WHILE_INPUT_DO = "執行";  // untranslated
Blockly.Msg.CONTROLS_WHILE_TITLE = "當";  // untranslated
Blockly.Msg.CONTROLS_WHILE_TOOLTIP = "while loops will loop continuously, and infinitely, until the expression inside the parenthesis, () becomes false.";  // untranslated
Blockly.Msg.COPY_BUTTON = "Clip Code";  // untranslated
Blockly.Msg.COPY_DONE = "拷貝完成！";  // untranslated
Blockly.Msg.DATA_LENGTH = "資料長度";  // untranslated
Blockly.Msg.DATA_TYPE = "資料型態";  // untranslated
Blockly.Msg.DELETE_ALL1 = "刪除全部";  // untranslated
Blockly.Msg.DELETE_ALL2 = "積木？";  // untranslated
Blockly.Msg.DELETE_BLOCK = "刪除積木";
Blockly.Msg.DELETE_X_BLOCKS = "刪除 %1 塊積木";
Blockly.Msg.DELETE_X_BLOCKS1 = "刪除 ";
Blockly.Msg.DELETE_X_BLOCKS2 = " 塊積木";
Blockly.Msg.DEVICE_ID = "DeviceID";  // untranslated
Blockly.Msg.SETTINGS_OK = "儲存並重新啟動";
Blockly.Msg.SETTINGS_CANCEL = "取消";
Blockly.Msg.SETTINGS_VERSION = "版本：";
Blockly.Msg.SETTINGS_VERSION_PRE_RELEASE = "（測試版）";
Blockly.Msg.MESSAGE_UPDATE = "更新版本 ";
Blockly.Msg.MESSAGE_UPDATE_APPEND = " 目前可供下載！";
Blockly.Msg.DIALOG1_NO = "否";
Blockly.Msg.DIALOG1_TITLE = "重設？";
Blockly.Msg.DIALOG1_YES = "是";
Blockly.Msg.DIALOG2_TITLE = "檔案名稱";
Blockly.Msg.DIALOG3_TITLE = "無法讀取 XML 檔案";
Blockly.Msg.DIALOG4_TITLE = "刪除所有積木？";
Blockly.Msg.DIALOG_BLOCK_TITLE = "選擇性積木";
Blockly.Msg.DIALOG_EXPORT_OK = "關閉";
Blockly.Msg.DIALOG_IMPORT_CANCEL = "取消";
Blockly.Msg.DIALOG_IMPORT_OK = "匯入";
Blockly.Msg.DIALOG_LANG_TITLE = "選擇語言";
Blockly.Msg.DIALOG_SENDCHROME = "將範例傳送至 ChromeApp？";
Blockly.Msg.DIRECTION = "方向";
Blockly.Msg.DISABLE_BLOCK = "停用積木";
Blockly.Msg.DISCARD = "放棄";
Blockly.Msg.DO = "執行";
Blockly.Msg.DOUBLE = "倍精度浮點數";
Blockly.Msg.DOWNLOAD_CHROME_APP = "下載離線版編輯器";
Blockly.Msg.DROPDOWN_DISCARD = "放棄積木"
Blockly.Msg.DROPDOWN_SAVE_AS = "另存新檔...";
Blockly.Msg.DUPLICATE_BLOCK = "複製";
Blockly.Msg.ELEVATION = "評估";
Blockly.Msg.EMAIL_ADDRESS = "電子信箱";
Blockly.Msg.EMAIL_BODY = "內容";
Blockly.Msg.EMAIL_TITLE = "標題";
Blockly.Msg.ENABLE_BLOCK = "啟用積木";
Blockly.Msg.ERROR_BETA_WARNING = '您正在使用測試版本，請改用穩定版本！';
Blockly.Msg.ERROR_FILENAME = "請輸入檔案名稱！";
Blockly.Msg.ERROR_FILENAME2 = "檔案名稱錯誤！";
Blockly.Msg.ERROR_PARSING_XML = "XML 讀取錯誤";

Blockly.Msg.EXPAND_ALL = "展開積木";
Blockly.Msg.EXPAND_BLOCK = "展開積木";
Blockly.Msg.EXTERNAL_INPUTS = "多行輸入";
Blockly.Msg.FALLING = "下降邊緣";  // untranslated
Blockly.Msg.GO_TO_SAMPLE = "連結至範例頁面";
Blockly.Msg.GO_TO_WEB = "連結至線上編輯器";
Blockly.Msg.GREEN = "綠";

Blockly.Msg.HELP = "說明";

Blockly.Msg.INDEX = "Index";  // untranslated
Blockly.Msg.INFO_FILENAME = "檔案名稱：";
Blockly.Msg.INFO_TITLE = "[無已載入的文件]";
Blockly.Msg.INITIALIZES_SETUP_APPENDTEXT = "初始化";
Blockly.Msg.INITIALIZES_LOOP_APPENDTEXT = "重複執行";
Blockly.Msg.INITIALIZES_SETUP_HELPURL = "http://www.arduino.cc/en/Reference/Setup";
Blockly.Msg.INITIALIZES_SETUP_TOOLTIP = "setup()，在程式執行之初執行一次這些步驟。";
Blockly.Msg.INITIALIZES_LOOP_HELPURL = "http://www.arduino.cc/en/Reference/Loop";
Blockly.Msg.INITIALIZES_LOOP_TOOLTIP = "loop()，在程式執行過程中不斷重複執行這些步驟。";
Blockly.Msg.INITIALIZES_TEMP_APPENDTEXT = "暫存區";
Blockly.Msg.INITIALIZES_TEMP_HELPURL = "";
Blockly.Msg.INITIALIZES_SETUP_TOOLTIP = "此區域內的模塊將不會被轉換為程式碼。";
Blockly.Msg.INLINE_INPUTS = "單行輸入";
音。";
Blockly.Msg.INTEGER = "整數";


Blockly.Msg.LEFT = "左";
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "建立空列表";
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE_PROCEDURE = "空變數";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "返回一個長度為 0 的列表，不包含任何資料記錄";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "加入";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "添加、 刪除或重新排列各區塊來此重新配置這個 列表 積木。";
Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "建立值的列表";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "將一個項目加入到列表中。";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "建立一個具備任意數量項目的列表。";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "第一筆";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "倒數第#筆";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";
Blockly.Msg.LISTS_GET_INDEX_GET = "取值";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "取出並移除";
Blockly.Msg.LISTS_GET_INDEX_LAST = "最後一筆";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "隨機";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "移除";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "返回列表中的第一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "返回在列表中的指定位置的項目。#1 是最後一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "返回在列表中的指定位置的項目。#1 是第一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "返回列表中的最後一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "返回列表中隨機的一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "移除並返回列表中的第一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "移除並返回列表中的指定位置的項目。#1 是最後一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "移除並返回列表中的指定位置的項目。#1 是第一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "移除並返回列表中的最後一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "移除並返回列表中的隨機一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "移除列表中的第一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "移除在列表中的指定位置的項目。#1 是最後一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "移除在列表中的指定位置的項目。#1 是第一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "移除列表中的最後一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "移除列表中隨機的一個項目";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "到 倒數 # 位";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "到 #";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "到 最後";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "從 頭 取得子列表";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "從倒數 # 取得子列表";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "從 # 取得子列表";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "複製列表中指定的部分。";
Blockly.Msg.LISTS_INDEX_OF_FIRST = "找出 第一個 項目出現";
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";
Blockly.Msg.LISTS_INDEX_OF_LAST = "找出 最後一個 項目出現";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "返回在列表中的第一個/最後一個匹配項目的索引值。如果未找到則返回 0。";
Blockly.Msg.LISTS_INLIST = "自列表";
Blockly.Msg.LISTS_IS_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty";
Blockly.Msg.LISTS_IS_EMPTY_TITLE = "%1 值為空";
Blockly.Msg.LISTS_IS_EMPTY_TITLE1 = " 值為空";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "返回列表的長度。";
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";
Blockly.Msg.LISTS_REPEAT_TITLE = "建立列表使用項目 %1 重複 %2 次數";
Blockly.Msg.LISTS_REPEAT_TITLE1 = "建立列表使用項目 ";
Blockly.Msg.LISTS_REPEAT_TITLE2 = " 重複 ";
Blockly.Msg.LISTS_REPEAT_TITLE3 = " 次數";
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "建立包含指定重複次數的 值 的列表。";
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set";
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "為";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "插入到";
Blockly.Msg.LISTS_SET_INDEX_SET = "設定";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "在列表的起始處添加一個項目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "插入在列表中的指定位置的項目。#1 是最後一個項目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "插入在列表中的指定位置的項目。#1 是第一個項目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "在列表的尾端加入一個項目";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "在列表中隨機插入項目";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "設定列表中的第一個項目";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "設定在列表中的指定位置的項目。#1 是最後一個項目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "設定在列表中的指定位置的項目。#1 是第一個項目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "設定列表中的最後一個項目";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "設定列表中隨機的一個項目";
Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";
Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "make list from text";  // untranslated
Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "make text from list";  // untranslated
Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "Join a list of texts into one text, separated by a delimiter.";  // untranslated
Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "Split text into a list of texts, breaking at each delimiter.";  // untranslated
Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "with delimiter";  // untranslated
Blockly.Msg.LISTS_TOOLTIP = "如果該列表為空，則返回 真。";
Blockly.Msg.LOAD_XML = "載入 XML";
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "否";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "返回 真 或 否。";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "真";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://en.wikipedia.org/wiki/Inequality_(mathematics)";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "如果這兩個輸入區塊內容相等，返回 真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "如果第一個輸入大於第二個輸入，返回 真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "如果第一個輸入大於或等於第二個輸入，返回 真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "如果第一個輸入小於第二個輸入，返回 真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "如果第一個輸入是小於或等於第二個輸入，返回 真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "如果這兩個輸入區塊內容不相等，返回 真。";
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not";
Blockly.Msg.LOGIC_NEGATE_TITLE = "非";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "如果輸入的值是 否，則返回 真。如果輸入的值是 真 返回 否。";
Blockly.Msg.LOGIC_NULL = "空";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type";
Blockly.Msg.LOGIC_NULL_TOOLTIP = "返回 空。";
Blockly.Msg.LOGIC_OPERATION_AND = "且";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations";
Blockly.Msg.LOGIC_OPERATION_OR = "或";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "如果這兩個輸入值都為 真，則返回 真。";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "如果至少一個輸入的值為 真，返回 真。";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "測試";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://en.wikipedia.org/wiki/%3F:";
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "如果為非";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "如果為真";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "檢查 'test' 中的條件。如果條件為 真，將返回 '如果為 真' 值 ；否則，返回 '如果為 否' 的值。";
Blockly.Msg.LONGITUDE = "Longitude";  // untranslated
Blockly.Msg.LOW = "低";
Blockly.Msg.HIGH = "高";

Blockly.Msg.MATH_ADDITION_SYMBOL = "+";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://en.wikipedia.org/wiki/Arithmetic";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "返回兩個數字的總和。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "返回兩個數字的商。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "返回兩個數字的差。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MODULO = "Return the remainder when one integer is divided by another.";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "返回兩個數字的乘積。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "返回第二個數字的指數的第一個數字。";
Blockly.Msg.MATH_CHANGE_HELPURL = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
Blockly.Msg.MATH_CHANGE_INPUT_BY = "增量";
Blockly.Msg.MATH_CHANGE_TITLE_CHANGE = "修改";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "將數字添加到變數 '%1'。";
Blockly.Msg.MATH_CHANGE_TOOLTIP1 = "將數字添加到變數 '";
Blockly.Msg.MATH_CHANGE_TOOLTIP2 = "'。";
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://en.wikipedia.org/wiki/Mathematical_constant";
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "返回一個的常見常量： π (3.141......)，e (2.718...)、 φ (1.618...)、 開方(2) (1.414......)、 開方(½) (0.707......) 或 ∞ （無窮大）。";
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_TITLE = "限制數字 %1 介於 (低) %2 到 (高) %3";
Blockly.Msg.MATH_CONSTRAIN_TITLE1 = "限制數字 ";
Blockly.Msg.MATH_CONSTRAIN_TITLE2 = " 介於 (低) ";
Blockly.Msg.MATH_CONSTRAIN_TITLE3 = " 到 (高) ";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "限制數字介於兩個指定的數字之間";
Blockly.Msg.MATH_DIVISION_SYMBOL = "÷";
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "可被整除";
Blockly.Msg.MATH_IS_EVEN = "是偶數";
Blockly.Msg.MATH_IS_NEGATIVE = "是負值";
Blockly.Msg.MATH_IS_ODD = "是奇數";
Blockly.Msg.MATH_IS_POSITIVE = "是正值";
Blockly.Msg.MATH_IS_PRIME = "是質數";
Blockly.Msg.MATH_IS_TOOLTIP = "如果數字是偶數，奇數，非負整數，正數、 負數或如果它是可被某數字整除，則返回 真 或 否。";
Blockly.Msg.MATH_IS_WHOLE = "是非負整數";
Blockly.Msg.MATH_MAP_APPENDTEXT_FROMHIGH = "由高";
Blockly.Msg.MATH_MAP_APPENDTEXT_FROMLOW = "由低";
Blockly.Msg.MATH_MAP_APPENDTEXT_MAP = "映射";
Blockly.Msg.MATH_MAP_APPENDTEXT_TOHIGH = "至高";
Blockly.Msg.MATH_MAP_APPENDTEXT_TOLOW = "至低";
Blockly.Msg.MATH_MAP_APPENDTEXT_VALUE = "數值";
Blockly.Msg.MATH_MAP_HELPURL = "http://arduino.cc/en/Reference/map";
Blockly.Msg.MATH_MAP_TOOLTIP = "將數值由一個區間映射至另一區間。";
Blockly.Msg.MATH_MAP_FLOAT_APPENDTEXT_MAP = "浮點數映射:"
Blockly.Msg.MATH_MODULO_HELPURL = "https://en.wikipedia.org/wiki/Modulo_operation";
Blockly.Msg.MATH_MODULO_SYMBOL = "%";
Blockly.Msg.MATH_MODULO_TITLE = "取餘數自 %1 ÷ %2";
Blockly.Msg.MATH_MODULO_TITLE1 = "取餘數自 ";
Blockly.Msg.MATH_MODULO_TITLE2 = " ÷ ";
Blockly.Msg.MATH_MODULO_TOOLTIP = "回傳兩個數字相除的餘數";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×";
Blockly.Msg.MATH_NUMBER_HELPURL = "https://en.wikipedia.org/wiki/Number";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "一個數字。";
Blockly.Msg.MATH_ONLIST_HELPURL = "";
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "平均值 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "最大值 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "中位數 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "最小值 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "比較眾數 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "隨機抽取 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "標準差 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "總和 自列表";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "返回列表中數值的平均值 （算術平均值）。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "返回列表中的最大數字。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "返回列表中數值的中位數。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "返回列表中的最小數字。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "返回一個列表中的最常見項目的列表。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "從列表中返回一個隨機的項目。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "返回列表中數字的標準差。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "返回列表中的所有數字的總和。";
Blockly.Msg.MATH_POWER_SYMBOL = "^";
Blockly.Msg.MATH_POW_BASE = "基數";
Blockly.Msg.MATH_POW_EXP = "指數";
Blockly.Msg.MATH_POW_HELPURL = "http://arduino.cc/en/Reference/pow";
Blockly.Msg.MATH_POW_TITLE = "乘方";
Blockly.Msg.MATH_POW_TOOLTIP = "Calculates the value of a number raised to a power.";  // untranslated
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "取隨機分數";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "返回介於 （包含） 0.0 到 1.0 之間的隨機數。";
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_INT_TITLE = "取隨機整數介於 (低) %1 到 %2";
Blockly.Msg.MATH_RANDOM_INT_TITLE1 = "取隨機整數介於 (低) ";
Blockly.Msg.MATH_RANDOM_INT_TITLE2 = " 到 ";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "回傳限制的數字區間內的隨機數字";
Blockly.Msg.MATH_RANDOM_MAX_MIN_APPENDTEXT_MAX = "最大";
Blockly.Msg.MATH_RANDOM_MAX_MIN_APPENDTEXT_MIN = "最小";
Blockly.Msg.MATH_RANDOM_MAX_MIN_APPENDTEXT_RANDOM = "隨機";
Blockly.Msg.MATH_RANDOM_MAX_MIN_HELPURL = "http://arduino.cc/en/Reference/Random";  // untranslated
Blockly.Msg.MATH_RANDOM_MAX_MIN_TOOLTIP = "The random function generates pseudo-random numbers.";  // untranslated
Blockly.Msg.MATH_ROUND_HELPURL = "https://en.wikipedia.org/wiki/Rounding";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "四捨五入";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "無條件捨去";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "無條件進位";
Blockly.Msg.MATH_ROUND_TOOLTIP = "將數字向上或向下舍入。";
Blockly.Msg.MATH_SINGLE_HELPURL = "https://en.wikipedia.org/wiki/Square_root";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "絕對值";
Blockly.Msg.MATH_SINGLE_OP_ROOT = "開根號";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "返回指定數字的絕對值。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "返回指定數字指數的 e";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "返回指定數字的自然對數。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "返回指定數字的對數。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "返回指定數字的 negation。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "返回指定數字指數的10的冪次。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "返回指定數字的平方根。";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";
Blockly.Msg.MATH_TRIG_ACOS = "反餘弦";
Blockly.Msg.MATH_TRIG_ASIN = "反正弦";
Blockly.Msg.MATH_TRIG_ATAN = "反正切";
Blockly.Msg.MATH_TRIG_COS = "餘弦";
Blockly.Msg.MATH_TRIG_HELPURL = "https://en.wikipedia.org/wiki/Trigonometric_functions";
Blockly.Msg.MATH_TRIG_SIN = "正弦";
Blockly.Msg.MATH_TRIG_TAN = "正切";
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "返回指定角度的反餘弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "返回指定角度的反正弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "返回指定角度的反正切值。";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "返回指定角度的餘弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "返回指定角度的正弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "返回指定角度的正切值(非弧度）。";
Blockly.Msg.MATH_DEGREE_TO_RADIAN_HELPURL = "https://en.wikipedia.org/wiki/Radian";
Blockly.Msg.MATH_DEGREE_TO_RADIAN_TITLE = "角度";
Blockly.Msg.MATH_DEGREE_TO_RADIAN_APPEND = "轉換為弧度";
Blockly.Msg.MATH_DEGREE_TO_RADIAN_TOOLTIP = "";
Blockly.Msg.ME = "我";
Blockly.Msg.MODE = "模式";

Blockly.Msg.NEW_VARIABLE = "新變數...";
Blockly.Msg.NEW_VARIABLE_TITLE = "新變數名稱:";
Blockly.Msg.OFF = "關";  // untranslated
Blockly.Msg.ON = "開";  // untranslated
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";  // untranslated
Blockly.Msg.PIN = "Pin";  // untranslated
Blockly.Msg.POPUP_SAVE_DONE = "儲存完成";  // untranslated
Blockly.Msg.PORT = "連接埠";  // untranslated
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "allow statements";  // untranslated
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "與：";
Blockly.Msg.PROCEDURES_CALLNORETURN_CALL = "呼叫";
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "執行使用者定義的函數 '%1'。";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP1 = "執行使用者定義的函數 '";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP2 = "'。";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "執行使用者定義的函數 '%1' 並使用它的回傳值";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP1 = "執行使用者定義的函數 '";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP2 = "' 並使用它的回傳值";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "與：";
Blockly.Msg.PROCEDURES_CREATE_DO = "建立 '%1'";
Blockly.Msg.PROCEDURES_CREATE_DO1 = "建立 '";
Blockly.Msg.PROCEDURES_CREATE_DO2 = "'";
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "子程序";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "函數";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "創建一個無回傳值的函數。";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "回傳";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "創建一個有回傳值的函數。";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "警告: 此函數中有重複的參數。";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "高亮顯示函式定義";
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "如果值為 真，則返回第二個值。";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "警告: 此積木僅可在定義函式時使用。";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "變數:";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "Add an input to the function.";  // untranslated
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "參數";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "Add, remove, or reorder inputs to this function.";  // untranslated
Blockly.Msg.RANGE_TITLE = "間隔（分）";  // untranslated
Blockly.Msg.RE = "re";  // untranslated
Blockly.Msg.REBOOT = "請重新啟動開發板";
Blockly.Msg.RED = "紅";  // untranslated
Blockly.Msg.REMOVE_COMMENT = "移除註解";
Blockly.Msg.RENAME_VARIABLE = "重新命名變數...";
Blockly.Msg.RENAME_VARIABLE_TITLE = "將所有 \"%1\" 變數重新命名為:";
Blockly.Msg.RENAME_VARIABLE_TITLE1 = "將所有 \"";
Blockly.Msg.RENAME_VARIABLE_TITLE2 = "\" 變數重新命名為:";
Blockly.Msg.REPLACE_TEXT1 = "取代既有的積木？";
Blockly.Msg.REPLACE_TEXT2 = "[Cancel] will merge.";  // untranslated

Blockly.Msg.RIGHT = "右";  // untranslated
Blockly.Msg.RISING = "上升邊緣";
Blockly.Msg.ROW = "Row";  // untranslated
Blockly.Msg.SAVE_XML = "儲存 XML";  // untranslated
Blockly.Msg.SAVE_FIRST = "請先儲存檔案，方能在IDE中開啟"

Blockly.Msg.SETTING = "設定";  // untranslated

Blockly.Msg.STRING = "字串";  // untranslated
Blockly.Msg.TERM = "終端機";  // untranslated
Blockly.Msg.TEXT = "字串";  // untranslated
Blockly.Msg.TEXTAREA_EXPORT_LABEL = "複製代碼";  // untranslated
Blockly.Msg.TEXTAREA_IMPORT_LABEL = "貼上代碼";  //Blockly.Msg.STRING untranslated
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "後加入字串";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_APPEND_TO = "在";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "將一些字串追加到變數 '%1'。";
Blockly.Msg.TEXT_APPEND_TOOLTIP1 = "將一些字串追加到變數 '";
Blockly.Msg.TEXT_APPEND_TOOLTIP2 = "'。";
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "轉成 小寫";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "轉成 首字母大寫";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "轉成 大寫";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "使用不同的大小寫複製這段字串。";
Blockly.Msg.TEXT_CHARAT_FIRST = "取第一個字元";
Blockly.Msg.TEXT_CHARAT_FROM_END = "取得 倒數第 # 個字元";
Blockly.Msg.TEXT_CHARAT_FROM_START1 = "取得第";
Blockly.Msg.TEXT_CHARAT_FROM_START2 = "字元";  // untranslated
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg.TEXT_CHARAT_INTEXT = "從字串";
Blockly.Msg.TEXT_CHARAT_LAST = "取最後一個字元";
Blockly.Msg.TEXT_CHARAT_RANDOM = "取隨機一個字元";
Blockly.Msg.TEXT_CHARAT_TAIL = "";
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "返回位於指定位置的字元。";
Blockly.Msg.TEXT_COMMENTOUT_APPENDTEXT = "註解掉";
Blockly.Msg.TEXT_COMMENTOUT_HELPURL = "";  // untranslated
Blockly.Msg.TEXT_COMMENTOUT_TOOLTIP = "";  // untranslated
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "將一個項目加入到字串中。";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "加入";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "添加、 刪除或重新排列各區塊來此重新配置這個字串積木。";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "到 倒數第 # 個字元";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "到 字元 #";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "到 最後一個字元";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "自字串";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "取得一段字串 自 第一個字元";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "取得一段字串自 #";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "取得一段字串自 #";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "返回指定的部分字串。";
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "在字串";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "尋找 第一個 出現的字串";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "尋找 最後一個 出現的字串";
Blockly.Msg.TEXT_INDEXOF_TAIL = "";  // untranslated
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "返回在第二個字串中的第一個/最後一個匹配項目的索引值。如果未找到則返回 0。";
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 為空";
Blockly.Msg.TEXT_ISEMPTY_TITLE1 = " 為空";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "如果提供的字串為空，則返回 真。";
Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "串接字串";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "通過串起任意數量字串或數字來建立一段字串。";
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_LENGTH_TITLE = "字串長度 %1";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "返回這串字串的字元數（含空格） 。";
Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg.TEXT_PRINT_TITLE = "印出 %1";
Blockly.Msg.TEXT_PRINT_TITLE1 = "印出 ";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "印出指定的字串、 數字或其他值。";
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "輸入數字";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "輸入字串";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "輸入 數字 並顯示提示訊息";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "輸入 字串 並顯示提示訊息";
Blockly.Msg.TEXT_TEXT_HELPURL = "https://en.wikipedia.org/wiki/String_(computer_science)";
Blockly.Msg.TEXT_TEXT_TOOLTIP = "字元、 單詞或一行字串。";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "消除兩側空格";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "消除左側空格";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "消除右側空格";
Blockly.Msg.TEXT_TRIM_TOOLTIP = "複製這段字串的同時刪除兩端多餘的空格。";



Blockly.Msg.URL = "URL";
Blockly.Msg.VALUE = "數值";
Blockly.Msg.VARIABLE = "變數";
Blockly.Msg.VARIABLES_DEFAULT_NAME = "項目";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "創立 '設定 %1'";
Blockly.Msg.VARIABLES_GET_CREATE_SET1 = "創立 '設定 ";
Blockly.Msg.VARIABLES_GET_CREATE_SET2 = "'";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg.VARIABLES_GET_TAIL = "";
Blockly.Msg.VARIABLES_GET_TITLE = "";
Blockly.Msg.VARIABLES_GET_TOOLTIP = "返回此變數的值。";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "建立 '取得 %1'";
Blockly.Msg.VARIABLES_SET_CREATE_GET1 = "建立 '取得 ";
Blockly.Msg.VARIABLES_SET_CREATE_GET2 = "'";
Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg.VARIABLES_SET_TAIL = "值";
Blockly.Msg.VARIABLES_SET_TITLE = "宣告";
Blockly.Msg.VARIABLES_SET_TOOLTIP = "設定此變數，好和輸入值相等。";
Blockly.Msg.VARIABLES_TYPE_ANY = "任意";
Blockly.Msg.VARIABLES_TYPE_ARRAY = "整數陣列";
Blockly.Msg.VARIABLES_TYPE_ARRAY1 = "字串陣列"
Blockly.Msg.VARIABLES_TYPE_ARRAY2 = "字元陣列"
Blockly.Msg.VARIABLES_TYPE_ARRAY2D = "二維整數陣列";
Blockly.Msg.VARIABLES_TYPE_BOOLEAN = "布林值";
Blockly.Msg.VARIABLES_TYPE_BYTE = "位元";
Blockly.Msg.VARIABLES_TYPE_CHAR = "字元";
Blockly.Msg.VARIABLES_TYPE_COLOUR = "顏色";
Blockly.Msg.VARIABLES_TYPE_DOUBLE = "倍精度浮點數";
Blockly.Msg.VARIABLES_TYPE_FLOAT = "浮點數";
Blockly.Msg.VARIABLES_TYPE_LONG = "長整數";
Blockly.Msg.VARIABLES_TYPE_NUMBER = "整數";
Blockly.Msg.VARIABLES_TYPE_STRING = "字串物件";
Blockly.Msg.VARIABLES_TYPE_UNSIGNED_INT = "正整數";
Blockly.Msg.VARIABLES_TYPE_UNSIGNED_LONG = "正長整數";
Blockly.Msg.VARIABLES_TYPE_VOLATILE_INT = "可變性整數";
Blockly.Msg.VARIABLES_TYPE_WORD = "存取字元";

Blockly.Msg.VARIABLES_TYPE_VOID = "空白 (void)";
Blockly.Msg.VARIABLES_TYPE_ARRAY = "陣列 (array)";
Blockly.Msg.VARIABLES_TYPE_BOOLEAN = "布林 (boolean)";
Blockly.Msg.VARIABLES_TYPE_BYTE = "位元組 (byte)";
Blockly.Msg.VARIABLES_TYPE_CHAR = "字元 (char)";
Blockly.Msg.VARIABLES_TYPE_CHAR1 = "字元 (char*)";
Blockly.Msg.VARIABLES_TYPE_CHAR2 = "字元 (const char*)";
Blockly.Msg.VARIABLES_TYPE_DOUBLE = "倍精度浮點數 (double)";
Blockly.Msg.VARIABLES_TYPE_FLOAT = "浮點數 (float)";
Blockly.Msg.VARIABLES_TYPE_INT = "整數 (int)";
Blockly.Msg.VARIABLES_TYPE_LONG = "長整數 (long)";
Blockly.Msg.VARIABLES_TYPE_SHORT = "短整數 (short)";
Blockly.Msg.VARIABLES_TYPE_SIZET = "字節大小 (size_t)";
Blockly.Msg.VARIABLES_TYPE_STRING = "字串 (String)";
Blockly.Msg.VARIABLES_TYPE_UNSIGNEDCHAR = "無號字元 (unsigned char)";
Blockly.Msg.VARIABLES_TYPE_UNSIGNEDINT = "無號整數 (unsigned int)";
Blockly.Msg.VARIABLES_TYPE_UNSIGNEDLONG = "無號長整數 (unsigned long)";
Blockly.Msg.VARIABLES_TYPE_UNSIGNEDWORD = "無號數 (word)";

	
Blockly.Msg.XML = "XML";
Blockly.Msg.YELLOW = "黃";
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.VARIABLES_SET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.VARIABLES_GET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_CALLRETURN_CALL = Blockly.Msg.PROCEDURES_CALLNORETURN_CALL;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;

Blockly.Msg.CATEGORY_EXTERNAL = "其他元件";
Blockly.Msg.CATEGORY_BETA = "未測試元件";
Blockly.Msg.CATEGORY_SENSOR = "感測模組";
Blockly.Msg.CATEGORY_DISPLAY = "顯示模組";
Blockly.Msg.CATEGORY_SENSING_ENV = "環境感測";
Blockly.Msg.CATEGORY_SENSING_DIST = "距離感測";
Blockly.Msg.CATEGORY_SENSING_MOTION = "動態感測";
Blockly.Msg.CATEGORY_TRANSCEIVER = "傳輸模組";
Blockly.Msg.CATEGORY_INFRARED = "紅外線";
Blockly.Msg.CATEGORY_RFID = "RFID";

Blockly.Msg.BUTTON_UPLOAD = "燒錄";
Blockly.Msg.BUTTON_LAUNCH_IDE = "啟動 Arduino IDE";
Blockly.Msg.BUTTON_BOARD_SETTINGS = "開發板設定";
Blockly.Msg.TEXT_UPLOADER_STATUS = "燒錄狀態";
Blockly.Msg.TEXT_BOARD = "開發板";
Blockly.Msg.TEXT_COM_PORT = "連接埠";
Blockly.Msg.DROPDOWN_SCANNING = "掃描連接埠當中...";


Blockly.Msg.TEMPERATURE_CELCIUS = "溫度（°C）";
Blockly.Msg.TEMPERATURE_FERENHEIT = "溫度（°F）";
Blockly.Msg.HUMIDITY_PERCENT = "相對濕度（%）";  // untranslated
Blockly.Msg.SIGNAL_PIN = "訊號：";  // untranslated
Blockly.Msg.MESUREMENT_TYPE = "量測數值：";
Blockly.Msg.CATEGORY_OLED = "OLED顯示";

Blockly.Msg.ADXL345_HELPURL = "https://github.com/adafruit/Adafruit_ADXL345";
Blockly.Msg.ADXL345_READ_X = "X 軸";
Blockly.Msg.ADXL345_READ_Y = "Y 軸";
Blockly.Msg.ADXL345_READ_Z = "Z 軸";
Blockly.Msg.ADXL345_TITLE = "加速規";
Blockly.Msg.ADXL345_TOOLTIP = "ADXL345 加速規，具備 I2C 介面";
Blockly.Msg.ADXL345_UNIT = "G值";
Blockly.Msg.ADXL345_DETECT = "偵測動作、手勢";
Blockly.Msg.ADXL345_GESTURE_DETECTED = "已經偵測到";
Blockly.Msg.ADXL345_TAP = "點一下";
Blockly.Msg.ADXL345_DOUBLE_TAP = "點兩下";
Blockly.Msg.ADXL345_MOTION = "移動";
Blockly.Msg.ADXL345_ATTITUDE = "取得姿態：";
Blockly.Msg.ADXL345_PITCH = "俯仰";
Blockly.Msg.ADXL345_ROLL = "翻滾";
Blockly.Msg.ADXL345_DEGREE = "角度\u00b0";


Blockly.Msg.DHT_HELPURL = "https://github.com/adafruit/DHT-sensor-library";  // untranslated
Blockly.Msg.DHT_TITLE = "溫濕度計";
Blockly.Msg.DHT_TOOLTIP = "The DHT sensors are made of two parts, a capacitive humidity sensor and a thermistor.";  // untranslated
Blockly.Msg.DHT_WARNING = "Need to install the (adafruit) DHT-sensor-library";  // untranslated

Blockly.Msg.HTU21D_HELPURL = "https://github.com/sparkfun/SparkFun_HTU21D_Breakout_Arduino_Library/blob/master/src/SparkFunHTU21D.h";
Blockly.Msg.HTU21D_TITLE = "高精度溫濕度計";
Blockly.Msg.HTU21D_TOOLTIP = "高精度溫濕度計 HTU21D，具備I2C介面，需要安裝 SparkFun HTU21D 函式庫";

Blockly.Msg.INFRA_RED_HELPURL = "控制紅外線傳送器與接收器。如果接收失敗，會得到0";
Blockly.Msg.INFRA_RED_SEND_TEXT_PARAM = "發送整數（僅限 Pin 3）"
Blockly.Msg.INFRA_RED_RECEIVE_TEXT_PARAM = "接收整數"
Blockly.Msg.INFRA_RED_SEND_TITLE = "紅外線發送器";
Blockly.Msg.INFRA_RED_RECEIVE_TITLE = "紅外線接收器";

Blockly.Msg.OLED_DISPLAY_HELPURL = "http://wiki.seeed.cc/Grove-OLED_Display_0.96inch/";
Blockly.Msg.OLED_DISPLAY_TITLE = "OLED顯示";
Blockly.Msg.OLED_DISPLAY_DRAW_COMMANDS = "顯示內容："
Blockly.Msg.OLED_DISPLAY_CLEAR = "清除畫面";
Blockly.Msg.OLED_DISPLAY_SET_CURSOR = "設定游標　行：";
Blockly.Msg.OLED_DISPLAY_SET_CURSOR_SEP = "　列：";
Blockly.Msg.OLED_DISPLAY_SET_CURSOR_APPEND = "";
Blockly.Msg.OLED_DISPLAY_PUT = "於游標處列印";
Blockly.Msg.OLED_DISPLAY_TOOLTIP = "用 u8g2 函式庫來驅動 I2C 介面的 128×64 點陣 OLED 顯示器。支援 SH1106、SH1306 等型號";

Blockly.Msg.OLED_DISPLAY_DRAW_LINE_START = "畫線 起點：";
Blockly.Msg.OLED_DISPLAY_DRAW_LINE_END = "終點：";
Blockly.Msg.OLED_DISPLAY_DRAW_BOX_START = "繪製實心方塊 左上角：";
Blockly.Msg.OLED_DISPLAY_DRAW_BOX_END = "右下角：";
Blockly.Msg.OLED_DISPLAY_DRAW_FRAME_START = "繪製方框 左上角：";
Blockly.Msg.OLED_DISPLAY_DRAW_FRAME_END = "右下角：";
Blockly.Msg.OLED_DISPLAY_DRAW_DISC_CENTER = "繪製實心圓盤 中心點：";
Blockly.Msg.OLED_DISPLAY_DRAW_DISC_RADIUS = "半徑：";
Blockly.Msg.OLED_DISPLAY_DRAW_CIRCLE_CENTER = "繪製圓形 中心點：";
Blockly.Msg.OLED_DISPLAY_DRAW_CIRCLE_RADIUS = "半徑：";
Blockly.Msg.OLED_DISPLAY_SET_FONT = "設定字串大小";
Blockly.Msg.OLED_DISPLAY_SET_FONT_LARGE = "大";
Blockly.Msg.OLED_DISPLAY_SET_FONT_SMALL = "小";
Blockly.Msg.OLED_DISPLAY_DRAW_TEXT_START = "繪製字串 起點：";
Blockly.Msg.OLED_DISPLAY_DRAW_TEXT_CONTENT = "內容字串：";

Blockly.Msg.LCD_I2C_HELPURL = "http://wiki.seeed.cc/Grove-LCD_I2C_0.96inch/";
Blockly.Msg.LCD_I2C_TITLE = "液晶顯示";
Blockly.Msg.LCD_I2C_CLEAR = "清除畫面";
Blockly.Msg.LCD_I2C_SET_CURSOR = "設定游標　行：";
Blockly.Msg.LCD_I2C_SET_CURSOR_SEP = "　列：";
Blockly.Msg.LCD_I2C_SET_CURSOR_APPEND = "";
Blockly.Msg.LCD_I2C_PUT = "顯示";
Blockly.Msg.LCD_I2C_TOOLTIP = "透過 I2C 連接的 LCD 顯示螢幕，支援背光以及兩種不同的尺寸（1602 與 2004）";
Blockly.Msg.LCD_I2C_I2C_ADDRESS = "I2C位址";
Blockly.Msg.LCD_I2C_LIGHT = "背光";
Blockly.Msg.LCD_I2C_ON = "開";
Blockly.Msg.LCD_I2C_OFF = "關";

Blockly.Msg.PMS_HELPURL = "https://github.com/fu-hsi/PMS";
Blockly.Msg.PMS_RECEIVE_TITLE = "PM2.5感測器";
Blockly.Msg.PMS_READ_VALIE = "讀取";

Blockly.Msg.MPU9250_HELPURL = "https://github.com/sparkfun/SparkFun_MPU-9250_Breakout_Arduino_Library";
Blockly.Msg.MPU9250_READ_X = "X 軸";
Blockly.Msg.MPU9250_READ_Y = "Y 軸";
Blockly.Msg.MPU9250_READ_Z = "Z 軸";
Blockly.Msg.MPU9250_TITLE = "慣性感測單元";
Blockly.Msg.MPU9250_GROVE_TITLE = "慣性感應器9DOF";
Blockly.Msg.MPU9250_TOOLTIP = "MPU9250慣性感測單元，具備I2C介面";
Blockly.Msg.MPU9250_DEGREE = "角度\u00b0";
Blockly.Msg.MPU9250_ACC = "量測加速度：";
Blockly.Msg.MPU9250_ACC_UNIT = "G值";
Blockly.Msg.MPU9250_GYRO = "量測角速度：";
Blockly.Msg.MPU9250_GYRO_UNIT = "度/秒";
Blockly.Msg.MPU9250_MAG = "量測磁強度：";
Blockly.Msg.MPU9250_MAG_UNIT = "高斯";
Blockly.Msg.MPU9250_ATTITUDE = "取得姿態：";
Blockly.Msg.MPU9250_PITCH = "俯仰";
Blockly.Msg.MPU9250_ROLL = "翻滾";
Blockly.Msg.MPU9250_YAW = "偏擺";
Blockly.Msg.MPU9250_NORTH = "取得X軸與磁北極夾角";

Blockly.Msg.GROVE_IMU_9DOF_HELPURL = "https://github.com/sparkfun/SparkFun_MPU-9250_Breakout_Arduino_Library";
Blockly.Msg.GROVE_IMU_9DOF_READ_X = "X 軸";
Blockly.Msg.GROVE_IMU_9DOF_READ_Y = "Y 軸";
Blockly.Msg.GROVE_IMU_9DOF_READ_Z = "Z 軸";
Blockly.Msg.GROVE_IMU_9DOF_TITLE = "慣性感應器9DOF";
Blockly.Msg.GROVE_IMU_9DOF_GROVE_TITLE = "慣性感應器9DOF";
Blockly.Msg.GROVE_IMU_9DOF_TOOLTIP = "MPU9250慣性感測單元，具備I2C介面";
Blockly.Msg.GROVE_IMU_9DOF_DEGREE = "角度\u00b0";
Blockly.Msg.GROVE_IMU_9DOF_ACC = "量測加速度：";
Blockly.Msg.GROVE_IMU_9DOF_ACC_UNIT = "G值";
Blockly.Msg.GROVE_IMU_9DOF_GYRO = "量測角速度：";
Blockly.Msg.GROVE_IMU_9DOF_GYRO_UNIT = "度/秒";
Blockly.Msg.GROVE_IMU_9DOF_MAG = "量測磁強度：";
Blockly.Msg.GROVE_IMU_9DOF_MAG_UNIT = "高斯";
Blockly.Msg.GROVE_IMU_9DOF_ATTITUDE = "取得姿態：";
Blockly.Msg.GROVE_IMU_9DOF_PITCH = "俯仰";
Blockly.Msg.GROVE_IMU_9DOF_ROLL = "翻滾";
Blockly.Msg.GROVE_IMU_9DOF_YAW = "偏擺";
Blockly.Msg.GROVE_IMU_9DOF_NORTH = "取得X軸與磁北極夾角";

Blockly.Msg.MFRC522_RFID_HELPURL = "https://github.com/miguelbalboa/rfid";  // untranslated
Blockly.Msg.MFRC522_RFID_TITLE = "RFID";
Blockly.Msg.MFRC522_RFID_READ = "讀取識別碼"
Blockly.Msg.MFRC522_RFID_TOOLTIP = "如果有感應到識別卡，會回傳識別碼。如果沒有，則會回傳空字串。"

Blockly.Msg.EEPROM_LENGTH_HELPURL = "https://www.arduino.cc/en/Reference/EEPROM";
Blockly.Msg.EEPROM_LENGTH_TITLE = "EEPROM 容量";
Blockly.Msg.EEPROM_LENGTH_TOOLTIP = "取得 EEPROM 可以容納的位元組數量";
Blockly.Msg.EEPROM_WRITE_HELPURL = "https://www.arduino.cc/en/Reference/EEPROM";
Blockly.Msg.EEPROM_WRITE_TITLE = "寫入到 EEPROM 位址：";
Blockly.Msg.EEPROM_WRITE_TOOLTIP = "The address in EEPROM and the byte value to write";
Blockly.Msg.EEPROM_READ_HELPURL = "https://www.arduino.cc/en/Reference/EEPROM";
Blockly.Msg.EEPROM_READ_TITLE = "從 EEROM 讀取 位址：";
Blockly.Msg.EEPROM_READ_TOOLTIP = "第一個參數指定要讀取的位址";
Blockly.Msg.EEPROM_ADDRESS = "位址"
Blockly.Msg.EEPROM_VALUE = "數值："

// mooncar
Blockly.Msg.CATEGORY_MOONCAR = "登月小車";
Blockly.Msg.MOONCAR_HELPURL = "登月小車";
Blockly.Msg.MOVE_CAR = "登月小車移動";
Blockly.Msg.FORWARD = "前進";
Blockly.Msg.BACKWARD = "後退";
Blockly.Msg.LEFT = "左轉";
Blockly.Msg.RIGHT = "右轉";
Blockly.Msg.STOP = "停止";
Blockly.Msg.MOVE_SPEED = "速度(0~255)";
Blockly.Msg.MOVE_CAR_TOOLTIP = "用於登月小車移動";
Blockly.Msg.MOVE_MOTOR_L = "登月小車左輪速度";
Blockly.Msg.MOVE_MOTOR_R = "登月小車右輪速度";
Blockly.Msg.TRACKER = "循線感測器";
Blockly.Msg.SONAR = "超音波距離感測器";
Blockly.Msg.BUTTON = "按鈕";
Blockly.Msg.BUTTON_CHECK = "有被按下嗎?";
Blockly.Msg.INIT_TCS = "顏色感測器初始化並設定容許誤差:";
Blockly.Msg.READ_TCS = "顏色感測器讀取";
Blockly.Msg.RED = "紅色";
Blockly.Msg.GREEN = "綠色";
Blockly.Msg.BLUE = "藍色";
Blockly.Msg.READ_VALUE = "通道數值";
Blockly.Msg.FLASH_LIGHT = "補光燈";
Blockly.Msg.ON = "開啟";
Blockly.Msg.OFF = "關閉";
Blockly.Msg.IR_REMOTE_READ = "讀取到紅外線遙控器訊號?";
Blockly.Msg.IR_REMOTE_READ_VALUE = "紅外線遙控器訊號(字串)";
Blockly.Msg.IR_REMOTE_READ_TYPE = "紅外線訊號類型(字串)"
Blockly.Msg.IR_REMOTE_TYPE = "紅外線類型";
Blockly.Msg.IR_REMOTE_SEND = "發送紅外線訊號(字串)";
Blockly.Msg.FACE_SHOW = "OLED 顯示表情";
Blockly.Msg.face_F1 = "淡定";
Blockly.Msg.face_F2 = "不高興";
Blockly.Msg.face_F3 = "微笑";
Blockly.Msg.face_F4 = "無奈";
Blockly.Msg.face_F5 = "生氣";
Blockly.Msg.face_F6 = "開心";
Blockly.Msg.face_F7 = "驚訝";
Blockly.Msg.face_F8 = "眨眼";
Blockly.Msg.face_F9 = "流淚";
Blockly.Msg.RECORD_TCS = "紀錄";
Blockly.Msg.RECORD_VALUE = "顏色數值";
Blockly.Msg.YELLO = "黃色";
Blockly.Msg.AZURE = "天藍色";
Blockly.Msg.PURPLE = "紫色";
Blockly.Msg.C1 = "自訂1";
Blockly.Msg.C2 = "自訂2";
Blockly.Msg.C3 = "自訂3";
Blockly.Msg.CHACK_TCS = "檢查顏色是否為紀錄的";
Blockly.Msg.CHACK_VALUE = "?";

// ez_start_kit
Blockly.Msg.CATEGORY_ZE_START_KIT = "EZ Start Kit";
Blockly.Msg.EZ_HELPURL = "EZ Start Kit";
Blockly.Msg.EZ_TOOLTIP = "EZ Start Kit";
Blockly.Msg.EZ_BUTTON = "按鈕";
Blockly.Msg.EZ_BUTTON_CHECK = "有被按下嗎?";
Blockly.Msg.EZ_VR = "可變電阻";
Blockly.Msg.EZ_PHR = "光敏電阻";
Blockly.Msg.EZ_DHT = "DHT11溫濕度感測器";
Blockly.Msg.EZ_DHT_TEMP = "溫度";
Blockly.Msg.EZ_DHT_HUMID = "濕度%";
Blockly.Msg.EZ_RELAY = "繼電器";
Blockly.Msg.EZ_RELAY_ON = "開啟";
Blockly.Msg.EZ_RELAY_OFF = "關閉";
Blockly.Msg.EZ_IR_REMOTE_READ = "讀取到紅外線遙控器訊號?";
Blockly.Msg.EZ_IR_REMOTE_READ_VALUE = "紅外線遙控器訊號(字串)";
Blockly.Msg.EZ_IR_REMOTE_READ_TYPE = "紅外線訊號類型(字串)";
Blockly.Msg.EZ_TONE = "蜂鳴器";
Blockly.Msg.EZ_noTONE = "停止蜂鳴器";
Blockly.Msg.EZ_LED = "LED燈";
Blockly.Msg.EZ_LED_RED = "紅色";
Blockly.Msg.EZ_LED_YELLOW = "黃色";
Blockly.Msg.EZ_LED_GREEN = "綠色";
Blockly.Msg.EZ_LED_VALUE = "亮度(0~255)";
Blockly.Msg.EZ_NEOPIXEL_BEGIN_BRIGHTNESS = "初始化並設定RGB LED 亮度(0~255)";
Blockly.Msg.EZ_NEOPIXEL_TITLE = "RGB LED";
Blockly.Msg.EZ_NEOPIXEL_CLEAR = "關閉RGB LED";
Blockly.Msg.EZ_OLED_DISPLAY_ALBUM = "自訂OLED點陣圖(128*64)";
Blockly.Msg.custom_C1 = "自訂1";
Blockly.Msg.custom_C2 = "自訂2";
Blockly.Msg.custom_C3 = "自訂3";
Blockly.Msg.custom_C4 = "自訂4";
Blockly.Msg.custom_C5 = "自訂5";
Blockly.Msg.custom_C6 = "自訂6";
Blockly.Msg.custom_C7 = "自訂7";
Blockly.Msg.custom_C8 = "自訂8";
Blockly.Msg.custom_C9 = "自訂9";
Blockly.Msg.custom_C10 = "自訂10";
Blockly.Msg.show_album = "顯示OLED點陣圖";
Blockly.Msg.EZ_OLED_DISPLAY_ALBUM_NAME = "自訂OLED點陣圖(128*64)名稱:";
Blockly.Msg.EZ_OLED_DISPLAY_ALBUM_XBM = "XBM:";
Blockly.Msg.SHOW_ALBUM_NAME = "顯示OLED點陣圖名稱:";

// RockBot
Blockly.Msg.CATEGORY_RockBot = "RockBot";
Blockly.Msg.RockBot_HELPURL = "RockBot";
Blockly.Msg.RockBot_MOTOR_GO = "RockBot 動作";
Blockly.Msg.Move_forward = "前進";
Blockly.Msg.Move_back = "後退";
Blockly.Msg.Move_turnleft = "左轉";
Blockly.Msg.Move_turnright = "右轉";
Blockly.Msg.Move_left = "左移";
Blockly.Msg.Move_right = "右移";
Blockly.Msg.Move_frontright = "右前";
Blockly.Msg.Move_backleft = "左後";
Blockly.Msg.Move_frontleft = "左前";
Blockly.Msg.Move_backright = "右後";
Blockly.Msg.Move_stop = "停止";
Blockly.Msg.RockBot_MOTOR_SPEED = "速度(0~127)";
Blockly.Msg.RockBot_TOOLTIP = "RockBot";
Blockly.Msg.RockBot_motor_LF = "RockBot 控制輪子速度 左前";
Blockly.Msg.RockBot_motor_RF = "右前";
Blockly.Msg.RockBot_motor_LB = "左後";
Blockly.Msg.RockBot_motor_RB = "右後";
Blockly.Msg.RockBot_SERVO = "RockBot 控制伺服馬達";
Blockly.Msg.SERVO1 = "S1";
Blockly.Msg.SERVO2 = "S2";
Blockly.Msg.RockBot_SERVO_DEGREE = "角度";
//Blockly.Msg.RockBot_SERVO_PULSE = "脈衝";
Blockly.Msg.RockBot_IO_DIGITAL_WRITE = "數位寫入";
Blockly.Msg.IO1 = "IO1(A1)";
Blockly.Msg.IO2 = "IO2(A2)";
Blockly.Msg.IO3 = "IO3(A3)";
Blockly.Msg.IO4 = "IO4(P13)";
Blockly.Msg.IO5 = "IO5(P12)";
Blockly.Msg.IO6 = "IO6(P11)";
Blockly.Msg.IO7 = "IO7(P10)";
Blockly.Msg.RockBot_IO_DIGITAL_READ = "數位讀取";
Blockly.Msg.RockBot_IO_ANALOG_WRITE = "類比寫入";
Blockly.Msg.RockBot_IO_ANALOG_Read = "類比讀取";
Blockly.Msg.LeftLight = "左側車燈";
Blockly.Msg.RightLight = "右側車燈";

// NFC/RFID
Blockly.Msg.CATEGORY_NFC_RFID = "RFID/NFC";
Blockly.Msg.NFC_RFID_HELPURL = "RFID/NFC PN532";
Blockly.Msg.NFC_RFID_setup_TITLE = "初始化PN532 並設定IRQ 為";
Blockly.Msg.NFC_RFID_setup_IRQ_TITLE = "號腳位";
Blockly.Msg.NFC_RFID_TOOLTIP = "RFID/NFC";
Blockly.Msg.NFC_RFID_read_TITLE = "PN532 讀取卡片";
Blockly.Msg.NFC_RFID_read_sector_TITLE = "PN532 讀取 Sector:";
Blockly.Msg.NFC_RFID_read_block_TITLE = "Block:";
Blockly.Msg.NFC_RFID_write_sector_TITLE = "PN532 寫入 Sector:";
Blockly.Msg.NFC_RFID_write_data_TITLE = "資料(String)";
Blockly.Msg.NFC_RFID_FORMAT_TITLE = "PN532 格式化卡片 (NDEF)";
Blockly.Msg.mfrc522_read_nostop_TITLE = "MFRC522 讀取卡片(不進入停止模式)";
Blockly.Msg.mfrc522_read_sector_TITLE = "MFRC522 讀取 Sector:";
Blockly.Msg.mfrc522_read_block_TITLE = "Block";
Blockly.Msg.mfrc522_write_sector_TITLE = "MFRC522 寫入 Sector:";
Blockly.Msg.mfrc522_write_block_TITLE = "Block";
Blockly.Msg.mfrc522_write_data_TITLE = "資料(最多16個字元)";
Blockly.Msg.mfrc522_stop_TITLE = "讓卡片進入停止模式";

// M5Stack Stick V/Unit V
Blockly.Msg.CATEGORY_M5STACK_V = "M5Stack V";
Blockly.Msg.CATEGORY_MOTION_DETECT = "運動感測";
Blockly.Msg.M5_HELPURL = "M5Stack V";
Blockly.Msg.M5_TOOLTIP = "M5Stack V";
Blockly.Msg.M5_Serial_Set = "M5Stack V 連接";
Blockly.Msg.M5_Motion_Detect_Mode = "設定感測模式"
Blockly.Msg.M5_STATIC = "靜態";
Blockly.Msg.M5_DYNAMIC = "動態";
Blockly.Msg.M5_Motion_Detect_Thr = "設定變化閾值";
Blockly.Msg.M5_Motion_Detect_Scan1 = "設定掃描間隔 x";
Blockly.Msg.M5_Motion_Detect_Scan2 = "y";
Blockly.Msg.M5_Motion_Detect_Main = "取得感測影像";
Blockly.Msg.M5_DIFF_TOTAL = "變化率";
Blockly.Msg.M5_DIFF_MAX = "最大變化量";
Blockly.Msg.M5_TOTAL = "框選數量";
Blockly.Msg.M5_Motion_Detect_Data_Box = "取得框選編號";
Blockly.Msg.M5_Motion_Detect_Data_Choose = "資料選擇";

Blockly.Msg.M5_X = "x座標";
Blockly.Msg.M5_Y = "y座標";
Blockly.Msg.M5_W = "寬度";
Blockly.Msg.M5_H = "高度";
Blockly.Msg.M5_AREA = "像素數量";
Blockly.Msg.CATEGORY_TARGET_TRACE = "目標追隨";
Blockly.Msg.M5_Target_Trace_Set_x = "設定目標追隨範圍 x座標";
Blockly.Msg.M5_Target_Trace_Set_y = "y座標";
Blockly.Msg.M5_Target_Trace_Set_w = "寬度";
Blockly.Msg.M5_Target_Trace_Set_h = "高度";
Blockly.Msg.M5_target_trace_Data_Choose = "取得目標資料類別";

Blockly.Msg.CATEGORY_COLOR_TRACE = "顏色追隨";
Blockly.Msg.M5_Color_Trace_Lmin = "設定LAB檢測閾值 L-min";
Blockly.Msg.M5_Color_Trace_Lmax = "L-max";
Blockly.Msg.M5_Color_Trace_Amin = "A-min";
Blockly.Msg.M5_Color_Trace_Amax = "A-max";
Blockly.Msg.M5_Color_Trace_Bmin = "B-min";
Blockly.Msg.M5_Color_Trace_Bmax = "B-max";
Blockly.Msg.M5_Color_Trace_Scanx = "設定掃描間隔 x";
Blockly.Msg.M5_Color_Trace_Scany = "y";
Blockly.Msg.M5_Color_Trace_Merge = "設定邊界擬合閾值";
Blockly.Msg.M5_Color_Trace_thrw = "設定邊界寬度閾值";
Blockly.Msg.M5_Color_Trace_thrh = "高度";
Blockly.Msg.M5_Color_Trace_Count = "取得追隨目標數量";
Blockly.Msg.M5_Color_Trace_Data_Box = "取得目標編號";
Blockly.Msg.M5_Color_Trace_Data_Choose = "資料選擇";

Blockly.Msg.CATEGORY_FACE_DETECT = "人臉檢測";
Blockly.Msg.M5_Face_Detect_Count = "取得人臉檢測數量";
Blockly.Msg.M5_Face_Detect_Data_Box = "取得人臉編號";
Blockly.Msg.M5_Face_Detect_Data_Choose = "資料選擇";
Blockly.Msg.M5_value = "符合率";

Blockly.Msg.CATEGORY_QR_CODE = "QR Code辨識";
Blockly.Msg.M5_QR_Code_Set = "設定為QR code辨識模式";
Blockly.Msg.M5_QR_Code_Count = "取得QR code辨識掃描數量";
Blockly.Msg.M5_QR_Code_Data1 = "取得QR code辨識編號";
Blockly.Msg.M5_QR_Code_Data2 = "掃描字串";

Blockly.Msg.CATEGORY_Bar_CODE = "條碼辨識";
Blockly.Msg.M5_Bar_Code_Set = "設定為條碼辨識模式";
Blockly.Msg.M5_Bar_Code_Count = "取得條碼辨識掃描數量";
Blockly.Msg.M5_Bar_Code_Data1 = "取得條碼辨識編號";
Blockly.Msg.M5_Bar_Code_Data2 = "掃描字串";

Blockly.Msg.CATEGORY_Datamatrix_CODE = "Datamatrix編碼辨識";
Blockly.Msg.M5_Datamatrix_Code_Set = "設定為Datamatrix編碼辨識模式";
Blockly.Msg.M5_Datamatrix_Code_Count = "取得Datamatrix編碼掃描數量";
Blockly.Msg.M5_Datamatrix_Code_Data1 = "取得Datamatrix編碼辨識編號";
Blockly.Msg.M5_Datamatrix_Code_Data2 = "掃描字串";

Blockly.Msg.CATEGORY_April_TAG = "AprilTag編碼辨識";
Blockly.Msg.M5_April_Tag_Set = "設定為AprilTag編碼辨識模式";
Blockly.Msg.M5_April_Tag_Count = "取得AprilTag編碼掃描數量";
Blockly.Msg.M5_April_Tag_Data = "取得AprilTag編碼辨識編號";
Blockly.Msg.M5_April_Tag_Data_Choose = "掃描字串";
Blockly.Msg.M5_id = "編碼";
Blockly.Msg.M5_family = "編碼類別";

Blockly.Msg.CATEGORY_Tag_Reader = "自定義標籤辨識";
Blockly.Msg.M5_Tag_Reader_Count = "取得自定義標籤掃描數量";
Blockly.Msg.M5_Tag_Reader_Data = "取得自定義標籤辨識編號";
Blockly.Msg.M5_Tag_Reader_Data_Choose = "掃描字串";
Blockly.Msg.M5_code = "編碼";
Blockly.Msg.M5_binstr = "二進制資料";

Blockly.Msg.CATEGORY_Line_Tracker = "線路循跡";
Blockly.Msg.M5_line_tracker_w0 = "設定線路區域權重0";
Blockly.Msg.M5_line_tracker_w1 = "權重1";
Blockly.Msg.M5_line_tracker_w2 = "權重2";
Blockly.Msg.M5_line_tracker_data = "取得轉彎角度";

// PCA9685
Blockly.Msg.CATEGORY_PCA9685 = "PCA9685";
Blockly.Msg.PCA9685_HELPURL = "PCA9685";
Blockly.Msg.PCA9685_init = "PCA9685 初始化";
Blockly.Msg.pwm_channel = "PWM 輸出連接腳位";
Blockly.Msg.pwm_value = "數值";
Blockly.Msg.PCA9685_TOOLTIP = "PCA9685";
Blockly.Msg.servo_pulse_min = "設定伺服馬達脈衝寬度最小值";
Blockly.Msg.servo_pulse_max = "最大值";
Blockly.Msg.servo_channel = "伺服馬達輸出連接腳位";
Blockly.Msg.servo_degree = "角度";

// Sensor Big
Blockly.Msg.CATEGORY_SENSOR_BIG = "感測模組擴充";
Blockly.Msg.sensor_big_HELPURL = "Sensor Big";
Blockly.Msg.sensor_big_TOOLTIP = "Sensor Big";
Blockly.Msg.PMS5003_T_TITLE = "PM2.5 感測器連接";
Blockly.Msg.PMS5003_T_LAST = "讀取資料";
Blockly.Msg.PMS_READ_VALIE = "取得PM2.5 感測器資料";
Blockly.Msg.PMS5003_T_TEMP = "溫度(PMS5003T)";
Blockly.Msg.PMS5003_T_HUMID = "濕度(PMS5003T)";
Blockly.Msg.SGP30_TITLE = "SGP30 感測器連接";
Blockly.Msg.SGP30_LAST = "讀取資料";
Blockly.Msg.SGP30_READ_TYPE = "取得SGP30 感測器資料";
Blockly.Msg.SGP30_TVOC = "TVOC";
Blockly.Msg.SGP30_eCO2 = "eCO2";
Blockly.Msg.M5_MINI_RFID = "M5 Mini RFID 讀取識別碼(I2C)";

// HUSKYLENS
Blockly.Msg.CATEGORY_HUSKYLENS = "HuskyLens";
Blockly.Msg.HUSKYLENS_HELPURL = "HuskyLens";
Blockly.Msg.HUSKYLENS_I2C_INIT = "HuskyLens I2C 連線初始化直到成功";
Blockly.Msg.HUSKYLENS_UART_INIT = "HuskyLens 序列埠: 9600 連線";
Blockly.Msg.HUSKYLENS_UART_INIT2 = "初始化直到成功";
Blockly.Msg.HUSKYLENS_TOOLTIP = "HuskyLens";
Blockly.Msg.HUSKYLENS_SET_MODE = "HuskyLens 設定模式:";
Blockly.Msg.FACE_RECOGNITION = "人臉辨識";
Blockly.Msg.OBJECT_TRACKING = "物體追蹤";
Blockly.Msg.OBJECT_RECOGNITION = "物體辨識";
Blockly.Msg.LINE_TRACKING = "線道跟隨";
Blockly.Msg.COLOR_RECOGNITION = "顏色辨識";
Blockly.Msg.TAG_RECOGNITION = "標籤辨識";
Blockly.Msg.OBJECT_CLASSIFICATION = "物體分類";
Blockly.Msg.HUSKYLENS_READ_DATA = "從HuskyLens 獲得一組數據";
Blockly.Msg.GET_DATA_BLOCK = "取得框選數據:";
Blockly.Msg.B_XCENTER = "中心點X 座標";
Blockly.Msg.B_YCENTER = "中心點Y 座標";
Blockly.Msg.B_WIDTH = "框選寬度";
Blockly.Msg.B_HEIGHT = "框選高度";
Blockly.Msg.B_ID = "ID 編號";
Blockly.Msg.GET_DATA_ARROW = "取得箭頭數據";
Blockly.Msg.A_XORIGIN = "起點X 座標";
Blockly.Msg.A_YORIGIN = "起點Y 座標";
Blockly.Msg.A_XTARGET = "目標X 座標";
Blockly.Msg.A_YTARGET = "目標Y 座標";
Blockly.Msg.A_ID = "ID 編號";
Blockly.Msg.HUSKYLENS_SHOWTEXT = "螢幕顯示字串:";
Blockly.Msg.HUSKYLENS_XAXIS = "X 座標:";
Blockly.Msg.HUSKYLENS_YAXIS = "Y 座標:";
Blockly.Msg.HUSKYLENS_CLEAR_SCREEN = "清除螢幕顯示";
Blockly.Msg.HUSKYLENS_COUNT_LEARNED = "取得螢幕上已學習的ID 總數";
Blockly.Msg.HUSKYLENS_WRITE_LEARN = "學習當前目標並賦予ID 編號:";
Blockly.Msg.HUSKYLENS_WRITE_FORGET = "忘記所有學習數據";
Blockly.Msg.HUSKYLENS_LEARNED_ID = "ID 編號:";
Blockly.Msg.HUSKYLENS_LEARNED_ID2 = "是否已學習?";
Blockly.Msg.HUSKYLENS_SET_ID = "設定ID 編號:";
Blockly.Msg.HUSKYLENS_SET_NAME = "名稱為:";
Blockly.Msg.HUSKYLENS_SAVE_PICTURE_SD = "擷取畫面保存到SD 卡";
Blockly.Msg.HUSKYLENS_SG_MODEL_SD = "模型";
Blockly.Msg.HUSKYLENS_CHOOSE_ID = "至SD 卡編號為:";
Blockly.Msg.MODE_SAVE = "儲存";
Blockly.Msg.MODE_LOAD = "讀取";



Blockly.Msg["CATVARIABLES"] = "變數";
Blockly.Msg["CATPROCEDURES"] = "函數";
Blockly.Msg["CATLOGIC"] = "邏輯";
Blockly.Msg["CATLOOPS"] = "迴圈";
Blockly.Msg["CATMATH"] = "數值";
Blockly.Msg["CATTEXTS"] = "字串";
Blockly.Msg["CATTRANSFORM"] = "轉換";
Blockly.Msg["CATLISTS"] = "列表";
Blockly.Msg["CATCOLOUR"] = "顏色";
Blockly.Msg["CATINITIALIZES"] = "程式流程";

Blockly.Msg["MATH_HUE"] = "230";
Blockly.Msg["LOOPS_HUE"] = "120";
Blockly.Msg["LISTS_HUE"] = "20";
Blockly.Msg["LOGIC_HUE"] = "210";
Blockly.Msg["VARIABLES_HUE"] = "330";
Blockly.Msg["TEXTS_HUE"] = "160";
Blockly.Msg["PROCEDURES_HUE"] = "290";
Blockly.Msg["COLOUR_HUE"] = "20";
Blockly.Msg["VARIABLES_DYNAMIC_HUE"] = "310";
Blockly.Msg["TRANSFORM_HUE"] = "250";
Blockly.Msg["CATINITIALIZES_HUE"] = "50";

Blockly.Msg["ADD_COMMENT"] = "加入註解";
Blockly.Msg["CANNOT_DELETE_VARIABLE_PROCEDURE"] = "無法刪除變數「%1」，因為這是功能「%2」定義的一部份內容";
Blockly.Msg["CHANGE_VALUE_TITLE"] = "修改值：";
Blockly.Msg["CLEAN_UP"] = "整理積木";
Blockly.Msg["COLLAPSE_ALL"] = "收合積木";
Blockly.Msg["COLLAPSE_BLOCK"] = "收合區塊";
Blockly.Msg["COLOUR_BLEND_COLOUR1"] = "顏色 1";
Blockly.Msg["COLOUR_BLEND_COLOUR2"] = "顏色 2";
Blockly.Msg["COLOUR_BLEND_HELPURL"] = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
Blockly.Msg["COLOUR_BLEND_RATIO"] = "比例";
Blockly.Msg["COLOUR_BLEND_TITLE"] = "混合";
Blockly.Msg["COLOUR_BLEND_TOOLTIP"] = "用一個給定的比率（0.0-1.0）混合兩種顏色。";
Blockly.Msg["COLOUR_PICKER_HELPURL"] = "https://zh.wikipedia.org/wiki/顏色";
Blockly.Msg["COLOUR_PICKER_TOOLTIP"] = "從調色板中選擇一種顏色。";
Blockly.Msg["COLOUR_RANDOM_HELPURL"] = "http://randomcolour.com";  // untranslated
Blockly.Msg["COLOUR_RANDOM_TITLE"] = "隨機顏色";
Blockly.Msg["COLOUR_RANDOM_TOOLTIP"] = "隨機選擇一種顏色。";
Blockly.Msg["COLOUR_RGB_BLUE"] = "藍";
Blockly.Msg["COLOUR_RGB_GREEN"] = "綠";
Blockly.Msg["COLOUR_RGB_HELPURL"] = "http://www.december.com/html/spec/colorper.html";  // untranslated
Blockly.Msg["COLOUR_RGB_RED"] = "紅";
Blockly.Msg["COLOUR_RGB_TITLE"] = "顏色";
Blockly.Msg["COLOUR_RGB_TOOLTIP"] = "透過指定紅、綠、 藍色的值來建立一種顏色。所有的值必須介於 0 和 100 之間。";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK"] = "中斷循環";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE"] = "繼續下一個循環";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK"] = "中斷當前的循環。";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE"] = "跳過這個循環的其餘步驟，並繼續下一次的循環。";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_WARNING"] = "警告：此區塊僅可用於迴圈內。";
Blockly.Msg["CONTROLS_FOREACH_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
Blockly.Msg["CONTROLS_FOREACH_TITLE"] = "取出每個 %1 自清單 %2";
Blockly.Msg["CONTROLS_FOREACH_TOOLTIP"] = "遍歷每個清單中的項目，將變數「%1」設定到該項目中，然後執行某些陳述式。";
Blockly.Msg["CONTROLS_FOR_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg["CONTROLS_FOR_TITLE"] = "循環計數 %1 從 %2 到 %3 間隔數 %4";
Blockly.Msg["CONTROLS_FOR_TOOLTIP"] = "從起始數到結尾數中取出變數「%1」的值，按指定的時間間隔，執行指定的區塊。";
Blockly.Msg["CONTROLS_IF_ELSEIF_TOOLTIP"] = "添加條件到「如果」積木。";
Blockly.Msg["CONTROLS_IF_ELSE_TOOLTIP"] = "加入一個最終、所有條件都執行的部份到「如果」區塊中。";
Blockly.Msg["CONTROLS_IF_HELPURL"] = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg["CONTROLS_IF_IF_TOOLTIP"] = "添加、刪除或重新排列各部份以重新配置這個「如果」區塊。";
Blockly.Msg["CONTROLS_IF_MSG_ELSE"] = "否則";
Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"] = "否則如果";
Blockly.Msg["CONTROLS_IF_MSG_IF"] = "如果";
Blockly.Msg["CONTROLS_IF_TOOLTIP_1"] = "當值為 true 時，執行一些陳述式。";
Blockly.Msg["CONTROLS_IF_TOOLTIP_2"] = "當值為 true 時，執行第一個陳述式。否則，執行第二個陳述式。";
Blockly.Msg["CONTROLS_IF_TOOLTIP_3"] = "如果第一個值為 true，則執行第一個陳述式。否則，當第二個值為 true 時，則執行第二個陳述式。";
Blockly.Msg["CONTROLS_IF_TOOLTIP_4"] = "如果第一個值為 true，則執行第一個陳述式。否則當第二個值為 true 時，則執行第二個陳述式。如果前幾個敘述都不為 ture，則執行最後一個陳述式。";
Blockly.Msg["CONTROLS_REPEAT_HELPURL"] = "https://zh.wikipedia.org/wiki/For迴圈";
Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"] = "執行";
Blockly.Msg["CONTROLS_REPEAT_TITLE"] = "重複%1次";
Blockly.Msg["CONTROLS_REPEAT_TOOLTIP"] = "重複執行指定的陳述式多次。";
Blockly.Msg["CONTROLS_WHILEUNTIL_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_UNTIL"] = "重複直到";
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_WHILE"] = "重複 當";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL"] = "當值為 false 時，執行一些陳述式。";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_WHILE"] = "當值為 true 時，執行一些陳述式。";
Blockly.Msg["DELETE_ALL_BLOCKS"] = "刪除全部 %1 個區塊？";
Blockly.Msg["DELETE_BLOCK"] = "刪除區塊";
Blockly.Msg["DELETE_VARIABLE"] = "刪除變數「%1」";
Blockly.Msg["DELETE_VARIABLE_CONFIRMATION"] = "刪除%1使用的「%2」變數？";
Blockly.Msg["DELETE_X_BLOCKS"] = "刪除%1個積木";
Blockly.Msg["DISABLE_BLOCK"] = "停用區塊";
Blockly.Msg["DUPLICATE_BLOCK"] = "複製";
Blockly.Msg["DUPLICATE_COMMENT"] = "重複註解";
Blockly.Msg["ENABLE_BLOCK"] = "啟用積木";
Blockly.Msg["EXPAND_ALL"] = "展開積木";
Blockly.Msg["EXPAND_BLOCK"] = "展開區塊";
Blockly.Msg["EXTERNAL_INPUTS"] = "外部輸入";
Blockly.Msg["HELP"] = "說明";
Blockly.Msg["INLINE_INPUTS"] = "單行輸入";
Blockly.Msg["IOS_CANCEL"] = "取消";
Blockly.Msg["IOS_ERROR"] = "錯誤";
Blockly.Msg["IOS_OK"] = "確定";
Blockly.Msg["IOS_PROCEDURES_ADD_INPUT"] = "+ 添加輸入";
Blockly.Msg["IOS_PROCEDURES_ALLOW_STATEMENTS"] = "允許聲明";
Blockly.Msg["IOS_PROCEDURES_DUPLICATE_INPUTS_ERROR"] = "此功能有重複輸入內容。";
Blockly.Msg["IOS_PROCEDURES_INPUTS"] = "輸入";
Blockly.Msg["IOS_VARIABLES_ADD_BUTTON"] = "添加";
Blockly.Msg["IOS_VARIABLES_ADD_VARIABLE"] = "+ 添加變數";
Blockly.Msg["IOS_VARIABLES_DELETE_BUTTON"] = "刪除";
Blockly.Msg["IOS_VARIABLES_EMPTY_NAME_ERROR"] = "您不能使用不帶名的變數名稱。";
Blockly.Msg["IOS_VARIABLES_RENAME_BUTTON"] = "重新命名";
Blockly.Msg["IOS_VARIABLES_VARIABLE_NAME"] = "變數名稱";
Blockly.Msg["LISTS_CREATE_EMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
Blockly.Msg["LISTS_CREATE_EMPTY_TITLE"] = "建立空的清單";
Blockly.Msg["LISTS_CREATE_EMPTY_TOOLTIP"] = "返回一個長度（項目數量）為 0 的清單，不包含任何資料記錄";
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TITLE_ADD"] = "清單";
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TOOLTIP"] = "添加、刪除或重新排列各部份以重新配置這個清單區塊。";
Blockly.Msg["LISTS_CREATE_WITH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg["LISTS_CREATE_WITH_INPUT_WITH"] = "建立值的清單";
Blockly.Msg["LISTS_CREATE_WITH_INPUT_WITH_PROCEDURE"] = "宣告參數";
Blockly.Msg["LISTS_CREATE_WITH_INPUT_WITH_PROCEDURE_VALUE"] = "參數值";
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TOOLTIP"] = "添加一個項目到清單裡。";
Blockly.Msg["LISTS_CREATE_WITH_TOOLTIP"] = "建立一個具備任意數量項目的清單。";
Blockly.Msg["LISTS_GET_INDEX_FIRST"] = "第一筆";
Blockly.Msg["LISTS_GET_INDEX_FROM_END"] = "倒數第 # 筆";
Blockly.Msg["LISTS_GET_INDEX_FROM_START"] = "#";  // untranslated
Blockly.Msg["LISTS_GET_INDEX_GET"] = "取得";
Blockly.Msg["LISTS_GET_INDEX_GET_REMOVE"] = "取得並移除";
Blockly.Msg["LISTS_GET_INDEX_LAST"] = "最後一筆";
Blockly.Msg["LISTS_GET_INDEX_RANDOM"] = "隨機";
Blockly.Msg["LISTS_GET_INDEX_REMOVE"] = "移除";
Blockly.Msg["LISTS_GET_INDEX_TAIL"] = "";  // untranslated
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_FIRST"] = "返回清單中的第一個項目。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_FROM"] = "返回在清單中指定位置的項目。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_LAST"] = "返回清單中的最後一個項目。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_RANDOM"] = "返回清單中隨機一個項目。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST"] = "移除並返回清單中的第一個項目。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM"] = "移除並返回清單中的指定位置的項目。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST"] = "移除並返回清單中的最後一個項目。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM"] = "移除並返回清單中的隨機項目。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST"] = "移除清單中的第一個項目。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM"] = "移除在清單中指定位置的項目。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST"] = "移除清單中的最後一個項目。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM"] = "移除清單中隨機一個項目。";
Blockly.Msg["LISTS_GET_SUBLIST_END_FROM_END"] = "到 # 倒數";
Blockly.Msg["LISTS_GET_SUBLIST_END_FROM_START"] = "到 #";
Blockly.Msg["LISTS_GET_SUBLIST_END_LAST"] = "到 最後面";
Blockly.Msg["LISTS_GET_SUBLIST_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
Blockly.Msg["LISTS_GET_SUBLIST_START_FIRST"] = "取得子清單 從 最前面";
Blockly.Msg["LISTS_GET_SUBLIST_START_FROM_END"] = "取得子清單 從 # 倒數";
Blockly.Msg["LISTS_GET_SUBLIST_START_FROM_START"] = "取得子清單 從 #";
Blockly.Msg["LISTS_GET_SUBLIST_TAIL"] = "";  // untranslated
Blockly.Msg["LISTS_GET_SUBLIST_TOOLTIP"] = "複製清單中指定的部分。";
Blockly.Msg["LISTS_INDEX_FROM_END_TOOLTIP"] = "%1 是最後一個項目。";
Blockly.Msg["LISTS_INDEX_FROM_START_TOOLTIP"] = "%1 是第一個項目。";
Blockly.Msg["LISTS_INDEX_OF_FIRST"] = "從 最前面 索引項目";
Blockly.Msg["LISTS_INDEX_OF_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
Blockly.Msg["LISTS_INDEX_OF_LAST"] = "從 最後面 索引項目";
Blockly.Msg["LISTS_INDEX_OF_TOOLTIP"] = "在清單中檢索是否有包含項目，如果有，返回從頭/倒數算起的索引值。如果沒有則返回 %1。";
Blockly.Msg["LISTS_INLIST"] = "自清單";
Blockly.Msg["LISTS_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
Blockly.Msg["LISTS_ISEMPTY_TITLE"] = "陣列 %1 值為空";
Blockly.Msg["LISTS_ISEMPTY_TOOLTIP"] = "如果該清單為空，則返回 true。";
Blockly.Msg["LISTS_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg["LISTS_LENGTH_TITLE"] = "陣列長度 %1";
Blockly.Msg["LISTS_LENGTH_TOOLTIP"] = "返回清單的長度（項目數）。";
Blockly.Msg["LISTS_REPEAT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg["LISTS_REPEAT_TITLE"] = "建立清單使用項目 %1 重複 %2 次";
Blockly.Msg["LISTS_REPEAT_TOOLTIP"] = "建立一個清單，項目中包含指定重複次數的值。";
Blockly.Msg["LISTS_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#reversing-a-list";
Blockly.Msg["LISTS_REVERSE_MESSAGE0"] = "反轉%1";
Blockly.Msg["LISTS_REVERSE_TOOLTIP"] = "反轉清單的複製內容。";
Blockly.Msg["LISTS_SET_INDEX_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg["LISTS_SET_INDEX_INPUT_TO"] = "為";
Blockly.Msg["LISTS_SET_INDEX_INSERT"] = "添加";
Blockly.Msg["LISTS_SET_INDEX_SET"] = "設定";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST"] = "添加一個項目到清單中的第一個位置。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_FROM"] = "添加一個項目到清單中的指定位置。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_LAST"] = "添加一個項目到清單中的最後一個位置。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM"] = "添加一個項目到清單中的隨機位置。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_FIRST"] = "設定清單中的第一個項目。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_FROM"] = "設定清單中指定位置的項目。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_LAST"] = "設定清單中的最後一個項目。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_RANDOM"] = "設定清單中隨機一個項目。";
Blockly.Msg["LISTS_SORT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
Blockly.Msg["LISTS_SORT_ORDER_ASCENDING"] = "升序";
Blockly.Msg["LISTS_SORT_ORDER_DESCENDING"] = "降序";
Blockly.Msg["LISTS_SORT_TITLE"] = "排列 %1 %2 %3";
Blockly.Msg["LISTS_SORT_TOOLTIP"] = "排序清單的複製內容。";
Blockly.Msg["LISTS_SORT_TYPE_IGNORECASE"] = "依字母排序，忽略大小寫";
Blockly.Msg["LISTS_SORT_TYPE_NUMERIC"] = "依數字";
Blockly.Msg["LISTS_SORT_TYPE_TEXT"] = "依字母";
Blockly.Msg["LISTS_SPLIT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";  // untranslated
Blockly.Msg["LISTS_SPLIT_LIST_FROM_TEXT"] = "從文本製作清單";
Blockly.Msg["LISTS_SPLIT_TEXT_FROM_LIST"] = "從清單拆出文本";
Blockly.Msg["LISTS_SPLIT_TOOLTIP_JOIN"] = "串起清單項目成一個文本，並用分隔符號分開。";
Blockly.Msg["LISTS_SPLIT_TOOLTIP_SPLIT"] = "將文本變成清單項目，按分隔符號拆分。";
Blockly.Msg["LISTS_SPLIT_WITH_DELIMITER"] = "用分隔符";
Blockly.Msg["LOGIC_BOOLEAN_FALSE"] = "假";
Blockly.Msg["LOGIC_BOOLEAN_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg["LOGIC_BOOLEAN_TOOLTIP"] = "返回真或假。";
Blockly.Msg["LOGIC_BOOLEAN_TRUE"] = "真";
Blockly.Msg["LOGIC_COMPARE_HELPURL"] = "https://zh.wikipedia.org/wiki/不等";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_EQ"] = "如果這兩個輸入區塊的結果相等，返回 true。";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GT"] = "如果第一個輸入結果大於第二個，返回 true。";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GTE"] = "如果第一個輸入結果大於或等於第二個，返回 true。";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LT"] = "如果第一個輸入結果比第二個小，返回 true。";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LTE"] = "如果第一個輸入結果小於或等於第二個，返回 true。";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_NEQ"] = "如果這兩個輸入區塊的結果不相等，返回 true。";
Blockly.Msg["LOGIC_NEGATE_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
Blockly.Msg["LOGIC_NEGATE_TITLE"] = "%1 不成立";
Blockly.Msg["LOGIC_NEGATE_TOOLTIP"] = "如果輸入結果是 false，則返回 true。如果輸入結果是 true，則返回 false。";
Blockly.Msg["LOGIC_NULL"] = "空";
Blockly.Msg["LOGIC_NULL_HELPURL"] = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
Blockly.Msg["LOGIC_NULL_TOOLTIP"] = "返回空值。";
Blockly.Msg["LOGIC_OPERATION_AND"] = "且";
Blockly.Msg["LOGIC_OPERATION_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg["LOGIC_OPERATION_OR"] = "或";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_AND"] = "如果兩個輸入結果都為 true，則返回 true。";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_OR"] = "如果至少一個輸入結果為 true，返回 true。";
Blockly.Msg["LOGIC_TERNARY_CONDITION"] = "測試";
Blockly.Msg["LOGIC_TERNARY_HELPURL"] = "https://zh.wikipedia.org/wiki/條件運算符";
Blockly.Msg["LOGIC_TERNARY_IF_FALSE"] = "如果為假";
Blockly.Msg["LOGIC_TERNARY_IF_TRUE"] = "如果為真";
Blockly.Msg["LOGIC_TERNARY_TOOLTIP"] = "檢查「測試」中的條件。如果條件為真，將返回「如果為真」的值；否則，返回「如果為假」的值。";
Blockly.Msg["MATH_ADDITION_SYMBOL"] = "+";  // untranslated
Blockly.Msg["MATH_ARITHMETIC_HELPURL"] = "https://zh.wikipedia.org/wiki/算術";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_ADD"] = "返回兩個數字的總和。";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_DIVIDE"] = "返回兩個數字的商。";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MINUS"] = "返回兩個數字的差。";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MULTIPLY"] = "返回兩個數字的乘積。";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_POWER"] = "返回第二個數字的指數的第一個數字。";
Blockly.Msg["MATH_ATAN2_HELPURL"] = "https://zh.wikipedia.org/wiki/Atan2";
Blockly.Msg["MATH_ATAN2_TITLE"] = "X:%1 Y:%2 的 Atan2";
Blockly.Msg["MATH_ATAN2_TOOLTIP"] = "回傳點（X，Y）從 -180 至 180 度的反正切值。";
Blockly.Msg["MATH_CHANGE_HELPURL"] = "https://zh.wikipedia.org/wiki/加法";
Blockly.Msg["MATH_CHANGE_TITLE"] = "修改 %1 自 %2";
Blockly.Msg["MATH_CHANGE_TOOLTIP"] = "將數字加到變數「%1」。";
Blockly.Msg["MATH_CONSTANT_HELPURL"] = "https://zh.wikipedia.org/wiki/數學常數";
Blockly.Msg["MATH_CONSTANT_TOOLTIP"] = "返回一個的常見常量： π (3.141......)，e (2.718...)、 φ (1.618...)、 開方(2) (1.414......)、 開方(½) (0.707......) 或 ∞ （無窮大）。";
Blockly.Msg["MATH_CONSTRAIN_HELPURL"] = "https://en.wikipedia.org/wiki/Clamping_(graphics)";  // untranslated
Blockly.Msg["MATH_CONSTRAIN_TITLE"] = "限制數字 %1 介於（低）%2 到（高）%3";
Blockly.Msg["MATH_CONSTRAIN_TOOLTIP"] = "限制數字介於兩個指定的數字之間（包含）。";
Blockly.Msg["MATH_DIVISION_SYMBOL"] = "÷";  // untranslated
Blockly.Msg["MATH_IS_DIVISIBLE_BY"] = "可被整除";
Blockly.Msg["MATH_IS_EVEN"] = "是偶數";
Blockly.Msg["MATH_IS_NEGATIVE"] = "是負值";
Blockly.Msg["MATH_IS_ODD"] = "是奇數";
Blockly.Msg["MATH_IS_POSITIVE"] = "是正值";
Blockly.Msg["MATH_IS_PRIME"] = "是質數";
Blockly.Msg["MATH_IS_TOOLTIP"] = "如果數字是偶數，奇數，非負整數，正數、 負數，或如果它是可被某數字整除，則返回 true 或 false。";
Blockly.Msg["MATH_IS_WHOLE"] = "是非負整數";
Blockly.Msg["MATH_MODULO_HELPURL"] = "https://zh.wikipedia.org/wiki/模除";
Blockly.Msg["MATH_MODULO_TITLE"] = "%1 除以 %2 的餘數";
Blockly.Msg["MATH_MODULO_TOOLTIP"] = "回傳兩個數字相除的餘數。";
Blockly.Msg["MATH_MULTIPLICATION_SYMBOL"] = "×";  // untranslated
Blockly.Msg["MATH_NUMBER_HELPURL"] = "https://zh.wikipedia.org/wiki/數";
Blockly.Msg["MATH_NUMBER_TOOLTIP"] = "一個數字。";
Blockly.Msg["MATH_ONLIST_HELPURL"] = "";  // untranslated
Blockly.Msg["MATH_ONLIST_OPERATOR_AVERAGE"] = "平均數 自清單";
Blockly.Msg["MATH_ONLIST_OPERATOR_MAX"] = "最大值 自清單";
Blockly.Msg["MATH_ONLIST_OPERATOR_MEDIAN"] = "中位數 自清單";
Blockly.Msg["MATH_ONLIST_OPERATOR_MIN"] = "最小值 自清單";
Blockly.Msg["MATH_ONLIST_OPERATOR_MODE"] = "比較眾數 自清單";
Blockly.Msg["MATH_ONLIST_OPERATOR_RANDOM"] = "隨機抽取 自清單";
Blockly.Msg["MATH_ONLIST_OPERATOR_STD_DEV"] = "標準差 自清單";
Blockly.Msg["MATH_ONLIST_OPERATOR_SUM"] = "數字總和 自清單";
Blockly.Msg["MATH_ONLIST_TOOLTIP_AVERAGE"] = "返回清單中數值的平均值（算術平均值）。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MAX"] = "返回清單項目中最大的數字。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MEDIAN"] = "返回清單中數值的中位數。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MIN"] = "返回清單項目中最小的數字。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MODE"] = "返回一個清單中的最常見的項目。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_RANDOM"] = "從清單中返回一個隨機的項目。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_STD_DEV"] = "返回清單中數字的標準差。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_SUM"] = "返回清單中的所有數字的總和。";
Blockly.Msg["MATH_POWER_SYMBOL"] = "^";  // untranslated
Blockly.Msg["MATH_RANDOM_FLOAT_HELPURL"] = "https://zh.wikipedia.org/wiki/隨機數生成器";
Blockly.Msg["MATH_RANDOM_FLOAT_TITLE_RANDOM"] = "隨機取分數";
Blockly.Msg["MATH_RANDOM_FLOAT_TOOLTIP"] = "在 0.0（包含）和 1.0（不包含）之間隨機取一個數。";
Blockly.Msg["MATH_RANDOM_INT_HELPURL"] = "https://zh.wikipedia.org/wiki/隨機數生成器";
Blockly.Msg["MATH_RANDOM_INT_TITLE"] = "隨機取數 %1 到 %2";
Blockly.Msg["MATH_RANDOM_INT_TOOLTIP"] = "在指定二個數之間隨機取一個數（包含）。";
Blockly.Msg["MATH_ROUND_HELPURL"] = "https://zh.wikipedia.org/wiki/數值簡化";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUND"] = "四捨五入";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDDOWN"] = "無條件捨去";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDUP"] = "無條件進位";
Blockly.Msg["MATH_ROUND_TOOLTIP"] = "將數字無條件進位或無條件捨去。";
Blockly.Msg["MATH_SINGLE_HELPURL"] = "https://zh.wikipedia.org/wiki/平方根";
Blockly.Msg["MATH_SINGLE_OP_ABSOLUTE"] = "絕對值";
Blockly.Msg["MATH_SINGLE_OP_ROOT"] = "開根號";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ABS"] = "返回指定數字的絕對值。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_EXP"] = "返回指定數字指數的 e";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LN"] = "返回指定數字的自然對數。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LOG10"] = "返回指定數字的對數。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_NEG"] = "返回指定數字的 negation。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_POW10"] = "返回指定數字指數的10的冪次。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ROOT"] = "返回指定數字的平方根。";
Blockly.Msg["MATH_SUBTRACTION_SYMBOL"] = "-";  // untranslated
Blockly.Msg["MATH_TRIG_ACOS"] = "acos";  // untranslated
Blockly.Msg["MATH_TRIG_ASIN"] = "asin";  // untranslated
Blockly.Msg["MATH_TRIG_ATAN"] = "atan";  // untranslated
Blockly.Msg["MATH_TRIG_COS"] = "cos";  // untranslated
Blockly.Msg["MATH_TRIG_HELPURL"] = "https://zh.wikipedia.org/wiki/三角函數";
Blockly.Msg["MATH_TRIG_SIN"] = "sin";  // untranslated
Blockly.Msg["MATH_TRIG_TAN"] = "tan";  // untranslated
Blockly.Msg["MATH_TRIG_TOOLTIP_ACOS"] = "返回指定角度的反餘弦值(非弧度）。";
Blockly.Msg["MATH_TRIG_TOOLTIP_ASIN"] = "返回指定角度的反正弦值(非弧度）。";
Blockly.Msg["MATH_TRIG_TOOLTIP_ATAN"] = "返回指定角度的反正切值。";
Blockly.Msg["MATH_TRIG_TOOLTIP_COS"] = "返回指定角度的餘弦值(非弧度）。";
Blockly.Msg["MATH_TRIG_TOOLTIP_SIN"] = "返回指定角度的正弦值(非弧度）。";
Blockly.Msg["MATH_TRIG_TOOLTIP_TAN"] = "返回指定角度的正切值(非弧度）。";
Blockly.Msg["NEW_COLOUR_VARIABLE"] = "建立顏色變數...";
Blockly.Msg["NEW_NUMBER_VARIABLE"] = "建立數字變數...";
Blockly.Msg["NEW_STRING_VARIABLE"] = "建立字串變數...";
Blockly.Msg["NEW_VARIABLE"] = "建立變數…";
Blockly.Msg["NEW_VARIABLE_TITLE"] = "新變數名稱：";
Blockly.Msg["NEW_VARIABLE_TYPE_TITLE"] = "新變數類型：";
Blockly.Msg["ORDINAL_NUMBER_SUFFIX"] = "";  // untranslated
Blockly.Msg["PROCEDURES_ALLOW_STATEMENTS"] = "允許陳述式";
Blockly.Msg["PROCEDURES_BEFORE_PARAMS"] = "與：";
Blockly.Msg["PROCEDURES_CALLNORETURN_HELPURL"] = "https://zh.wikipedia.org/wiki/子程式";
Blockly.Msg["PROCEDURES_CALLNORETURN_TOOLTIP"] = "執行使用者定義的函式「%1」。";
Blockly.Msg["PROCEDURES_CALLRETURN_HELPURL"] = "https://zh.wikipedia.org/wiki/%E5%AD%90%E7%A8%8B%E5%BA%8F";
Blockly.Msg["PROCEDURES_CALLRETURN_TOOLTIP"] = "執行使用者定義的函式「%1」，並使用它的回傳值。";
Blockly.Msg["PROCEDURES_CALL_BEFORE_PARAMS"] = "與：";
Blockly.Msg["PROCEDURES_CREATE_DO"] = "建立「%1」";
Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"] = "描述此函式...";
Blockly.Msg["PROCEDURES_DEFNORETURN_DO"] = "";  // untranslated
Blockly.Msg["PROCEDURES_DEFNORETURN_HELPURL"] = "https://zh.wikipedia.org/wiki/子程式";
Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"] = "func";
Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"] = "函數";
Blockly.Msg["PROCEDURES_DEFNORETURN_TOOLTIP"] = "創建一個無回傳值的函式。";
Blockly.Msg["PROCEDURES_DEFRETURN_HELPURL"] = "https://zh.wikipedia.org/wiki/子程式";
Blockly.Msg["PROCEDURES_DEFRETURN_RETURN"] = "返回";
Blockly.Msg["PROCEDURES_DEFRETURN_TOOLTIP"] = "創建一個有回傳值的的函式。";
Blockly.Msg["PROCEDURES_DEF_DUPLICATE_WARNING"] = "警告: 此函式中有重複的參數。";
Blockly.Msg["PROCEDURES_HIGHLIGHT_DEF"] = "反白顯示函式定義";
Blockly.Msg["PROCEDURES_IFRETURN_HELPURL"] = "http://c2.com/cgi/wiki?GuardClause";  // untranslated
Blockly.Msg["PROCEDURES_IFRETURN_TOOLTIP"] = "如果值為 true，則返回第二個值。";
Blockly.Msg["PROCEDURES_IFRETURN_WARNING"] = "警告：這個區塊只可以在定義函式時使用。";
Blockly.Msg["PROCEDURES_MUTATORARG_TITLE"] = "輸入名稱：";
Blockly.Msg["PROCEDURES_MUTATORARG_TOOLTIP"] = "添加一個輸入區塊到函式。";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TITLE"] = "輸入";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TOOLTIP"] = "添加、刪除或重新排列此函式的輸入。";
Blockly.Msg["REDO"] = "重做";
Blockly.Msg["REMOVE_COMMENT"] = "移除註解";
Blockly.Msg["RENAME_VARIABLE"] = "重新命名變數...";
Blockly.Msg["RENAME_VARIABLE_TITLE"] = "將所有「%1」變數重新命名為：";
Blockly.Msg["TEXT_APPEND_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg["TEXT_APPEND_TITLE"] = "在字串 %1 後串接字串 %2";
Blockly.Msg["TEXT_APPEND_TOOLTIP"] = "添加一些字串到變數「%1」之後。";
Blockly.Msg["TEXT_CHANGECASE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_LOWERCASE"] = "轉成 英文小寫";
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_TITLECASE"] = "轉成 英文首字大寫";
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_UPPERCASE"] = "轉成 英文大寫";
Blockly.Msg["TEXT_CHANGECASE_TOOLTIP"] = "使用不同的大小寫複製這段字串。";
Blockly.Msg["TEXT_CHARAT_FIRST"] = "取得 第一個字元";
Blockly.Msg["TEXT_CHARAT_FROM_END"] = "取得 倒數第 # 個字元";
Blockly.Msg["TEXT_CHARAT_FROM_START"] = "取得 字元 #";
Blockly.Msg["TEXT_CHARAT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg["TEXT_CHARAT_LAST"] = "取得 最後一個字元";
Blockly.Msg["TEXT_CHARAT_RANDOM"] = "取得 任意字元";
Blockly.Msg["TEXT_CHARAT_TAIL"] = "";  // untranslated
Blockly.Msg["TEXT_CHARAT_TITLE"] = "在字串 %1 %2";
Blockly.Msg["TEXT_CHARAT_TOOLTIP"] = "返回位於指定位置的字元。";
Blockly.Msg["TEXT_COUNT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#counting-substrings";
Blockly.Msg["TEXT_COUNT_MESSAGE0"] = "在%2計算%1";
Blockly.Msg["TEXT_COUNT_TOOLTIP"] = "計算某些字串在內容裡的出現次數。";
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TOOLTIP"] = "添加一個項目到字串中。";
Blockly.Msg["TEXT_CREATE_JOIN_TITLE_JOIN"] = "加入";
Blockly.Msg["TEXT_CREATE_JOIN_TOOLTIP"] = "添加、刪除或重新排列各部份以重新配置這個字串區塊。";
Blockly.Msg["TEXT_GET_SUBSTRING_END_FROM_END"] = "到 倒數第 # 個字元";
Blockly.Msg["TEXT_GET_SUBSTRING_END_FROM_START"] = "到 字元 #";
Blockly.Msg["TEXT_GET_SUBSTRING_END_LAST"] = "到 最後一個字元";
Blockly.Msg["TEXT_GET_SUBSTRING_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg["TEXT_GET_SUBSTRING_INPUT_IN_TEXT"] = "在字串";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FIRST"] = "取得 第一個字元";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FROM_END"] = "取得 倒數第 # 個字元";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FROM_START"] = "取得 字元 #";
Blockly.Msg["TEXT_GET_SUBSTRING_TAIL"] = "";  // untranslated
Blockly.Msg["TEXT_GET_SUBSTRING_TOOLTIP"] = "返回指定的部分字串。";
Blockly.Msg["TEXT_INDEXOF_HELPURL"] = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg["TEXT_INDEXOF_OPERATOR_FIRST"] = "從 最前面 索引字串";
Blockly.Msg["TEXT_INDEXOF_OPERATOR_LAST"] = "從 最後面 索引字串";
Blockly.Msg["TEXT_INDEXOF_TITLE"] = "在字串 %1 %2 %3";
Blockly.Msg["TEXT_INDEXOF_TOOLTIP"] = "在字串1中檢索是否有包含字串2，如果有，返回從頭/倒數算起的索引值。如果沒有則返回 %1。";
Blockly.Msg["TEXT_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg["TEXT_ISEMPTY_TITLE"] = "%1 為空";
Blockly.Msg["TEXT_ISEMPTY_TOOLTIP"] = "如果提供的字串為空，則返回 true。";
Blockly.Msg["TEXT_WITH_HELPURL"] = "";  // untranslated
Blockly.Msg["TEXT_WITH_TITLE"] = "%1 從 最前面 %2";
Blockly.Msg["TEXT_WITH_TOOLTIP"] = "如果提供的字串為空，則返回 true。";
Blockly.Msg["TEXT_WITH_OPERATOR_FIRST"] = "從 最前面 比對字串";
Blockly.Msg["TEXT_WITH_OPERATOR_LAST"] = "從 最後面 比對字串";
Blockly.Msg["TEXT_JOIN_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg["TEXT_JOIN_TITLE_CREATEWITH"] = "字串組合";
Blockly.Msg["TEXT_JOIN_TOOLTIP"] = "通過連接任意數量的項目來建立一串字串。";
Blockly.Msg["TEXT_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg["TEXT_LENGTH_TITLE"] = "字串長度 %1";
Blockly.Msg["TEXT_LENGTH_TOOLTIP"] = "返回這串字串的字元數（包含空格）。";
Blockly.Msg["TEXT_PRINT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg["TEXT_PRINT_TITLE"] = "輸出 %1";
Blockly.Msg["TEXT_PRINT_TOOLTIP"] = "輸出指定的字串、 數字或其他值。";
Blockly.Msg["TEXT_PROMPT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg["TEXT_PROMPT_TOOLTIP_NUMBER"] = "輸入數字";
Blockly.Msg["TEXT_PROMPT_TOOLTIP_TEXT"] = "輸入字串";
Blockly.Msg["TEXT_PROMPT_TYPE_NUMBER"] = "輸入 數字 並顯示提示訊息";
Blockly.Msg["TEXT_PROMPT_TYPE_TEXT"] = "輸入 字串 並顯示提示訊息";
Blockly.Msg["TEXT_REPLACE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#replacing-substrings";
Blockly.Msg["TEXT_REPLACE_MESSAGE0"] = "在%3以%2取代%1";
Blockly.Msg["TEXT_REPLACE_TOOLTIP"] = "取代在內容裡的全部某些字串。";
Blockly.Msg["TEXT_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#reversing-text";
Blockly.Msg["TEXT_REVERSE_MESSAGE0"] = "反轉%1";
Blockly.Msg["TEXT_REVERSE_TOOLTIP"] = "反轉排序在字串裡的字元。";
Blockly.Msg["TEXT_TEXT_HELPURL"] = "https://zh.wikipedia.org/wiki/字串";
Blockly.Msg["TEXT_TEXT_TOOLTIP"] = "一個字元、一個單詞，或一串字串。";
Blockly.Msg["TEXT_TRIM_HELPURL"] = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg["TEXT_TRIM_OPERATOR_BOTH"] = "消除兩側空格";
Blockly.Msg["TEXT_TRIM_OPERATOR_LEFT"] = "消除左側空格";
Blockly.Msg["TEXT_TRIM_OPERATOR_RIGHT"] = "消除右側空格";
Blockly.Msg["TEXT_TRIM_TOOLTIP"] = "複製這段字串，同時刪除兩端多餘的空格。";
Blockly.Msg["TODAY"] = "今天";
Blockly.Msg["UNDO"] = "還原";
Blockly.Msg["VARIABLES_DEFAULT_NAME"] = "項目";
Blockly.Msg["VARIABLES_GET_CREATE_SET"] = "建立「賦值 %1」";
Blockly.Msg["VARIABLES_GET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg["VARIABLES_GET_TOOLTIP"] = "返回此變數的值。";
Blockly.Msg["VARIABLES_SET"] = "賦值 %1 成 %2";
Blockly.Msg["VARIABLES_SET_CREATE_GET"] = "建立「取得 %1」";
Blockly.Msg["VARIABLES_SET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg["VARIABLES_SET_TOOLTIP"] = "設定此變數，好和輸入結果相等。";
Blockly.Msg["VARIABLE_ALREADY_EXISTS"] = "已存在變數「%1」。";
Blockly.Msg["VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE"] = "已存在名為「%1」且用於其它類型「%2」的變數。";
Blockly.Msg["WORKSPACE_COMMENT_DEFAULT_TEXT"] = "來說些事情...";
Blockly.Msg["CONTROLS_FOREACH_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_FOR_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_IF_ELSEIF_TITLE_ELSEIF"] = Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"];
Blockly.Msg["CONTROLS_IF_ELSE_TITLE_ELSE"] = Blockly.Msg["CONTROLS_IF_MSG_ELSE"];
Blockly.Msg["CONTROLS_IF_IF_TITLE_IF"] = Blockly.Msg["CONTROLS_IF_MSG_IF"];
Blockly.Msg["CONTROLS_IF_MSG_THEN"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_WHILEUNTIL_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TITLE"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["LISTS_GET_INDEX_HELPURL"] = Blockly.Msg["LISTS_INDEX_OF_HELPURL"];
Blockly.Msg["LISTS_GET_INDEX_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["LISTS_GET_SUBLIST_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["LISTS_INDEX_OF_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["LISTS_SET_INDEX_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["MATH_CHANGE_TITLE_ITEM"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["PROCEDURES_DEFRETURN_COMMENT"] = Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"];
Blockly.Msg["PROCEDURES_DEFRETURN_DO"] = Blockly.Msg["PROCEDURES_DEFNORETURN_DO"];
Blockly.Msg["PROCEDURES_DEFRETURN_PROCEDURE"] = Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"];
Blockly.Msg["PROCEDURES_DEFRETURN_TITLE"] = Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"];
Blockly.Msg["TEXT_APPEND_VARIABLE"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TITLE_ITEM"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];

Blockly.Msg.VARIABLES_CHANGETYPE_TOINT = "整數(int)";
Blockly.Msg.VARIABLES_CHANGETYPE_TODOUBLE = "倍精度浮點數(double)";
Blockly.Msg.VARIABLES_CHANGETYPE_TOFLOAT = "浮點數(float)";
Blockly.Msg.VARIABLES_CHANGETYPE_TOLOWERCASE = "小寫字串";
Blockly.Msg.VARIABLES_CHANGETYPE_TOUPPERCASE = "大寫字串";
Blockly.Msg.VARIABLES_CHANGETYPE_TRIM = "刪除兩側空格";
Blockly.Msg.VARIABLES_CHANGETYPE_CSTR = "NULL結尾字串(c_str)";
Blockly.Msg.VARIABLES_CHANGETYPE_LENGTH = "字串長度";

Blockly.Msg.VARIABLES_TYPE_POSITION_GLOBAL = "全域";
Blockly.Msg.VARIABLES_TYPE_POSITION_LOCAL = "區域";

Blockly.Msg.VARIABLES_GETNUMBER_RANDOM = "隨機";
Blockly.Msg.VARIABLES_GETNUMBER_RANDOMSEED = "隨機種子";

Blockly.Msg.MATH_RADIAN_TO_DEGREE_TITLE = "弧度";
Blockly.Msg.MATH_RADIAN_TO_DEGREE_APPEND = "轉換為角度";
Blockly.Msg.MATH_RADIAN_TO_DEGREE_TOOLTIP = "";

Blockly.Msg.LAUNCHSERIAL = "PuTTY序列埠監看視窗"
Blockly.Msg.DOWNLOAD = "下載積木圖片"
Blockly.Msg.PREVIOUSSTEP = "還原"
Blockly.Msg.NEXTSTEP = "重做"

Blockly.Msg.CATEGORY_TRANSFORM = "轉換";
Blockly.Msg.SCROLLPLUGIN = "切換邊緣捲動";
Blockly.Msg.SCROLLPLUGIN_TRUE = "啟用邊緣捲動";
Blockly.Msg.SCROLLPLUGIN_FALSE = "停用邊緣捲動";
Blockly.Msg.HIGHLIGHTPLUGIN = "啟用醒目範圍";
Blockly.Msg.BACKPACKPLUGIN = '啟用背包區域';
Blockly.Msg.DELETENULL = '清除%1個空子積木';
Blockly.Msg.SEARCHNULL = '尋找下個空子積木';

Blockly.Msg['COPY_ALL_TO_BACKPACK'] = '複製所有積木到背包';
Blockly.Msg['COPY_TO_BACKPACK'] = '複製到背包';
Blockly.Msg['EMPTY_BACKPACK'] = '清空背包';
Blockly.Msg['PASTE_ALL_FROM_BACKPACK'] = '從背包貼上所有積木';
Blockly.Msg['REMOVE_FROM_BACKPACK'] = '從背包移除所有積木';

Blockly.Msg["CONTROLS_SWITCH"] = "條件判斷";
Blockly.Msg["CONTROLS_SWITCH_VALUE"] = "比對值";
Blockly.Msg["CONTROLS_SWITCH_CASE"] = "條件";
Blockly.Msg["CONTROLS_SWITCH_DEFAULT"] = "預設";
Blockly.Msg["CONTROLS_SWITCH_TO"] = "陳述";
Blockly.Msg["CONTROLS_SWITCH_MSG"] = "符合";
Blockly.Msg["CONTROLS_SWITCH_MSG_CASE"] = "符合";
Blockly.Msg["CONTROLS_SWITCH_MSG_DEFAULT"] = "預設陳述";

Blockly.Msg.TOOLBOX_DISPLAY = "工具箱目錄";
Blockly.Msg.TOOLBOX_SHOW = "顯示工具箱";
Blockly.Msg.TOOLBOX_HIDE = "隱藏工具箱";
Blockly.Msg.LOADLASTBLOCKS = "還原備份積木";
Blockly.Msg.WINDOW_CLOSE_MESSAGE = "請確認已儲存積木檔後再離開？";

Blockly.Msg.VARIABLES_TO_STRING_BIN = "字串(二進制)";
Blockly.Msg.VARIABLES_TO_STRING_OCT = "字串(八進制)";
Blockly.Msg.VARIABLES_TO_STRING_DEC = "字串(十進制)";
Blockly.Msg.VARIABLES_TO_STRING_HEX = "字串(十六進制)";
Blockly.Msg.VARIABLES_TO_REPLACE = "取代";

Blockly.Msg.RELOAD_TITLE = "你要重啟視窗載入新設定嗎？";
Blockly.Msg.COM_TITLE = "請先選擇序列埠！";
Blockly.Msg.BUTTON_OPEN = "開啟";
Blockly.Msg.BUTTON_CLOSE = "關閉";
Blockly.Msg.BUTTON_SURE = "確認";
Blockly.Msg.BUTTON_RESET = "你確定要重設工作區？";
Blockly.Msg.BUTTON_SERIAL_OPEN = "開啟PUTTY";
Blockly.Msg.BUTTON_SERIAL_TITLE = "序列埠監看視窗";
Blockly.Msg.BUTTON_UPLOAD_TITLE = "燒錄韌體";
Blockly.Msg.BUTTON_UPLOAD_START = "正在上傳韌體...";
Blockly.Msg.BUTTON_UPLOAD_CODE = "程式碼";
Blockly.Msg.BUTTON_CLEARAREAS_TITLE = "你確定要清除自訂積木區內容？";