var MSG = {
  lang: "zh-hant",
  catLoadingBlocks: "載入積木",
  update: "update 2018.12.01",
  title: "Webduino Bit 教育版",
  documentTitle: "Webduino Blockly",
  editing: "",
  gotoTutorials: "教學範例",
  gotoWebSite: "官方網站",
  cleanUpBlocks: "整理積木",
  REDO: "下一步 ( Ctrl + Shift + Z )",
  UNDO: "上一步 ( Ctrl + Z )",
  CLEAN_UP: "整理積木",
  exportImage: "下載圖片",
  userMenuDashboard: "專案",
  userMenuTutorials: "教學",
  userMenuApiDocs: "API 文件",
  userMenuWebSite: "首頁",
  userMenuLogout: "登出",
  blocks: "積木",
  copyToClipboard: "複製到剪貼簿",
  changesSaved: " ( 已儲存變更 )",
  linkTooltip: "儲存並產生連結",
  qrcodeTooltip: "產生即時預覽 QR code",
  runTooltip: "執行程式",
  stopRunTooltip: "停止執行",
  badCode: "程式錯誤：\n%1",
  timeout: "超過最大執行數",
  trashTooltip: "刪除所有積木",
  sampleTooltip: "載入範例積木",
  simulatorTooltip: "模擬器區域",
  demoTooltip: "網頁互動區域",
  openJsbin: "打開程式編輯",
  checkDeviceOnline: "檢查裝置狀態",
  catLogic: "邏輯",
  catLoops: "重複",
  catMath: "數學",
  catText: "文字",
  catLists: "陣列",
  catColour: "顏色",
  catVariables: "變數",
  catFunctions: "函式",
  catExec: "等待",
  catRepeat: "狀態切換",
  catBoardGroup: "開發板控制",
  catBoard: "Webduino Bit",
  catPin: "I/O 腳位",
  catLed: "LED 燈",
  catRelay: "繼電器",
  catRGBLed: "三色 LED",
  catUltraSonic: "超音波",
  catSmartServo: "智慧伺服馬達",
  catG3: "細懸浮微粒",
  catButton: "按鈕開關",
  catShock: "震動開關",
  catPir: "人體紅外線",
  catSound: "聲音偵測",
  catServo: "伺服馬達",
  listVariable: "陣列",
  textVariable: "文字",
  httpRequestError: "命令出現錯誤。",
  shareLink: "分享連結",
  shareLinkTrial: "分享連結(有效日期: %1)",
  errorOccur: "發生錯誤",
  linkAlert: "透過此連結分享您的積木組：\n\n%1",
  hashError: "對不起，「%1」並未對應任何已保存的程式。",
  xmlError: "檔案已損毀或含有未知積木，故無法載入。",
  badXml: "解析 XML 時出現錯誤：\n%1\n\n選擇'確定'以放棄您的更改，或選擇'取消'以進一步編輯 XML。",
  catDataTransfer: "資料傳輸",
  catConsole: "控制",
  catDetect: "偵測",
  catMathOther: "數值轉換",
  catTextLogic: "文字邏輯",
  backIndex: "返回 Webduino 積木教學",
  demoTitle: "Blockly 範例測試區",
  catTutorials: "教學積木",
  linkToBin: "程式編輯",
  catDatabase: "資料庫",
  catFirebase: "Firebase",
  catGoogleSheets: "Google 試算表",
  catCarTest: "自走車",
  catBasic: "基本積木",
  catWebduino: "Webduino 積木",
  catMenu1: "發光元件",
  catMenu2: "輸入輸出",
  catMenu3: "環境偵測",
  catMenu4: "無線感應",
  catMenu5: "玩具及馬達",
  catSpeech: "語音聲控",
  catSpeak: "語音＆音效",
  catMobile: "行動裝置",
  catTracking: "影像辨識",
  catKeyCode: "鍵盤行為",
  catPlus: "進階",
  catStandard: "基本功能",
  catMax7219: "LED 點矩陣",
  catMP3: "MP3 播放器",
  catSSD1306: "OLED 螢幕",
  catSoil: "土壤濕度偵測",
  catIRRecv: "紅外線接收",
  catIRLed: "紅外線發射",
  catADXL345: "三軸加速度計",
  catHX711: "電子磅秤",
  catBarcode: "條碼機",
  catRFID: "RFID",
  catJoystick: "搖桿",
  catDemo: "網頁互動",
  catDemoText: "顯示文字",
  catDemoLight: "點擊燈泡",
  catDemoImage: "控制圖片",
  catDemoChart: "繪製圖表",
  catDemoArea: "顏色調整",
  catDemoButton: "按鈕行為",
  catDemoRange: "拉霸操作",
  catDemoYoutube: "YouTube",
  catDemoTracking: "影像追蹤",
  catDemoController: "遙控器",
  demoAreaTitle: "網頁互動區域",
  demoAreaChoose: "互動方式：",
  demoAreaSelect1: "顯示文字",
  demoAreaSelect2: "點擊燈泡",
  demoAreaSelect3: "控制圖片",
  demoAreaSelect4: "顏色調整",
  demoAreaSelect5: "按鈕行為",
  demoAreaSelect6: "拉霸操作",
  demoAreaSelect7: "Youtube",
  demoAreaSelect8: "影像追蹤",
  demoAreaSelect9: "遙控器",
  demoAreaSelect10: "繪製圖表",
  demoAreaColor: "選擇顏色：",
  demoAreaBtn1: "按鈕 1",
  demoAreaBtn2: "按鈕 2",
  demoAreaBtn3: "按鈕 3",
  demoAreaBtn4: "按鈕 4",
  demoAreaBtn5: "按鈕 5",
  demoAreaSlider: "拉霸：",
  demoAreaSliderValue: "數值：",
  demoAreaYoutube1: "YouTube 影片會顯示在上方",
  demoAreaYoutube2: "必須另外載入：",
  demoAreaRemoteDisplay: "顯示",
  samples1:"基礎操作",
  samples1_1:"LED",
  samples1_2:"全彩 LED",
  samples1_3:"蜂鳴器",
  samples1_4:"伺服馬達",
  samples1_5:"LED 點矩陣",
  samples2:"傳感器應用",
  samples2_1:"超音波偵測距離",
  samples2_2:"偵測環境溫濕度",
  samples2_3:"偵測聲音",
  samples2_4:"偵測人體紅外線",
  samples2_5:"偵測環境光線",
  samples2_6:"偵測土壤濕度",
  samples2_7:"偵測三軸加速度",
  samples2_8:"偵測 RFID 識別碼",
  samples3:"I/O 腳位",
  samples3_1:"操控兩顆 LED",
  samples3_2:"操控全彩 LED",
  samples4:"Youtube 應用",
  samples4_1:"RFID 切換影片",
  samples4_2:"按鈕開關控制播放",
  samples4_3:"超音波控制播放速度",
  samples5:"進階應用",
  samples5_1:"網頁虛擬遙控器",
  samples5_2:"聲控電燈",
  samples5_3:"人臉追蹤控制電燈",
  samples5_4:"倒車雷達",
  samples5_5:"自走車 ( 鍵盤 )",
  samples5_6:"自走車 ( 虛擬遙控器 )",
  samples5_7:"資料庫記錄溫濕度",
  samples5_8:"RFID 簡易門禁系統",
  samples5_9:"LED 點矩陣顯示濕度",
  samples5_10:"鬧鐘 ( 蜂鳴器 + 點矩陣 )",
  samples6:"開發板連動",
  samples6_1:"土壤濕度 + LED",
  samples6_2:"超音波 + LED 點矩陣",
  samplesBit1:"Webduino Bit 全彩點矩陣",
  samplesBit0:"Webduino Bit 小遊戲",
  samplesBit0_1:"貪吃蛇 ( 按鈕開關 )",
  samplesBit0_2:"走迷宮 ( 按鈕開關 + 鍵盤 )",
  samplesBit0_3:"反彈球 ( 按鈕開關 )",
  samplesBit0_4:"小瑪莉 ( 按鈕開關 )",
  samplesBit1_0:"即時繪製圖案",
  samplesBit1_1:"網頁按鈕控制燈號",
  samplesBit1_2:"鍵盤操控燈號移動",
  samplesBit1_3:"線段移動 ( 水平 + 色彩變換 )",
  samplesBit1_4:"同時顯示相同顏色",
  samplesBit1_5:"線段移動 ( 水平 + 反彈 )",
  samplesBit1_6:"燈號移動 ( 水平 )",
  samplesBit1_7:"列與欄操作 ( 燈號水平反彈 )",
  samplesBit1_8:"燈號移動 ( 垂直 )",
  samplesBit1_9:"列與欄操作 ( 一排燈號水平反彈 )",
  samplesBit1_10:"列與欄操作 ( 一排燈號垂直反彈 )",
  samplesBit1_11:"列與欄操作 ( 反彈球效果 )",
  samplesBit1_12:"鍵盤操控燈號移動 ( 碰撞偵測 )",
  samplesBit1_13:"二維陣列定義圖案",
  samplesBit1_14:"二維陣列定義圖案 ( 水平跑馬燈 )",
  samplesBit1_15:"二維陣列定義圖案 ( 垂直跑馬燈 )",
  samplesBit1_16:"燈號移動 ( 繞著周圍 )",
  samplesBit2:"Webduino Bit 元件模組",
  samplesBit2_1:"按鈕開關 ( 網頁顯示狀態 )",
  samplesBit2_2:"按鈕開關 ( 控制燈號 )",
  samplesBit2_3:"蜂鳴器 ( 網頁按鈕操控 )",
  samplesBit3:"Webduino Bit 傳感器",
  samplesBit3_1:"光敏電阻 ( 網頁顯示亮度 )",
  samplesBit3_2:"光敏電阻 ( 改變全彩點矩陣顏色 )",
  samplesBit3_3:"熱敏電阻 ( 網頁顯示溫度 )",
  samplesBit3_4:"熱敏電阻 ( 改變全彩點矩陣顏色 )",
  samplesBit3_5:"九軸偵測 ( 加速度 )",
  samplesBit3_6:"九軸偵測 ( 陀螺儀 )",
  samplesBit3_7:"九軸偵測 ( 姿態角度 )",
  tabEnableBlocks: "啟用及停用",
  tabExport: "匯出及匯入",
  tabCustom: "使用自有積木",
  enableBlocksTitle: "選擇啟用積木",
  customBlockRemove: "移除",
  customBlockAdd: "加入",
  customBlockInvalid: "載入的檔案有誤",
  customBlockNotFound: "找不到指定檔案，請確認連結是否正確",
  customBlockUnknownError: "載入檔案時發生未知錯誤，請確認連結是否正確",
  customBlockLinkInvalid: "輸入的連結有誤，請確認連結是否正確",
  customBlockMIMEInvalid: "無法使用檔案，請確定 MIME 類型是否正確",
  customBlockInUse: "積木使用中無法移除",
  customBlockImportSuccess: "匯入的積木已可使用",
  customBlockRemoveSuccess: "已移除指定積木",
  importTitle: "匯入",
  importButton: "匯入",
  chooseFileButton: "選擇檔案",
  importFromUrlButton: "由連結匯入...",
  importUrlText: "輸入由體驗版 Blockly 匯出的連結",
  importDescription: "匯入先前備份的專案",
  importWarning: "繼續匯入將會複寫目前的積木，確定要繼續嗎？",
  importInvalid: "匯入的檔案格式有誤",
  exportTitle: "匯出",
  exportDescription: "匯出目前專案的積木，並下載備份",
  exportButton: "匯出",
  customTitle: "使用自有積木",
  customButton: "匯入",
  customDescription: "請輸入自有積木定義檔 %1 連結，並注意下列事項",
  customNotice1: "確保連結有效，連結必須為安全連線 (HTTPS)",
  customNotice3: "檢查程式碼是否無誤",
  customeBlockAccessDenied: "無法移除共享專案的自訂積木，複製專案後才可進行編輯",
  codeJsChangeFileName: "變更檔名",
  updateChrome: "請更新 Chrome 版本，以獲得更好的使用體驗！",
  linkQrcode: "預覽畫面",
  useHttpForWebsocket: "使用 Websocket 連線，請使用非加密連線 (HTTP)",
  openLink: "開啟連結",
  otherFunctions: "其他功能",
  cancel: "取消",
  loginPlatform: "登入平台",
  loginToUseCustomBlock: "請先登入平台！",
  loadProjectFailed: "無法讀取存檔",
  loginToReadLink: "請登入平台，再重新開啟連結！",
  linkExpired: "連結失效",
  catBitLedMatrix: "矩陣 LED",
  catBitButton: "按鈕開關",
  catBitDetected: "偵測光線＆溫度",
  catBitBuzzer: "音樂＆聲音",
  catBitMpu9250: "體感偵測 ( 九軸 )",
  carBitDemoMonster: "怪獸控制"
};
