Blockly.Msg.AZUREFACE_PART_SHOW = "臉部偵測 (Azure) 部位";
Blockly.Msg.AZUREFACE_WIDTH_SHOW = "視訊 (Azure Face Detection) 寬度";
Blockly.Msg.AZUREFACE_HEIGHT_SHOW = "高度";
Blockly.Msg.AZUREFACE_DETECT_SHOW = "臉部偵測";
Blockly.Msg.AZUREFACE_GET_SHOW = "取得結果";
Blockly.Msg.AZUREFACE_OPACITY_SHOW = "透明度";
Blockly.Msg.AZUREFACE_SETTINGS_SHOW ="臉部偵測 (Azure) 設定";
Blockly.Msg.AZUREFACE_RESOURCENAME_SHOW ="Resource Name";
Blockly.Msg.AZUREFACE_KEY_SHOW = "Ocp-Apim-Subscription-Key";
