Blockly.Msg.OPEN_SHOW = "網頁顯示";
Blockly.Msg.CLOSE_SHOW = "關閉 網頁";
Blockly.Msg.OPENID_SHOW = "代碼";
Blockly.Msg.CLOSEID_SHOW = "代碼";
Blockly.Msg.URL_SHOW = "來源網址";
Blockly.Msg.WIDTH_SHOW = "寬度";
Blockly.Msg.HEIGHT_SHOW = "高度";
Blockly.Msg.LEFT_SHOW = "靠左距離";
Blockly.Msg.TOP_SHOW = "靠上距離";
