Blockly.Msg["CATGEMINI"] = "Gemini";
Blockly.Msg.GEMINI_TEXT_SHOW = "Gemini 文本生成";
Blockly.Msg.GEMINI_APIKEY_SHOW = "金钥";
Blockly.Msg.GEMINI_MODEL_SHOW = "模型";
Blockly.Msg.GEMINI_TEXT_RESPONSE_SHOW = "取得回应后";
Blockly.Msg.GEMINI_TEXT_RESPONSE_DATA_SHOW = "回应资料";
Blockly.Msg.GEMINI_TEXT_REQUEST_SHOW = "对话内容";
Blockly.Msg.GEMINI_TEXT_REQUEST_BR_SHOW = "换行处理";
Blockly.Msg.GEMINI_TEXT_RESPONSE_DATA_BR_SHOW = "自动换行";
