Blockly.Msg.TELEGRAM_MESSAGE_SHOW = "Telegram Message";
Blockly.Msg.TELEGRAM_PHOTO_SHOW = "Telegram Photo";
Blockly.Msg.TELEGRAM_IMAGE_SHOW = "Telegram Image";
Blockly.Msg.TELEGRAM_GETID_SHOW = "Get Element ID";
Blockly.Msg.TELEGRAM_ID_SHOW = "ID";
Blockly.Msg.TELEGRAM_VIDEO_SHOW = "Video";
Blockly.Msg.TELEGRAM_CANVAS_SHOW = "Canvas";
Blockly.Msg.TELEGRAM_GETUPDATES_SHOW = "Telegram get the latest message";
Blockly.Msg.TELEGRAM_GETMESSAGE_SHOW = " = Telegram latest message";
Blockly.Msg.TELEGRAM_BR_SHOW = "Telegram Line-Break ";
Blockly.Msg.TELEGRAM_REPLYMARKUP_SHOW = "Telegram replyKeyboard";
Blockly.Msg.TELEGRAM_TEXT_SHOW = "message";
Blockly.Msg.TELEGRAM_PHOTOURL_SHOW = "Photo URL";
Blockly.Msg.TELEGRAM_REPLYKEYBOARD_SHOW = "replyKeyboard";
Blockly.Msg.TELEGRAM_ONTIME_SHOW = "onTime";
Blockly.Msg.TELEGRAM_TOKEN_SHOW ="Token";
Blockly.Msg.TELEGRAM_CHATID_SHOW ="Chat ID";
