Blockly.Msg.TELEGRAM_MESSAGE_SHOW = "Telegram 传送讯息";
Blockly.Msg.TELEGRAM_IMAGE_SHOW = "Telegram 传送影像";
Blockly.Msg.TELEGRAM_GETID_SHOW = "取得影像元素 ID";
Blockly.Msg.TELEGRAM_ID_SHOW = "代码";
Blockly.Msg.TELEGRAM_VIDEO_SHOW = "视讯媒体";
Blockly.Msg.TELEGRAM_CANVAS_SHOW = "画布";
Blockly.Msg.TELEGRAM_GETUPDATES_SHOW = "Telegram 取得最新讯息";
Blockly.Msg.TELEGRAM_GETMESSAGE_SHOW = " = Telegram 最新讯息";
Blockly.Msg.TELEGRAM_BR_SHOW = "Telegram 讯息换行";
Blockly.Msg.TELEGRAM_REPLYMARKUP_SHOW = "Telegram 按钮";