var msg = [
["msg_toolbox", "innerHTML", Blockly.Msg["MSG_TOOLBOX"]],
["msg_code", "innerHTML", Blockly.Msg["MSG_CODE"]],
["button_upload", "title", Blockly.Msg["BUTTON_UPLOAD"]],
["button_putty", "title", Blockly.Msg["BUTTON_PUTTY"]],
["button_code", "title", Blockly.Msg["BUTTON_CODE"]],
["button_reset", "title", Blockly.Msg["BUTTON_RESET"]],
["button_open_ino", "title", Blockly.Msg["BUTTON_OPEN_INO"]],
["button_open_xml", "title", Blockly.Msg["BUTTON_OPEN_XML"]],
["button_save_ino", "title", Blockly.Msg["BUTTON_SAVE_INO"]],
["button_toolbox", "title", Blockly.Msg["BUTTON_TOOLBOX"]],
["button_addRemoteBlocks", "title", Blockly.Msg["BUTTON_ADDREMOTEBLOCKS"]],
["button_addExtensionBlocks", "title", Blockly.Msg["BUTTON_ADDEXTENSIONBLOCKS"]],
["button_copycode", "title", Blockly.Msg["BUTTON_COPYCODE"]],
["button_tool", "title", Blockly.Msg["BUTTON_TOOL"]],
["title_code", "innerHTML", Blockly.Msg["MSG_CODE"]],
["lang-selector", "title", Blockly.Msg["LANG-SELECTOR"]],
["board-selector", "title", Blockly.Msg["BOARD-SELECTOR"]],
["com-selector", "title", Blockly.Msg["COM-SELECTOR"]],
["baudrate_title", "innerHTML", Blockly.Msg["BAUDRATE_TITLE"]]
];