Blockly.Msg.OPENAI_TEXT_SHOW = "openAI";
Blockly.Msg.OPENAI_TEXT_INITIAL_SHOW = "Initial";
Blockly.Msg.OPENAI_TEXT_TOKEN_SHOW = "API Key";
Blockly.Msg.OPENAI_TEXT_TOKENS_SHOW = "Max tokens";
Blockly.Msg.OPENAI_TEXT_REQUEST_SHOW = "Request content";
Blockly.Msg.OPENAI_TEXT_RESPONSE_SHOW = "After getting response";
Blockly.Msg.OPENAI_TEXT_RESPONSE_GET_SHOW = "Response";
Blockly.Msg.OPENAI_TEXT_RESPONSE_GET_BR_SHOW = "new line";
Blockly.Msg.OPENAI_TEXT_RESPONSE_CLEAR_SHOW = "Clear response";
