Blockly.Msg.OPENAI_TEXT_SHOW = "openAI";
Blockly.Msg.OPENAI_TEXT_INITIAL_SHOW = "初始化";
Blockly.Msg.OPENAI_TEXT_TOKEN_SHOW = "API Key";
Blockly.Msg.OPENAI_TEXT_TOKENS_SHOW = "最大字数";
Blockly.Msg.OPENAI_TEXT_REQUEST_SHOW = "对话内容";
Blockly.Msg.OPENAI_TEXT_RESPONSE_SHOW = "取得回应内容后执行";
Blockly.Msg.OPENAI_TEXT_RESPONSE_GET_SHOW = "回应内容";
Blockly.Msg.OPENAI_TEXT_RESPONSE_GET_BR_SHOW = "自动换行";
Blockly.Msg.OPENAI_TEXT_RESPONSE_CLEAR_SHOW = "清除回应内容";
