Blockly.Msg.TEACHABLEMACHINE_WIDTH_SHOW = "机器学习(自订模型) 视讯宽度";
Blockly.Msg.TEACHABLEMACHINE_HEIGHT_SHOW = "高度";
Blockly.Msg.TEACHABLEMACHINE_RESULT_SHOW = "结果";
Blockly.Msg.TEACHABLEMACHINE_MIRRORIMAGE_SHOW = "镜像";
Blockly.Msg.TEACHABLEMACHINE_OPACITY_SHOW = "透明度";
Blockly.Msg.TEACHABLEMACHINE_MODEL_SHOW = "模型路径";
Blockly.Msg.TEACHABLEMACHINE_PROPORTION_SHOW = "机器学习(自订模型) 最高";