Blockly.Msg.WEBUSB_ELEMENT_SHOW = "WebUSB 元素";
Blockly.Msg.WEBUSB_SHOW_SHOW = "顯示";
Blockly.Msg.WEBUSB_STATE_SHOW = "WebUSB 開發板連線狀態";
Blockly.Msg.WEBUSB_SEND_SHOW = "WebUSB 傳送指令";
Blockly.Msg.WEBUSB_GET_SHOW = "WebUSB 取得回傳資料";
Blockly.Msg.WEBUSB_WAITTIME_SHOW = "逾時(毫秒)";
Blockly.Msg.WEBUSB_CLEAR_SHOW = "WebUSB 清除回傳資料";
Blockly.Msg.WEBUSB_CONNECT_SHOW = "開發板連結";
Blockly.Msg.WEBUSB_STATUS_SHOW = "狀態";
