Blockly.Msg.BLOCK1_SHOW = " DHT";
Blockly.Msg.VALUE_SHOW = "dataset";
Blockly.Msg.WIDTH_SHOW = "width";
Blockly.Msg.HEIGHT_SHOW = "height";
Blockly.Msg.TITLE_X_SHOW = "title_x";
Blockly.Msg.TITLE_Y_SHOW = "title_y";
Blockly.Msg.BLOCK2_SHOW = " Get";
Blockly.Msg.DATASET_SHOW = "dataset";
Blockly.Msg.COUNT_SHOW = "latest data";
