Blockly.Msg.POSENET_PERSON_SHOW = "姿态侦测 (posenet) 索引";
Blockly.Msg.POSENET_PART_SHOW = "部位";
Blockly.Msg.POSENET_WIDTH_SHOW = "视讯 宽度";
Blockly.Msg.POSENET_HEIGHT_SHOW = "高度";
Blockly.Msg.POSENET_MIRRORIMAGE_SHOW = "镜像";
Blockly.Msg.POSENET_PERSONS_SHOW = "侦测人数";
Blockly.Msg.POSENET_RESULT_SHOW = "输出结果";
Blockly.Msg.POSENET_SCORELIMIT_SHOW = "信心底限";
Blockly.Msg.POSENET_SKELETON_SHOW = "骨架";
