Blockly.Msg.MYCLICKPLACEBLOCK_CLICK_TO_PICK = "取得來源積木";
Blockly.Msg.MYCLICKPLACEBLOCK_CLICK_TO_PLACE_NEXT = "貼上來源積木(Next)";
Blockly.Msg.MYCLICKPLACEBLOCK_CLICK_TO_PLACE_PREVIOUS = "貼上來源積木(Previous)";
Blockly.Msg.MYCLICKPLACEBLOCK_CLICK_TO_PLACE_OUTPUT0 = "貼上來源積木(Input 0)";
Blockly.Msg.MYCLICKPLACEBLOCK_CLICK_TO_PLACE_OUTPUT1 = "貼上來源積木(Input 1)";
Blockly.Msg.MYCLICKPLACEBLOCK_CLICK_TO_PLACE_OUTPUT2 = "貼上來源積木(Input 2)";
Blockly.Msg.MYCLICKPLACEBLOCK_CLICK_TO_PLACE_OUTPUT3 = "貼上來源積木(Input 3)";