Blockly.Blocks['chart_doughnut_create'] = {
  init: function() {
	this.appendDummyInput()
		.appendField(Blockly.Msg["CHART_DOUGHNUT_CREATE"]);
	this.appendValueInput("name")
		.setCheck("String")		
		.appendField(Blockly.Msg["CHART_NAME"]);
	this.appendValueInput("width")
		.setCheck("Number")
		.appendField(Blockly.Msg["CHART_WIDTH"]);  
	this.appendValueInput("height")
		.setCheck("Number")
		.appendField(Blockly.Msg["CHART_HEIGHT"]);	
	this.appendValueInput("left")
		.setCheck("Number")
		.appendField(Blockly.Msg["CHART_LEFT"]);  
	this.appendValueInput("top")
		.setCheck("Number")
		.appendField(Blockly.Msg["CHART_TOP"]);
	this.appendValueInput("val")
		.setCheck("Number")
		.appendField(Blockly.Msg["CHART_VAL"]);  
	this.appendValueInput("min")
		.setCheck("Number")
		.appendField(Blockly.Msg["CHART_MIN"]);	
	this.appendValueInput("max")
		.setCheck("Number")
		.appendField(Blockly.Msg["CHART_MAX"]);  
	this.appendValueInput("decimal")
		.setCheck("Number")
		.appendField(Blockly.Msg["CHART_DECIMAL"]);  
	this.appendValueInput("labelsize")
		.setCheck("Number")
		.appendField(Blockly.Msg["CHART_LABELSIZE"]);	
	this.appendValueInput("valuesize")
		.setCheck("Number")
		.appendField(Blockly.Msg["CHART_VALUESIZE"]); 
	this.appendValueInput("unit")
		.setCheck("String")	
		.appendField(Blockly.Msg["CHART_UNIT"]);
	this.appendValueInput("color")
		.setCheck(null)	
		.appendField(Blockly.Msg["CHART_COLOR"]);			
    this.setInputsInline(false);
	this.setPreviousStatement(!0);
	this.setNextStatement(!0);
    this.setColour(210);
  }
};

Blockly.Blocks['chart_doughnut_set'] = {
  init: function() {
	this.appendDummyInput()
		.appendField(Blockly.Msg["CHART_DOUGHNUT_SET"]);	  
	this.appendValueInput("name")
		.setCheck("String")		
		.appendField(Blockly.Msg["CHART_NAME"]);
	this.appendValueInput("val")
		.setCheck("Number")
		.appendField(Blockly.Msg["CHART_VAL"]); 
    this.setInputsInline(true);
	this.setPreviousStatement(!0);
	this.setNextStatement(!0);
    this.setColour(210);
  }
};	

Blockly.Blocks['chart_gauge_create'] = {
  init: function() {
	this.appendDummyInput()
		.appendField(Blockly.Msg["CHART_GAUGE_CREATE"]);
	this.appendValueInput("id")
		.setCheck("String")		
		.appendField(Blockly.Msg["CHART_ID"]);		
	this.appendValueInput("name")
		.setCheck("String")		
		.appendField(Blockly.Msg["CHART_NAME"]);
	this.appendValueInput("width")
		.setCheck("Number")
		.appendField(Blockly.Msg["CHART_WIDTH"]);
	this.appendValueInput("left")
		.setCheck("Number")
		.appendField(Blockly.Msg["CHART_LEFT"]);  
	this.appendValueInput("top")
		.setCheck("Number")
		.appendField(Blockly.Msg["CHART_TOP"]);
	this.appendValueInput("val")
		.setCheck("Number")
		.appendField(Blockly.Msg["CHART_VAL"]);  
	this.appendValueInput("min")
		.setCheck("Number")
		.appendField(Blockly.Msg["CHART_MIN"]);	
	this.appendValueInput("max")
		.setCheck("Number")
		.appendField(Blockly.Msg["CHART_MAX"]);  
	this.appendValueInput("decimal")
		.setCheck("Number")
		.appendField(Blockly.Msg["CHART_DECIMAL"]);  
	this.appendValueInput("labelsize")
		.setCheck("Number")
		.appendField(Blockly.Msg["CHART_LABELSIZE"]);
	this.appendValueInput("unit")
		.setCheck("String")	
		.appendField(Blockly.Msg["CHART_UNIT"]);
	this.appendValueInput("color")
		.setCheck(null)	
		.appendField(Blockly.Msg["CHART_COLOR"]);			
    this.setInputsInline(false);
	this.setPreviousStatement(!0);
	this.setNextStatement(!0);
    this.setColour(130);
  }
};

Blockly.Blocks['chart_gauge_set'] = {
  init: function() {
	this.appendDummyInput()
		.appendField(Blockly.Msg["CHART_GAUGE_SET"]);	  
	this.appendValueInput("id")
		.setCheck("String")		
		.appendField(Blockly.Msg["CHART_ID"]);
	this.appendValueInput("val")
		.setCheck("Number")
		.appendField(Blockly.Msg["CHART_VAL"]); 
    this.setInputsInline(true);
	this.setPreviousStatement(!0);
	this.setNextStatement(!0);
    this.setColour(130);
  }
};