Blockly.Msg.SPEECHRECOGNITION_SHOW = "開始語音辨識";
Blockly.Msg.SPEECHRECOGNITION_LANGUAGE_SHOW = "語言";
Blockly.Msg.SPEECHRECOGNITION_FINAL_GET_SHOW = "取得語音辨識最終文字";
Blockly.Msg.SPEECHRECOGNITION_INTERIM_GET_SHOW = "取得語音辨識臨時文字";
Blockly.Msg.SPEECHRECOGNITION_LISTENER_SHOW = "開始監聽語音辨識";
Blockly.Msg.SPEECHRECOGNITION_KEYWORD_SHOW = "包含關鍵字";
