Blockly.Msg.SPEECHRECOGNITION_SHOW = "开始语音辨识";
Blockly.Msg.SPEECHRECOGNITION_LANGUAGE_SHOW = "语言";
Blockly.Msg.SPEECHRECOGNITION_FINAL_GET_SHOW = "取得语音辨识最终文字";
Blockly.Msg.SPEECHRECOGNITION_FINAL_CLEAR_SHOW = "清除语音辨识最终文字";
Blockly.Msg.SPEECHRECOGNITION_INTERIM_GET_SHOW = "取得语音辨识临时文字";
Blockly.Msg.SPEECHRECOGNITION_LISTENER_SHOW = "开始监听语音辨识";
Blockly.Msg.SPEECHRECOGNITION_KEYWORD_SHOW = "包含关键字";
