Blockly.Msg["CATKEYBOARD"] = "Keyboard"
Blockly.Msg["KEYBOARD_LISTENER_SHOW"] = "Keyboard Listener";
Blockly.Msg["STOP_KEYBOARD_LISTENER_SHOW"] = "Stop Keyboard Listener";
Blockly.Msg["GET_KEYCODE_SHOW"] = "Get Keycode";
Blockly.Msg["KEYCODE_SHOW"] = "Key is";
Blockly.Msg["HOTKEY_SHOW"] = "HotKey is";
Blockly.Msg["KEYBOARD_KEYDOWN"] = "KEY DOWN";
Blockly.Msg["KEYBOARD_KEYUP"] = "KEY UP";
Blockly.Msg["KEYBOARD_KEYPRESS"] = "KEY PRESS";
