Blockly.Msg["CATKEYBOARD"] = "Keyboard Events";
Blockly.Msg["KEYBOARD_LISTENER_SHOW"] = "Start Listening to Keyboard";
Blockly.Msg["STOP_KEYBOARD_LISTENER_SHOW"] = "Stop Listening to Keyboard";
Blockly.Msg["GET_KEYCODE_SHOW"] = "Get Key Code Value";
Blockly.Msg["KEYCODE_SHOW"] = "Get Key Code Value of";
Blockly.Msg["HOTKEY_SHOW"] = "Get Shortcut Key Code Value of";
Blockly.Msg["KEYBOARD_KEYDOWN"] = "Key Down";
Blockly.Msg["KEYBOARD_KEYUP"] = "Key Up";
Blockly.Msg["KEYBOARD_KEYPRESS"] = "Key Press";
