Blockly.Msg.COCOSSD_OBJECT_SHOW = "物件偵測(coco-ssd) 偵測物件";
Blockly.Msg.COCOSSD_OBJECT_NUMBER_SHOW = "物件偵測(coco-ssd) 偵測物件數目";
Blockly.Msg.COCOSSD_INDEX_SHOW = "索引";
Blockly.Msg.COCOSSD_WIDTH_SHOW = "視訊 (coco-ssd) 寬度";
Blockly.Msg.COCOSSD_HEIGHT_SHOW = "高度";
Blockly.Msg.COCOSSD_MIRRORIMAGE_SHOW = "鏡像";
Blockly.Msg.COCOSSD_RESULT_SHOW = "結果";
Blockly.Msg.COCOSSD_FRAME_SHOW = "框架";
Blockly.Msg.COCOSSD_OPACITY_SHOW = "透明度";
