Blockly.Msg.SPEECHRECOGNITION_SHOW = "開始語音辨識";
Blockly.Msg.SPEECHRECOGNITION_LANGUAGE_SHOW = "語言";
Blockly.Msg.SPEECHRECOGNITION_GET_SHOW = "取得語音辨識文字";
Blockly.Msg.SPEECHRECOGNITION_LISTENER_SHOW = "開始監聽語音辨識";
