Blockly.Msg.AZUREFACETOFACEVERIFY_DETECT_SHOW = "Verify Face To Face (Azure) Detect";
Blockly.Msg.AZUREFACETOFACEVERIFY_GET_SHOW = "Verify Face To Face (Azure) Get";
Blockly.Msg.AZUREFACETOFACEVERIFY_GETDATA_SHOW = "Verify Face To Face (Azure) Get Data";
Blockly.Msg.AZUREFACETOFACEVERIFY_SETTINGS_SHOW ="Verify Face To Face (Azure) Settings";
Blockly.Msg.AZUREFACETOFACEVERIFY_RESOURCENAME_SHOW ="Resource Host";
Blockly.Msg.AZUREFACETOFACEVERIFY_KEY_SHOW = "Ocp-Apim-Subscription-Key";
Blockly.Msg.AZUREFACETOFACEVERIFY_FACEID1_SHOW = "Face Id1";
Blockly.Msg.AZUREFACETOFACEVERIFY_FACEID2_SHOW = "Face Id2";
