Blockly.Msg.AZUREFACETOFACEVERIFY_DETECT_SHOW = "两脸核对 (Azure) 侦测";
Blockly.Msg.AZUREFACETOFACEVERIFY_GET_SHOW = "两脸核对 (Azure) 取得";
Blockly.Msg.AZUREFACETOFACEVERIFY_GETDATA_SHOW = "两脸核对 (Azure) 取得资料";
Blockly.Msg.AZUREFACETOFACEVERIFY_SETTINGS_SHOW ="两脸核对 (Azure) 设定";
Blockly.Msg.AZUREFACETOFACEVERIFY_RESOURCENAME_SHOW ="Resource Host";
Blockly.Msg.AZUREFACETOFACEVERIFY_KEY_SHOW = "Ocp-Apim-Subscription-Key";
Blockly.Msg.AZUREFACETOFACEVERIFY_FACEID1_SHOW = "Face Id1";
Blockly.Msg.AZUREFACETOFACEVERIFY_FACEID2_SHOW = "Face Id2";
