Blockly.Msg["SPEECHRECOGNITION"] = "语音辨识";
Blockly.Msg["SPEECHRECOGNITION_HUE"] = "280";

Blockly.Msg.SPEECHRECOGNITION_SHOW = "开始语音辨识";
Blockly.Msg.SPEECHRECOGNITION_LANGUAGE_SHOW = "语言";
Blockly.Msg.SPEECHRECOGNITION_GET_SHOW = "取得语音辨识文字";
Blockly.Msg.SPEECHRECOGNITION_LISTENER_SHOW = "开始监听语音辨识";
