Blockly.Msg.TESSERACT_WIDTH_SHOW = "文字辨识 视讯宽度";
Blockly.Msg.TESSERACT_HEIGHT_SHOW = "高度";
Blockly.Msg.TESSERACT_RECOGNITION_SHOW = "文字辨识 ";
Blockly.Msg.TESSERACT_GET_SHOW = "文字辨识 取得结果";
Blockly.Msg.TESSERACT_RESULT_SHOW = "结果";
Blockly.Msg.TESSERACT_OPACITY_SHOW = "透明度";
Blockly.Msg.TESSERACT_SHOWTIME_SHOW = "显示截图(秒)";
Blockly.Msg.TESSERACT_LANG_SHOW = "语言";
Blockly.Msg.TESSERACT_CLEAR_SHOW = "清除辨识结果";
