Blockly.Msg.TESSERACT_WIDTH_SHOW = "文字辨識 視訊寬度";
Blockly.Msg.TESSERACT_HEIGHT_SHOW = "高度";
Blockly.Msg.TESSERACT_RECOGNITION_SHOW = "文字辨識 ";
Blockly.Msg.TESSERACT_GET_SHOW = "文字辨識 取得結果";
Blockly.Msg.TESSERACT_RESULT_SHOW = "結果";
Blockly.Msg.TESSERACT_OPACITY_SHOW = "透明度";
Blockly.Msg.TESSERACT_SHOWTIME_SHOW = "顯示截圖(秒)";
Blockly.Msg.TESSERACT_LANG_SHOW = "語言";
Blockly.Msg.TESSERACT_CLEAR_SHOW = "清除辨識結果";
