Blockly.Msg.SHOWTEXT_SHOW = "Show Text";
Blockly.Msg.SHOWTEXT_SIZE_SHOW = "size";
Blockly.Msg.SHOWTEXT_COLOR_SHOW = "color";
Blockly.Msg.SHOWTEXT_TEXT_SHOW = "Text";
Blockly.Msg.LINEBREAK_SHOW = "Line Break";
Blockly.Msg.SETSCREEN_LEFT_SHOW = "LEFT";
Blockly.Msg.SETSCREEN_TOP_SHOW = "TOP";
Blockly.Msg.SETSCREEN_WIDTH_SHOW = "WIDTH";
Blockly.Msg.SETSCREEN_HEIGHT_SHOW = "HEIGHT";