Blockly.Msg.OPEN_SHOW = "Open Link";
Blockly.Msg.CLOSE_SHOW = "Close Link";
Blockly.Msg.OPENID_SHOW = "ID";
Blockly.Msg.CLOSEID_SHOW = "ID";
Blockly.Msg.URL_SHOW = "Url";
Blockly.Msg.WIDTH_SHOW = "Width";
Blockly.Msg.LEFT_SHOW = "Left";
Blockly.Msg.TOP_SHOW = "Top";
Blockly.Msg.ZINDEX_SHOW = "Z-index";
