MSG.CATCHART = "仪表板";
MSG.CATCHARTDOUGHNUT = "甜甜圈图";
MSG.CATCHARTGAUGE = "温度图";
MSG.CATCHARTWATERBUBBLE = "水位图";
MSG.CATLINECHART = "折线图";
MSG.CATBARCHART = "长条图";
MSG.CATCANALOGGAUGE = "类比图";
MSG.CATCHARTSWITCH = "滑动开关";
