MSG.CATCHART = "仪表板";
MSG.CATCHARTDOUGHNUT = "甜甜圈";
MSG.CATCHARTGAUGE = "温度计";
MSG.CATCHARTWATERBUBBLE = "水位计";
MSG.CATLINECHART = "折线图";
MSG.CATBARCHART = "长条图";
MSG.CATCANALOGGAUGE = "类比计";
MSG.CATCHARTSWITCH = "滑动开关";