MSG.CATCHART = "儀表板";
MSG.CATCHARTDOUGHNUT = "甜甜圈圖";
MSG.CATCHARTGAUGE = "溫度圖";
MSG.CATCHARTWATERBUBBLE = "水位圖";
MSG.CATLINECHART = "折線圖";
MSG.CATBARCHART = "長條圖";
MSG.CATCANALOGGAUGE = "類比圖";
MSG.CATCHARTSWITCH = "滑動開關";
