/* eslint-disable */
;(function(root, factory) {
  if (typeof define === 'function' && define.amd) { // AMD
    define([], factory);
  } else if (typeof exports === 'object') { // Node.js
    module.exports = factory();
  } else { // Browser
    var messages = factory();
    for (var key in messages) {
      root.Blockly.Msg[key] = messages[key];
    }
  }
}(this, function() {
// This file was automatically generated.  Do not modify.

'use strict';

var Blockly = Blockly || { Msg: Object.create(null) };

Blockly.Msg.FUNCTION_ASYNC = "非同步(async)";
Blockly.Msg.ADD_COMMENT = "加入批注";

Blockly.Msg.ARDUINO = "ARDUINO";
Blockly.Msg.ARDUINO_CODE = "程序代码　　　";
Blockly.Msg.ARRAY_CREATE_WITH_CONTAINER_TITLE_ADD = "数组";
Blockly.Msg.ARRAY_CREATE_WITH_CONTAINER_TOOLTIP = "新增、移除或重新排列以重新设定数组积木。";
Blockly.Msg.ARRAY_CREATE_WITH_HELPURL = "";
Blockly.Msg.ARRAY_CREATE_WITH_INPUT_WITH = "建立数组使用 ";
Blockly.Msg.ARRAY_CREATE_WITH_ITEM_TITLE = "物件";
Blockly.Msg.ARRAY_CREATE_WITH_ITEM_TOOLTIP = "新增一个对象至数组";
Blockly.Msg.ARRAY_CREATE_WITH_TOOLTIP = "使用任意数量的对象来建立一个数组。";
Blockly.Msg.ARRAY_GETINDEX_AT = "取得第";
Blockly.Msg.ARRAY_GETINDEX_AT1 = "取得第";
Blockly.Msg.ARRAY_GETINDEX_AT2 = "索引";
Blockly.Msg.ARRAY_GETINDEX_HELPURL = "";
Blockly.Msg.ARRAY_GETINDEX_ITEM = "于数组中";
Blockly.Msg.ARRAY_GETSIZE_ITEM = "取得数组长度";
Blockly.Msg.ARRAY_GETINDEX_TOOLTIP = "";
Blockly.Msg.ARRAY_MODIFY_INDICE = "设定第";
Blockly.Msg.ARRAY_MODIFY_NAME = "将数组";
Blockly.Msg.ARRAY_MODIFY_VALUE = "资料为";
Blockly.Msg.ARRAY_MODIFY_TOOLTIP = "set a specific value to an elemnt of an array";
Blockly.Msg.ARRAY_FOR_INPUT_FROM_TO = "从范围 %1 到取得 %2 数组长度" ;
Blockly.Msg.ARRAY_FOR_INPUT_FROM_TO1 = "从范围 " ;
Blockly.Msg.ARRAY_FOR_INPUT_FROM_TO2 = " 到取得 " ;
Blockly.Msg.ARRAY_FOR_INPUT_FROM_TO3 = " 数组长度" ;
Blockly.Msg.AUTH = "Please authorize this app to enable your work to be saved and to allow it to be shared by you.";  // untranslated
Blockly.Msg.AUTO_SAVE_TITLE = "自动储存";
Blockly.Msg.BLOCKS = "　积木　";
Blockly.Msg.BLUE = "蓝";

Blockly.Msg.BUTTON_EXPORT = "汇出";
Blockly.Msg.BUTTON_IMPORT = "汇入";
Blockly.Msg.BUTTON_NEW = "新建";
Blockly.Msg.BUTTON_OPEN = "开启";
Blockly.Msg.BUTTON_SAVE = "储存";
Blockly.Msg.CAST_NUMBER_HELPURL = "https://www.arduino.cc/en/Reference/Cast";
Blockly.Msg.CAST_NUMBER_TITLE = "Type cast";
Blockly.Msg.CAST_NUMBER_TOOLTIP = "The cast operator translates one variable type into another and forces calculations to be performed in the cast type.";

Blockly.Msg.CHANGE = "变更";
Blockly.Msg.CHANGE_LANG = "变更语言";
Blockly.Msg.CHANGE_VALUE_TITLE = "修改值：";
Blockly.Msg.CHAT = "与您的合作者洽谈藉由在此框输入！";
Blockly.Msg.COL = "Col";  // untranslated
Blockly.Msg.COLLAPSE_ALL = "收合积木";
Blockly.Msg.COLLAPSE_BLOCK = "收合积木";
Blockly.Msg.COLOR = "颜色";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "颜色 1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "颜色 2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";
Blockly.Msg.COLOUR_BLEND_RATIO = "比例";
Blockly.Msg.COLOUR_BLEND_TITLE = "混合";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "透过一个比率 (0.0-1.0)来混合两种颜色。";
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://en.wikipedia.org/wiki/Color";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "从调色板中选择一种颜色。";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "随机颜色";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "随机选择一种颜色。";
Blockly.Msg.COLOUR_RGB_BLUE = "蓝";
Blockly.Msg.COLOUR_RGB_GREEN = "绿";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";
Blockly.Msg.COLOUR_RGB_RED = "红";
Blockly.Msg.COLOUR_RGB_TITLE = "颜色";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "透过指定红、绿、 蓝色的值来建立一种颜色。所有的值必须介于 0 和 100 之间。";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "停止 循环";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "继续下一个 循环";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "离开当前的 循环";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "跳过这个循环的其余步骤，并继续下一次的循环运算。";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "警告： 此积木仅可用于循环内。";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each 查看积木细节";
Blockly.Msg.CONTROLS_FOREACH_INPUT_INLIST = "自列表";
Blockly.Msg.CONTROLS_FOREACH_INPUT_INLIST_TAIL = "";
Blockly.Msg.CONTROLS_FOREACH_INPUT_ITEM = "取出每个";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "遍历每个列表中的项目，将变量  '%1' 设定到该项目中，然后执行某些语句";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP1 = "遍历每个列表中的项目，将变量  '";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP2 = "' 设定到该项目中，然后执行某些语句";
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO = "从范围 %1 到 %2";
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO1 = "从范围 ";
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO2 = " 到 ";
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO_BY = "从范围 %1 到 %2 每隔 %3";
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO_BY1 = "从范围 ";
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO_BY2 = " 到 ";
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO_BY3 = " 每隔 ";
Blockly.Msg.CONTROLS_FOR_INPUT_WITH = "使用";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "从起始数到结尾数中取出变量 %1 的值，按指定的时间间隔，执行指定的积木。";
Blockly.Msg.CONTROLS_FOR_TOOLTIP1 = "从起始数到结尾数中取出变数 ";
Blockly.Msg.CONTROLS_FOR_TOOLTIP2 = " 的值，按指定的时间间隔，执行指定的积木。";
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "将条件添加到'如果'积木。";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "加入一个最终，所有条件下都都执行的区块到'如果'积木中";
Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "添加、 删除或重新排列各区块来此重新配置这个'如果'积木。";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "否则";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "否则如果";
Blockly.Msg.CONTROLS_IF_MSG_IF = "如果";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "当值为真时，执行一些语句";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "当值为真时，执行第一个语句，否则则执行第二个语句";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "如果第一个值为真，则执行第一个语句。否则当第二个值为真时，则执行第二个语句";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "如果第一个值为真，则执行第一个语句。否则当第二个值为真时，则执行第二个语句。如果前几个叙述都不为真，则执行最后一个语句";
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://en.wikipedia.org/wiki/For_loop";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "执行";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "重复 %1 次";
Blockly.Msg.CONTROLS_REPEAT_TITLE1 = "重复 ";
Blockly.Msg.CONTROLS_REPEAT_TITLE2 = " 次";
Blockly.Msg.CONTROLS_REPEAT_TITLE_REPEAT = "重复 ";
Blockly.Msg.CONTROLS_REPEAT_TITLE_TIMES = " 次数";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "多次执行一些语句";
Blockly.Msg.CONTROLS_RETURN_HELPURL = "https://www.arduino.cc/en/Reference/Return";
Blockly.Msg.CONTROLS_RETURN_TITLE = "返回";
Blockly.Msg.CONTROLS_RETURN_TOOLTIP = "Terminate a function and return a value from a function to the calling function, if desired.";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "重复 直到";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "重复 当";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "当值为否时，执行一些语句";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "当值为真时，执行一些语句";
Blockly.Msg.CONTROLS_WHILE_HELPURL = "https://www.arduino.cc/en/Reference/While";  // untranslated
Blockly.Msg.CONTROLS_WHILE_INPUT_DO = "执行";  // untranslated
Blockly.Msg.CONTROLS_WHILE_TITLE = "当";  // untranslated
Blockly.Msg.CONTROLS_WHILE_TOOLTIP = "while loops will loop continuously, and infinitely, until the expression inside the parenthesis, () becomes false.";  // untranslated
Blockly.Msg.COPY_BUTTON = "Clip Code";  // untranslated
Blockly.Msg.COPY_DONE = "拷贝完成！";  // untranslated
Blockly.Msg.DATA_LENGTH = "数据长度";  // untranslated
Blockly.Msg.DATA_TYPE = "数据型态";  // untranslated
Blockly.Msg.DELETE_ALL1 = "删除全部";  // untranslated
Blockly.Msg.DELETE_ALL2 = "积木？";  // untranslated
Blockly.Msg.DELETE_BLOCK = "删除积木";
Blockly.Msg.DELETE_X_BLOCKS = "删除 %1 块积木";
Blockly.Msg.DELETE_X_BLOCKS1 = "删除 ";
Blockly.Msg.DELETE_X_BLOCKS2 = " 块积木";
Blockly.Msg.DEVICE_ID = "DeviceID";  // untranslated
Blockly.Msg.SETTINGS_OK = "储存并重新启动";
Blockly.Msg.SETTINGS_CANCEL = "取消";
Blockly.Msg.SETTINGS_VERSION = "版本：";
Blockly.Msg.SETTINGS_VERSION_PRE_RELEASE = "（测试版）";
Blockly.Msg.MESSAGE_UPDATE = "更新版本 ";
Blockly.Msg.MESSAGE_UPDATE_APPEND = " 目前可供下载！";
Blockly.Msg.DIALOG1_NO = "否";
Blockly.Msg.DIALOG1_TITLE = "重设？";
Blockly.Msg.DIALOG1_YES = "是";
Blockly.Msg.DIALOG2_TITLE = "文件名";
Blockly.Msg.DIALOG3_TITLE = "无法读取 XML 档案";
Blockly.Msg.DIALOG4_TITLE = "删除所有积木？";
Blockly.Msg.DIALOG_BLOCK_TITLE = "选择性积木";
Blockly.Msg.DIALOG_EXPORT_OK = "关闭";
Blockly.Msg.DIALOG_IMPORT_CANCEL = "取消";
Blockly.Msg.DIALOG_IMPORT_OK = "汇入";
Blockly.Msg.DIALOG_LANG_TITLE = "选择语言";
Blockly.Msg.DIALOG_SENDCHROME = "将范例传送至 ChromeApp？";
Blockly.Msg.DIRECTION = "方向";
Blockly.Msg.DISABLE_BLOCK = "停用积木";
Blockly.Msg.DISCARD = "放弃";
Blockly.Msg.DO = "执行";
Blockly.Msg.DOUBLE = "倍精度浮点数";
Blockly.Msg.DOWNLOAD_CHROME_APP = "下载脱机版编辑器";
Blockly.Msg.DROPDOWN_DISCARD = "放弃积木"
Blockly.Msg.DROPDOWN_SAVE_AS = "另存新檔...";
Blockly.Msg.DUPLICATE_BLOCK = "复制";

Blockly.Msg.ENABLE_BLOCK = "启用积木";
Blockly.Msg.ERROR_BETA_WARNING = '您正在使用测试版本，请改用稳定版本！';
Blockly.Msg.ERROR_FILENAME = "请输入文件名！";
Blockly.Msg.ERROR_FILENAME2 = "文件名错误！";
Blockly.Msg.ERROR_PARSING_XML = "XML 读取错误";

Blockly.Msg.EXPAND_ALL = "展开积木";
Blockly.Msg.EXPAND_BLOCK = "展开积木";
Blockly.Msg.EXTERNAL_INPUTS = "多行输入";
Blockly.Msg.FALLING = "下降边缘";  // untranslated
Blockly.Msg.GO_TO_SAMPLE = "链接至范例页面";
Blockly.Msg.GO_TO_WEB = "连结至在线编辑器";
Blockly.Msg.GREEN = "绿";

Blockly.Msg.HELP = "说明";

Blockly.Msg.INDEX = "Index";  // untranslated
Blockly.Msg.INFO_FILENAME = "文件名：";
Blockly.Msg.INFO_TITLE = "[无已加载的文件]";

Blockly.Msg.INLINE_INPUTS = "单行输入";
Blockly.Msg.INTEGER = "整数";


Blockly.Msg.LEFT = "左";
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "建立空列表";
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE_PROCEDURE = "空变数";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "返回一个长度为 0 的列表，不包含任何数据记录";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "加入";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "添加、 删除或重新排列各区块来此重新配置这个 列表 积木。";
Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "建立值的列表";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "将一个项目加入到列表中。";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "建立一个具备任意数量项目的列表。";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "第一笔";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "倒数第#笔";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";
Blockly.Msg.LISTS_GET_INDEX_GET = "取值";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "取出并移除";
Blockly.Msg.LISTS_GET_INDEX_LAST = "最后一笔";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "随机";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "移除";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "返回列表中的第一个项目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "返回在列表中的指定位置的项目。#1 是最后一个项目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "返回在列表中的指定位置的项目。#1 是第一个项目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "返回列表中的最后一个项目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "返回列表中随机的一个项目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "移除并返回列表中的第一个项目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "移除并返回列表中的指定位置的项目。#1 是最后一个项目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "移除并返回列表中的指定位置的项目。#1 是第一个项目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "移除并返回列表中的最后一个项目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "移除并返回列表中的随机一个项目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "移除列表中的第一个项目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "移除在列表中的指定位置的项目。#1 是最后一个项目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "移除在列表中的指定位置的项目。#1 是第一个项目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "移除列表中的最后一个项目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "移除列表中随机的一个项目";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "到 倒数 # 位";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "到 #";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "到 最后";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "从 头 取得子列表";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "从倒数 # 取得子列表";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "从 # 取得子列表";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "复制列表中指定的部分。";
Blockly.Msg.LISTS_INDEX_OF_FIRST = "找出 第一个 项目出现";
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";
Blockly.Msg.LISTS_INDEX_OF_LAST = "找出 最后一个 项目出现";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "返回在列表中的第一个/最后一个匹配项目的索引值。如果未找到则返回 0。";
Blockly.Msg.LISTS_INLIST = "自列表";
Blockly.Msg.LISTS_IS_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty";
Blockly.Msg.LISTS_IS_EMPTY_TITLE = "%1 值为空";
Blockly.Msg.LISTS_IS_EMPTY_TITLE1 = " 值为空";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "返回列表的长度。";
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";
Blockly.Msg.LISTS_REPEAT_TITLE = "建立列表使用项目 %1 重复 %2 次数";
Blockly.Msg.LISTS_REPEAT_TITLE1 = "建立列表使用项目 ";
Blockly.Msg.LISTS_REPEAT_TITLE2 = " 重复 ";
Blockly.Msg.LISTS_REPEAT_TITLE3 = " 次数";
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "建立包含指定重复次数的 值 的列表。";
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set";
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "为";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "插入到";
Blockly.Msg.LISTS_SET_INDEX_SET = "设定";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "在列表的起始处添加一个项目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "插入在列表中的指定位置的项目。#1 是最后一个项目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "插入在列表中的指定位置的项目。#1 是第一个项目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "在列表的尾端加入一个项目";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "在列表中随机插入项目";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "设定列表中的第一个项目";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "设定在列表中的指定位置的项目。#1 是最后一个项目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "设定在列表中的指定位置的项目。#1 是第一个项目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "设定列表中的最后一个项目";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "设定列表中随机的一个项目";
Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";
Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "make list from text";  // untranslated
Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "make text from list";  // untranslated
Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "Join a list of texts into one text, separated by a delimiter.";  // untranslated
Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "Split text into a list of texts, breaking at each delimiter.";  // untranslated
Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "with delimiter";  // untranslated
Blockly.Msg.LISTS_TOOLTIP = "如果该列表为空，则返回 真。";
Blockly.Msg.LOAD_XML = "载入 XML";
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "否";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "返回 真 或 否。";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "真";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://en.wikipedia.org/wiki/Inequality_(mathematics)";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "如果这两个输入区块内容相等，返回 真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "如果第一个输入大于第二个输入，返回 真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "如果第一个输入大于或等于第二个输入，返回 真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "如果第一个输入小于第二个输入，返回 真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "如果第一个输入是小于或等于第二个输入，返回 真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "如果这两个输入区块内容不相等，返回 真。";
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not";
Blockly.Msg.LOGIC_NEGATE_TITLE = "非";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "如果输入的值是 否，则返回 真。如果输入的值是 真 返回 否。";
Blockly.Msg.LOGIC_NULL = "空";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type";
Blockly.Msg.LOGIC_NULL_TOOLTIP = "返回 空。";
Blockly.Msg.LOGIC_OPERATION_AND = "且";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations";
Blockly.Msg.LOGIC_OPERATION_OR = "或";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "如果这两个输入值都为 真，则返回 真。";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "如果至少一个输入的值为 真，返回 真。";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "测试";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://en.wikipedia.org/wiki/%3F:";
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "如果为非";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "如果为真";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "检查 'test' 中的条件。如果条件为 真，将返回 '如果为 真' 值 ；否则，返回 '如果为 否' 的值。";


Blockly.Msg.MATH_ADDITION_SYMBOL = "+";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://en.wikipedia.org/wiki/Arithmetic";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "返回两个数字的总和。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "返回两个数字的商。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "返回两个数字的差。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MODULO = "Return the remainder when one integer is divided by another.";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "返回两个数字的乘积。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "返回第二个数字的指数的第一个数字。";
Blockly.Msg.MATH_CHANGE_HELPURL = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
Blockly.Msg.MATH_CHANGE_INPUT_BY = "增量";
Blockly.Msg.MATH_CHANGE_TITLE_CHANGE = "修改";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "将数字添加到变量 '%1'。";
Blockly.Msg.MATH_CHANGE_TOOLTIP1 = "将数字添加到变量 '";
Blockly.Msg.MATH_CHANGE_TOOLTIP2 = "'。";
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://en.wikipedia.org/wiki/Mathematical_constant";
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "返回一个的常见常量： π (3.141......)，e (2.718...)、 φ (1.618...)、 开方(2) (1.414......)、 开方(½) (0.707......) 或 ∞ （无穷大）。";
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_TITLE = "限制数字 %1 介于 (低) %2 到 (高) %3";
Blockly.Msg.MATH_CONSTRAIN_TITLE1 = "限制数字 ";
Blockly.Msg.MATH_CONSTRAIN_TITLE2 = " 介于 (低) ";
Blockly.Msg.MATH_CONSTRAIN_TITLE3 = " 到 (高) ";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "限制数字介于两个指定的数字之间";
Blockly.Msg.MATH_DIVISION_SYMBOL = "÷";
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "可被整除";
Blockly.Msg.MATH_IS_EVEN = "是偶数";
Blockly.Msg.MATH_IS_NEGATIVE = "是负值";
Blockly.Msg.MATH_IS_ODD = "是奇数";
Blockly.Msg.MATH_IS_POSITIVE = "是正值";
Blockly.Msg.MATH_IS_PRIME = "是质数";
Blockly.Msg.MATH_IS_TOOLTIP = "如果数字是偶数，奇数，非负整数，正数、 负数或如果它是可被某数字整除，则返回 真 或 否。";
Blockly.Msg.MATH_IS_WHOLE = "是非负整数";
Blockly.Msg.MATH_MAP_APPENDTEXT_FROMHIGH = "由高";
Blockly.Msg.MATH_MAP_APPENDTEXT_FROMLOW = "由低";
Blockly.Msg.MATH_MAP_APPENDTEXT_MAP = "映射";
Blockly.Msg.MATH_MAP_APPENDTEXT_TOHIGH = "至高";
Blockly.Msg.MATH_MAP_APPENDTEXT_TOLOW = "至低";
Blockly.Msg.MATH_MAP_APPENDTEXT_VALUE = "数值";
Blockly.Msg.MATH_MAP_HELPURL = "http://arduino.cc/en/Reference/map";
Blockly.Msg.MATH_MAP_TOOLTIP = "将数值由一个区间映射至另一区间。";
Blockly.Msg.MATH_MAP_FLOAT_APPENDTEXT_MAP = "浮点数映射:"
Blockly.Msg.MATH_MODULO_HELPURL = "https://en.wikipedia.org/wiki/Modulo_operation";
Blockly.Msg.MATH_MODULO_SYMBOL = "%";
Blockly.Msg.MATH_MODULO_TITLE = "取余数自 %1 ÷ %2";
Blockly.Msg.MATH_MODULO_TITLE1 = "取余数自 ";
Blockly.Msg.MATH_MODULO_TITLE2 = " ÷ ";
Blockly.Msg.MATH_MODULO_TOOLTIP = "回传两个数字相除的余数";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×";
Blockly.Msg.MATH_NUMBER_HELPURL = "https://en.wikipedia.org/wiki/Number";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "一个数字。";
Blockly.Msg.MATH_ONLIST_HELPURL = "";
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "平均值 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "最大值 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "中位数 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "最小值 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "比较众数 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "随机抽取 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "标准偏差 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "总和 自列表";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "返回列表中数值的平均值 （算术平均值）。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "返回列表中的最大数字。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "返回列表中数值的中位数。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "返回列表中的最小数字。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "返回一个列表中的最常见项目的列表。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "从列表中返回一个随机的项目。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "返回列表中数字的标准偏差。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "返回列表中的所有数字的总和。";
Blockly.Msg.MATH_POWER_SYMBOL = "^";
Blockly.Msg.MATH_POW_BASE = "基数";
Blockly.Msg.MATH_POW_EXP = "指数";
Blockly.Msg.MATH_POW_HELPURL = "http://arduino.cc/en/Reference/pow";
Blockly.Msg.MATH_POW_TITLE = "乘方";
Blockly.Msg.MATH_POW_TOOLTIP = "Calculates the value of a number raised to a power.";  // untranslated
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "取随机分数";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "返回介于 （包含） 0.0 到 1.0 之间的随机数。";
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_INT_TITLE = "取随机整数介于 (低) %1 到 %2";
Blockly.Msg.MATH_RANDOM_INT_TITLE1 = "取随机整数介于 (低) ";
Blockly.Msg.MATH_RANDOM_INT_TITLE2 = " 到 ";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "回传限制的数字区间内的随机数字";
Blockly.Msg.MATH_RANDOM_MAX_MIN_APPENDTEXT_MAX = "最大";
Blockly.Msg.MATH_RANDOM_MAX_MIN_APPENDTEXT_MIN = "最小";
Blockly.Msg.MATH_RANDOM_MAX_MIN_APPENDTEXT_RANDOM = "随机";
Blockly.Msg.MATH_RANDOM_MAX_MIN_HELPURL = "http://arduino.cc/en/Reference/Random";  // untranslated
Blockly.Msg.MATH_RANDOM_MAX_MIN_TOOLTIP = "The random function generates pseudo-random numbers.";  // untranslated
Blockly.Msg.MATH_ROUND_HELPURL = "https://en.wikipedia.org/wiki/Rounding";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "四舍五入";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "无条件舍去";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "无条件进位";
Blockly.Msg.MATH_ROUND_TOOLTIP = "将数字向上或向下舍入。";
Blockly.Msg.MATH_SINGLE_HELPURL = "https://en.wikipedia.org/wiki/Square_root";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "绝对值";
Blockly.Msg.MATH_SINGLE_OP_ROOT = "开根号";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "返回指定数字的绝对值。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "返回指定数字指数的 e";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "返回指定数字的自然对数。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "返回指定数字的对数。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "返回指定数字的 negation。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "返回指定数字指数的10的幂次。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "返回指定数字的平方根。";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";
Blockly.Msg.MATH_TRIG_ACOS = "反余弦";
Blockly.Msg.MATH_TRIG_ASIN = "反正弦";
Blockly.Msg.MATH_TRIG_ATAN = "反正切";
Blockly.Msg.MATH_TRIG_COS = "余弦";
Blockly.Msg.MATH_TRIG_HELPURL = "https://en.wikipedia.org/wiki/Trigonometric_functions";
Blockly.Msg.MATH_TRIG_SIN = "正弦";
Blockly.Msg.MATH_TRIG_TAN = "正切";
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "返回指定角度的反余弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "返回指定角度的反正弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "返回指定角度的反正切值。";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "返回指定角度的余弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "返回指定角度的正弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "返回指定角度的正切值(非弧度）。";
Blockly.Msg.MATH_DEGREE_TO_RADIAN_HELPURL = "https://en.wikipedia.org/wiki/Radian";
Blockly.Msg.MATH_DEGREE_TO_RADIAN_TITLE = "角度";
Blockly.Msg.MATH_DEGREE_TO_RADIAN_APPEND = "转换为弧度";
Blockly.Msg.MATH_DEGREE_TO_RADIAN_TOOLTIP = "";
Blockly.Msg.ME = "我";
Blockly.Msg.MODE = "模式";

Blockly.Msg.NEW_VARIABLE = "新变数...";
Blockly.Msg.NEW_VARIABLE_TITLE = "新变量名称:";
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";  // untranslated
Blockly.Msg.POPUP_SAVE_DONE = "储存完成";  // untranslated
Blockly.Msg.PORT = "端口";  // untranslated
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "allow statements";  // untranslated
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "与：";
Blockly.Msg.PROCEDURES_CALLNORETURN_CALL = "呼叫";
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "执行使用者定义的函式 '%1'。";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP1 = "执行使用者定义的函式 '";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP2 = "'。";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "执行使用者定义的函式 '%1' 并使用它的回传值";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP1 = "执行使用者定义的函式 '";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP2 = "' 并使用它的回传值";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "与：";
Blockly.Msg.PROCEDURES_CREATE_DO = "建立 '%1'";
Blockly.Msg.PROCEDURES_CREATE_DO1 = "建立 '";
Blockly.Msg.PROCEDURES_CREATE_DO2 = "'";
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "子程序";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "函式";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "创建一个无回传值的函式。";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "回传";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "创建一个有回传值的函式。";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "警告: 此函式中有重复的参数。";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "高亮显示函数定义";
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "如果值为 真，则返回第二个值。";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "警告: 此积木仅可在定义函式时使用。";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "变数:";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "Add an input to the function.";  // untranslated
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "参数";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "Add, remove, or reorder inputs to this function.";  // untranslated
Blockly.Msg.RANGE_TITLE = "间隔（分）";  // untranslated

Blockly.Msg.REMOVE_COMMENT = "移除批注";
Blockly.Msg.RENAME_VARIABLE = "重新命名变量...";
Blockly.Msg.RENAME_VARIABLE_TITLE = "将所有 \"%1\" 变量重新命名为:";
Blockly.Msg.RENAME_VARIABLE_TITLE1 = "将所有 \"";
Blockly.Msg.RENAME_VARIABLE_TITLE2 = "\" 变量重新命名为:";
Blockly.Msg.REPLACE_TEXT1 = "取代既有的积木？";
Blockly.Msg.REPLACE_TEXT2 = "[Cancel] will merge.";  // untranslated

Blockly.Msg.SAVE_XML = "储存 XML";  // untranslated
Blockly.Msg.SAVE_FIRST = "请先储存档案，方能在IDE中开启"

Blockly.Msg.SETTING = "设定";  // untranslated

Blockly.Msg.STRING = "字符串";  // untranslated
Blockly.Msg.TERM = "终端机";  // untranslated
Blockly.Msg.TEXT = "字符串";  // untranslated
Blockly.Msg.TEXTAREA_EXPORT_LABEL = "复制代码";  // untranslated
Blockly.Msg.TEXTAREA_IMPORT_LABEL = "贴上代码";  //Blockly.Msg.STRING untranslated
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "后加入字符串";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_APPEND_TO = "在";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "将一些字符串追加到变量 '%1'。";
Blockly.Msg.TEXT_APPEND_TOOLTIP1 = "将一些字符串追加到变量 '";
Blockly.Msg.TEXT_APPEND_TOOLTIP2 = "'。";
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "转成 小写";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "转成 首字母大写";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "转成 大写";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "使用不同的大小写复制这段字符串。";
Blockly.Msg.TEXT_CHARAT_FIRST = "取第一个字符";
Blockly.Msg.TEXT_CHARAT_FROM_END = "取得 倒数第 # 个字符";
Blockly.Msg.TEXT_CHARAT_FROM_START1 = "取得第";
Blockly.Msg.TEXT_CHARAT_FROM_START2 = "字符";  // untranslated
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg.TEXT_CHARAT_INTEXT = "从字符串";
Blockly.Msg.TEXT_CHARAT_LAST = "取最后一个字符";
Blockly.Msg.TEXT_CHARAT_RANDOM = "取随机一个字符";
Blockly.Msg.TEXT_CHARAT_TAIL = "";
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "返回位于指定位置的字符。";
Blockly.Msg.TEXT_COMMENTOUT_APPENDTEXT = "批注掉";
Blockly.Msg.TEXT_COMMENTOUT_HELPURL = "";  // untranslated
Blockly.Msg.TEXT_COMMENTOUT_TOOLTIP = "";  // untranslated
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "将一个项目加入到字符串中。";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "加入";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "添加、 删除或重新排列各区块来此重新配置这个字符串积木。";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "到 倒数第 # 个字符";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "到 字符 #";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "到 最后一个字符";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "自字符串";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "取得一段字符串 自 第一个字符";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "取得一段字符串自 #";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "取得一段字符串自 #";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "返回指定的部分字符串。";
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "在字符串";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "寻找 第一个 出现的字符串";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "寻找 最后一个 出现的字符串";
Blockly.Msg.TEXT_INDEXOF_TAIL = "";  // untranslated
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "返回在第二个字符串中的第一个/最后一个匹配项目的索引值。如果未找到则返回 0。";
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 为空";
Blockly.Msg.TEXT_ISEMPTY_TITLE1 = " 为空";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "如果提供的字符串为空，则返回 真。";
Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "串接字符串";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "通过串起任意数量字符串或数字来建立一段字符串。";
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_LENGTH_TITLE = "字符串长度 %1";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "返回这串字符串的字符数（含空格） 。";
Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg.TEXT_PRINT_TITLE = "印出 %1";
Blockly.Msg.TEXT_PRINT_TITLE1 = "印出 ";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "印出指定的字符串、 数字或其他值。";
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "输入数字";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "输入字符串";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "输入 数字 并显示提示讯息";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "输入 字符串 并显示提示讯息";
Blockly.Msg.TEXT_TEXT_HELPURL = "https://en.wikipedia.org/wiki/String_(computer_science)";
Blockly.Msg.TEXT_TEXT_TOOLTIP = "字符、 单词或一行字符串。";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "消除两侧空格";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "消除左侧空格";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "消除右侧空格";
Blockly.Msg.TEXT_TRIM_TOOLTIP = "复制这段字符串的同时删除两端多余的空格。";



Blockly.Msg.VALUE = "数值";
Blockly.Msg.VARIABLE = "变数";
Blockly.Msg.VARIABLES_DEFAULT_NAME = "i";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "创立 '设定 %1'";
Blockly.Msg.VARIABLES_GET_CREATE_SET1 = "创立 '设定 ";
Blockly.Msg.VARIABLES_GET_CREATE_SET2 = "'";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg.VARIABLES_GET_TAIL = "";
Blockly.Msg.VARIABLES_GET_TITLE = "";
Blockly.Msg.VARIABLES_GET_TOOLTIP = "返回此变数的值。";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "建立 '取得 %1'";
Blockly.Msg.VARIABLES_SET_CREATE_GET1 = "建立 '取得 ";
Blockly.Msg.VARIABLES_SET_CREATE_GET2 = "'";
Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg.VARIABLES_SET_TAIL = "值";
Blockly.Msg.VARIABLES_SET_TITLE = "宣告";
Blockly.Msg.VARIABLES_SET_TOOLTIP = "设定此变量，好和输入值相等。";
Blockly.Msg.VARIABLES_TYPE_ANY = "任意";
Blockly.Msg.VARIABLES_TYPE_ARRAY = "整数数组";
Blockly.Msg.VARIABLES_TYPE_ARRAY1 = "字符串数组"
Blockly.Msg.VARIABLES_TYPE_ARRAY2 = "字符数组"
Blockly.Msg.VARIABLES_TYPE_ARRAY2D = "二维整数数组";
Blockly.Msg.VARIABLES_TYPE_BOOLEAN = "布尔值";
Blockly.Msg.VARIABLES_TYPE_BYTE = "位";
Blockly.Msg.VARIABLES_TYPE_CHAR = "字符";
Blockly.Msg.VARIABLES_TYPE_COLOUR = "颜色";
Blockly.Msg.VARIABLES_TYPE_DOUBLE = "倍精度浮点数";
Blockly.Msg.VARIABLES_TYPE_FLOAT = "浮点数";
Blockly.Msg.VARIABLES_TYPE_LONG = "长整数";
Blockly.Msg.VARIABLES_TYPE_NUMBER = "整数";
Blockly.Msg.VARIABLES_TYPE_STRING = "字符串对象";
Blockly.Msg.VARIABLES_TYPE_UNSIGNED_INT = "正整数";
Blockly.Msg.VARIABLES_TYPE_UNSIGNED_LONG = "正长整数";
Blockly.Msg.VARIABLES_TYPE_VOLATILE_INT = "可变性整数";
Blockly.Msg.VARIABLES_TYPE_WORD = "存取字符";

Blockly.Msg.VARIABLES_TYPE_VOID = "空白 (void)";
Blockly.Msg.VARIABLES_TYPE_ARRAY = "数组 (array)";
Blockly.Msg.VARIABLES_TYPE_BOOLEAN = "布尔 (boolean)";
Blockly.Msg.VARIABLES_TYPE_BYTE = "字节 (byte)";
Blockly.Msg.VARIABLES_TYPE_CHAR = "字符 (char)";
Blockly.Msg.VARIABLES_TYPE_CHAR1 = "字符 (char*)";
Blockly.Msg.VARIABLES_TYPE_CHAR2 = "字符 (const char*)";
Blockly.Msg.VARIABLES_TYPE_DOUBLE = "倍精度浮点数 (double)";
Blockly.Msg.VARIABLES_TYPE_FLOAT = "浮点数 (float)";
Blockly.Msg.VARIABLES_TYPE_INT = "整数 (int)";
Blockly.Msg.VARIABLES_TYPE_LONG = "长整数 (long)";
Blockly.Msg.VARIABLES_TYPE_SHORT = "短整数 (short)";
Blockly.Msg.VARIABLES_TYPE_SIZET = "字节大小 (size_t)";
Blockly.Msg.VARIABLES_TYPE_STRING = "字符串 (String)";
Blockly.Msg.VARIABLES_TYPE_UNSIGNEDCHAR = "无号字符 (unsigned char)";
Blockly.Msg.VARIABLES_TYPE_UNSIGNEDINT = "无号整数 (unsigned int)";
Blockly.Msg.VARIABLES_TYPE_UNSIGNEDLONG = "无号长整数 (unsigned long)";
Blockly.Msg.VARIABLES_TYPE_UNSIGNEDWORD = "无号数 (word)";

	
Blockly.Msg.XML = "XML";
Blockly.Msg.YELLOW = "黄";
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.VARIABLES_SET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.VARIABLES_GET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_CALLRETURN_CALL = Blockly.Msg.PROCEDURES_CALLNORETURN_CALL;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;

Blockly.Msg.BUTTON_UPLOAD = "刻录";
Blockly.Msg.BUTTON_LAUNCH_IDE = "启动 Arduino IDE";
Blockly.Msg.BUTTON_BOARD_SETTINGS = "开发板设定";
Blockly.Msg.TEXT_UPLOADER_STATUS = "刻录状态";
Blockly.Msg.TEXT_BOARD = "开发板";
Blockly.Msg.TEXT_COM_PORT = "端口";
Blockly.Msg.DROPDOWN_SCANNING = "扫描端口当中...";




Blockly.Msg.VARIABLES_CHANGETYPE_TOINT = "整数(int)";
Blockly.Msg.VARIABLES_CHANGETYPE_TODOUBLE = "倍精度浮点数(double)";
Blockly.Msg.VARIABLES_CHANGETYPE_TOFLOAT = "浮点数(float)";
Blockly.Msg.VARIABLES_CHANGETYPE_TOLOWERCASE = "小写字符串";
Blockly.Msg.VARIABLES_CHANGETYPE_TOUPPERCASE = "大写字符串";
Blockly.Msg.VARIABLES_CHANGETYPE_TRIM = "删除两侧空格";
Blockly.Msg.VARIABLES_CHANGETYPE_CSTR = "NULL结尾字符串(c_str)";
Blockly.Msg.VARIABLES_CHANGETYPE_LENGTH = "字符串长度";

Blockly.Msg.VARIABLES_TYPE_POSITION_GLOBAL = "全局";
Blockly.Msg.VARIABLES_TYPE_POSITION_LOCAL = "区域";

Blockly.Msg.VARIABLES_GETNUMBER_RANDOM = "随机";
Blockly.Msg.VARIABLES_GETNUMBER_RANDOMSEED = "随机种子";

Blockly.Msg.MATH_RADIAN_TO_DEGREE_TITLE = "弧度";
Blockly.Msg.MATH_RADIAN_TO_DEGREE_APPEND = "转换为角度";
Blockly.Msg.MATH_RADIAN_TO_DEGREE_TOOLTIP = "";

Blockly.Msg.LAUNCHSERIAL = "PuTTY串行端口监视窗口"
Blockly.Msg.DOWNLOAD = "下载积木图片"
Blockly.Msg.PREVIOUSSTEP = "还原"
Blockly.Msg.NEXTSTEP = "重做"

Blockly.Msg.CATEGORY_CAST = "转换";
Blockly.Msg.SCROLLPLUGIN = "切换边缘卷动";
Blockly.Msg.SCROLLPLUGIN_TRUE = "启用边缘卷动";
Blockly.Msg.SCROLLPLUGIN_FALSE = "停用边缘卷动";
Blockly.Msg.HIGHLIGHTPLUGIN = "启用醒目范围";
Blockly.Msg.BACKPACKPLUGIN = '启用背包区域';
Blockly.Msg.DELETENULL = '清除%1个空子积木';
Blockly.Msg.SEARCHNULL = '寻找下个空子积木';

Blockly.Msg['COPY_ALL_TO_BACKPACK'] = '复制所有积木到背包';
Blockly.Msg['COPY_TO_BACKPACK'] = '复制到背包';
Blockly.Msg['EMPTY_BACKPACK'] = '清空背包';
Blockly.Msg['PASTE_ALL_FROM_BACKPACK'] = '从背包贴上所有积木';
Blockly.Msg['REMOVE_FROM_BACKPACK'] = '从背包移除所有积木';

Blockly.Msg["CONTROLS_SWITCH"] = "条件判断";
Blockly.Msg["CONTROLS_SWITCH_VALUE"] = "比对值";
Blockly.Msg["CONTROLS_SWITCH_CASE"] = "条件";
Blockly.Msg["CONTROLS_SWITCH_DEFAULT"] = "预设";
Blockly.Msg["CONTROLS_SWITCH_TO"] = "陈述";
Blockly.Msg["CONTROLS_SWITCH_MSG"] = "符合";
Blockly.Msg["CONTROLS_SWITCH_MSG_CASE"] = "符合";
Blockly.Msg["CONTROLS_SWITCH_MSG_DEFAULT"] = "预设陈述";

Blockly.Msg.TOOLBOX_DISPLAY = "工具箱目录";
Blockly.Msg.TOOLBOX_SHOW = "显示工具箱";
Blockly.Msg.TOOLBOX_HIDE = "隐藏工具箱";
Blockly.Msg.LOADLASTBLOCKS = "还原备份积木";
Blockly.Msg.WINDOW_CLOSE_MESSAGE = "请确认已储存积木档后再离开？";

Blockly.Msg.VARIABLES_TO_STRING_BIN = "字符串(二进制)";
Blockly.Msg.VARIABLES_TO_STRING_OCT = "字符串(八进制)";
Blockly.Msg.VARIABLES_TO_STRING_DEC = "字符串(十进制)";
Blockly.Msg.VARIABLES_TO_STRING_HEX = "字符串(十六进制)";
Blockly.Msg.VARIABLES_TO_REPLACE = "取代";

Blockly.Msg.RELOAD_TITLE = "你要重启窗口加载新设定吗？";
Blockly.Msg.COM_TITLE = "请先选择串行端口！";
Blockly.Msg.BUTTON_OPEN = "开启";
Blockly.Msg.BUTTON_CLOSE = "关闭";
Blockly.Msg.BUTTON_CLEAR = "清除";
Blockly.Msg.BUTTON_SURE = "确认";
Blockly.Msg.BUTTON_RESET = "你确定要重设工作区？";
Blockly.Msg.BUTTON_SERIAL_OPEN = "开启PUTTY";
Blockly.Msg.BUTTON_SERIAL_TITLE = "串行端口监视窗口";
Blockly.Msg.BUTTON_UPLOAD_TITLE = "刻录韧体";
Blockly.Msg.BUTTON_UPLOAD_STATE = "刻录状态";
Blockly.Msg.BUTTON_UPLOAD_START = "正在上传韧体...";
Blockly.Msg.BUTTON_UPLOAD_CODE = "程序代码";
Blockly.Msg.BUTTON_CLEARAREAS_TITLE = "你确定要清除自定义积木区内容？";

Blockly.Msg["VARIABLES_DEFINE"] = "宣告常数";
Blockly.Msg["BUTTON_CUSTOMBLOCKS"] = "新增自定义积木";
Blockly.Msg["CUSTOMBLOCKS_TITLE"] = "请输入自定义积木连结网址。\n目录中包含档案 blocks.js, javascript.js, toolbox.xml, en.js, zh-hant.js\n\n若要永久加入自定义积木连结，可开启档案\\package.nw\\customBlocks\\customblocks.js将链接手动加入清单";
Blockly.Msg["BUTTON_COPYCODE_SUCCESS"] = "复制程序代码到剪贴簿成功！";
Blockly.Msg["MYBACKPACK_TITLE"] = "暂存积木";
Blockly.Msg["MSG_TOOLBOX"] = "工具箱";
Blockly.Msg["MSG_XML"] = "积木结构";
Blockly.Msg["MSG_CODE"] = "程序代码";
Blockly.Msg["BUTTON_RUN"] = "执行程序";
Blockly.Msg["BUTTON_ADDBLOCKS"] = "汇入你的自定义积木";
Blockly.Msg["BUTTON_CODE"] = "显示/隐藏 程序代码区块";
Blockly.Msg["BUTTON_DEVELOPERTOOL"] = "显示/隐藏 自定义积木区块";
Blockly.Msg["BUTTON_RESET"] = "重设工作区";
Blockly.Msg["BUTTON_EXPORT_BLOCKS"] = "汇出你的自定义积木档案";
Blockly.Msg["BUTTON_OPEN_XML"] = "开启积木档汇入工作区";
Blockly.Msg["BUTTON_SAVE_INO"] = "汇出XML与INO檔";
Blockly.Msg["BUTTON_SAVE_XML"] = "储存积木档";
Blockly.Msg["BUTTON_SAVE_HTML"] = "汇出网页档";
Blockly.Msg["BUTTON_TOOLBOX"] = "显示/隐藏 工具箱目录";
Blockly.Msg["BUTTON_ADDREMOTEBLOCKS"] = "新增远程自定义积木";
Blockly.Msg["BUTTON_ADDEXTENSIONBLOCKS"] = "新增内建扩充自定义积木";
Blockly.Msg["BUTTON_TOOL"] = "开启积木开发工具";
Blockly.Msg["BUTTON_WEBSERIAL"] = "网页串行端口监视窗口";
Blockly.Msg["BUTTON_UPLOADCODE"] = "上传 HEX 檔至 nano/uno/pro/pro-mini";
Blockly.Msg["MSG_WEBSERIAL"] = "网页串行端口监视窗口";
Blockly.Msg["LANG-SELECTOR"] = "选择语言";
Blockly.Msg["BUTTON_COPYCODE"] = "复制程序代码到剪贴簿";
Blockly.Msg["TEXT_UPLOADER_STATUS"] = "程序代码&nbsp;&nbsp;";
Blockly.Msg["TEXT_UPDATEDEFINITION"] = "积木定义&nbsp;&nbsp;";
Blockly.Msg["TEXT_UPDATEGENERATE"] = "程序代码产出&nbsp;&nbsp;";
Blockly.Msg["TEXT_UPDATECATEGORY"] = "积木目录&nbsp;&nbsp;";
Blockly.Msg["TEXT_UPDATEMESSAGE"] = "语系变数&nbsp;&nbsp;";
Blockly.Msg["INITIAL_SETUP"] = "初始化";
Blockly.Msg["INITIAL_LOOP"] = "循环";
Blockly.Msg["LANGUAGE_EN"] = "英文";
Blockly.Msg["LANGUAGE_CHT"] = "中文";
Blockly.Msg["BAUDRATE_TITLE"] = "串行端口鲍率 : ";
Blockly.Msg["CLOSEPORT_TITLE"] = "关闭串行端口";
Blockly.Msg["REQUESTPORT_TITLE"] = "选择串行端口";
Blockly.Msg["SENDSTRING_TITLE"] = "传送文字";
Blockly.Msg["CLEARSTATUS_TITLE"] = "清除讯息";
Blockly.Msg["MSG_WEBBLUETOOTH"] = "网页蓝芽监视窗口";
Blockly.Msg["BUTTON_WEBBLUETOOTH"] = "网页蓝芽监视窗口";
Blockly.Msg["BLUETOOTH_DISCONNECT_DEVICE"] = "中断蓝芽设备";
Blockly.Msg["BLUETOOTH_REQUEST_DEVICE"] = "选择蓝芽设备";
Blockly.Msg["BLUETOOTH_SENDSTRING"] = "传送文字";
Blockly.Msg["BLUETOOTH_CLEARTEXT"] = "清除讯息";
Blockly.Msg["UUID_SERVICE_TITLE"] = "Service UUID";
Blockly.Msg["UUID_TX_TITLE"] = "TX UUID";
Blockly.Msg["UUID_RX_TITLE"] = "RX UUID";

Blockly.Msg["MYPICKPLACEBLOCK_PICKPLACE_ENABLED"] = "启用 选取/置放 积木";
Blockly.Msg["MYPICKPLACEBLOCK_PICKPLACE_DISABLED"] = "停用 选取/置放 积木";
Blockly.Msg["MYPICKPLACEBLOCK_CLICK_TO_PICK"] = "选取来源积木";
Blockly.Msg["MYPICKPLACEBLOCK_CLICK_TO_PLACE_NEXT"] = "置放来源积木 (目标积木之下)";
Blockly.Msg["MYPICKPLACEBLOCK_CLICK_TO_PLACE_PREVIOUS"] = "置放来源积木 (目标积木之上)";
Blockly.Msg["MYPICKPLACEBLOCK_CLICK_TO_PLACE_INPUT"] = "置放来源积木 [子输入 #]";
Blockly.Msg["MYPICKPLACEBLOCK_CLICK_TO_PLACE_INPUT_NAME"] = ["","","","","","","","","",""];

Blockly.Msg["DISABLED_TOPCHECK"] = "停用置顶积木检查";
Blockly.Msg["ENABLED_TOPCHECK"] = "启用置顶积木检查";

Blockly.Msg["INSERTBLOCKS_WORKSPACE_BLOCK_EXPORT"] = "汇出单一积木至档案";
Blockly.Msg["INSERTBLOCKS_WORKSPACE_BLOCK_INSERT"] = "开启单一积木档案插入至工作区";

Blockly.Msg["MSG_DISPLAY"] = "程序执行窗口";
Blockly.Msg["BUTTON_START"] = "执行程序";
Blockly.Msg["BUTTON_STOP"] = "停止程序";

Blockly.Msg["MSG_NEWLINE"] = "换行";

Blockly.Msg["BUTTON_FULLSCREEN"] = "全萤幕执行程序";
Blockly.Msg["BUTTON_BOTTOM"] = "视窗 置底/还原";

//20220327
Blockly.Msg["CATVARIABLES"] = "变数";
Blockly.Msg["CATFUNCTIONS"] = "流程";
Blockly.Msg["CATLOGIC"] = "逻辑";
Blockly.Msg["CATLOOPS"] = "循环";
Blockly.Msg["CATMATH"] = "数值";
Blockly.Msg["CATTEXT"] = "文字";
Blockly.Msg["CATLISTS"] = "列表";
Blockly.Msg["CATCOLOUR"] = "颜色";

Blockly.Msg["MATH_HUE"] = "230";
Blockly.Msg["LOOPS_HUE"] = "120";
Blockly.Msg["LISTS_HUE"] = "260";
Blockly.Msg["LOGIC_HUE"] = "210";
Blockly.Msg["VARIABLES_HUE"] = "330";
Blockly.Msg["TEXTS_HUE"] = "160";
Blockly.Msg["PROCEDURES_HUE"] = "290";
Blockly.Msg["COLOUR_HUE"] = "20";
Blockly.Msg["VARIABLES_DYNAMIC_HUE"] = "310";

Blockly.Msg["INSERTBLOCKS_WORKSPACE_BLOCK_EXPORT"] = "汇出选择的积木储存本机档案";
Blockly.Msg["INSERTBLOCKS_WORKSPACE_BLOCK_INSERT"] = "从本机档案插入积木至工作区";

Blockly.Msg["MYPICKPLACEBLOCK_PICKPLACE_ENABLED"] = "启用 挑选/置放 积木";
Blockly.Msg["MYPICKPLACEBLOCK_PICKPLACE_DISABLED"] = "停用 挑选/置放 积木";
Blockly.Msg["MYPICKPLACEBLOCK_CLICK_TO_PICK"] = "挑选积木";
Blockly.Msg["MYPICKPLACEBLOCK_CLICK_TO_PLACE_NEXT"] = "置放积木 (下方)";
Blockly.Msg["MYPICKPLACEBLOCK_CLICK_TO_PLACE_PREVIOUS"] = "置放积木 (上方)";
Blockly.Msg["MYPICKPLACEBLOCK_CLICK_TO_PLACE_INPUT"] = "置放积木 [输入: #]";

Blockly.Msg["VARIABLES_GLOBAL"] = "全域";
Blockly.Msg["VARIABLES_LOCAL"] = "区域";
Blockly.Msg["VARIABLES_CONST"] = "常数";

Blockly.Msg["BUTTON_COLLABORATION"] = "MQTT协同编辑";
Blockly.Msg["COLLABORATION_BROKER_TITLE"] = "代理伺服器";
Blockly.Msg["COLLABORATION_TOPIC_TITLE"] = "主题";
Blockly.Msg["COLLABORATION_USERID_TITLE"] = "使用者帐号";
Blockly.Msg["COLLABORATION_PASSWORD_TITLE"] = "密码";
Blockly.Msg.BUTTON_LINK = "连线";
Blockly.Msg["MSG_COLLABORATION"] = "MQTT协同编辑";
Blockly.Msg["COLLABORATION_TIP_TITLE"] = "MQTT.js须使用WSS通讯协定";

Blockly.Msg["BUTTON_WEBMQTT"] = "网页MQTT";











Blockly.Msg["ADD_COMMENT"] = "添加注释";
Blockly.Msg["CANNOT_DELETE_VARIABLE_PROCEDURE"] = "不能删除变量“%1”，因为它是函数“%2”定义的一部分";
Blockly.Msg["CHANGE_VALUE_TITLE"] = "更改值：";
Blockly.Msg["CLEAN_UP"] = "整理块";
Blockly.Msg["COLLAPSED_WARNINGS_WARNING"] = "已收起的信息块内包含警告。";
Blockly.Msg["COLLAPSE_ALL"] = "折叠块";
Blockly.Msg["COLLAPSE_BLOCK"] = "折叠块";
Blockly.Msg["COLOUR_BLEND_COLOUR1"] = "颜色1";
Blockly.Msg["COLOUR_BLEND_COLOUR2"] = "颜色2";
Blockly.Msg["COLOUR_BLEND_HELPURL"] = "https://meyerweb.com/eric/tools/color-blend/#:::rgbp";  // untranslated
Blockly.Msg["COLOUR_BLEND_RATIO"] = "比例";
Blockly.Msg["COLOUR_BLEND_TITLE"] = "混合";
Blockly.Msg["COLOUR_BLEND_TOOLTIP"] = "把两种颜色以一个给定的比例(0.0-1.0)进行混合。";
Blockly.Msg["COLOUR_PICKER_HELPURL"] = "https://zh.wikipedia.org/wiki/颜色";
Blockly.Msg["COLOUR_PICKER_TOOLTIP"] = "从调色板中选择一种颜色。";
Blockly.Msg["COLOUR_RANDOM_HELPURL"] = "http://randomcolour.com";  // untranslated
Blockly.Msg["COLOUR_RANDOM_TITLE"] = "随机颜色";
Blockly.Msg["COLOUR_RANDOM_TOOLTIP"] = "随机选择一种颜色。";
Blockly.Msg["COLOUR_RGB_BLUE"] = "蓝色";
Blockly.Msg["COLOUR_RGB_GREEN"] = "绿色";
Blockly.Msg["COLOUR_RGB_HELPURL"] = "https://www.december.com/html/spec/colorpercompact.html";  // untranslated
Blockly.Msg["COLOUR_RGB_RED"] = "红色";
Blockly.Msg["COLOUR_RGB_TITLE"] = "颜色";
Blockly.Msg["COLOUR_RGB_TOOLTIP"] = "通过指定红色、绿色和蓝色的量创建一种颜色。所有的值必须在0和100之间。";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK"] = "跳出循环";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE"] = "继续下一轮循环";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK"] = "跳出包含它的循环。";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE"] = "跳过本轮循环的剩余部分，并继进行续下一轮循环。";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_WARNING"] = "警告：这个块只能在循环内使用。";
Blockly.Msg["CONTROLS_FOREACH_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
Blockly.Msg["CONTROLS_FOREACH_TITLE"] = "遍历列表 %2 里的每一项 %1";
Blockly.Msg["CONTROLS_FOREACH_TOOLTIP"] = "遍历列表中的每一项，将变量“%1”设为所选项，并执行一些语句。";
Blockly.Msg["CONTROLS_FOR_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg["CONTROLS_FOR_TITLE"] = "变量 %1 从 %2 数到 %3 每次增加 %4";
Blockly.Msg["CONTROLS_FOR_TOOLTIP"] = "用变量%1记录从开始数值到终止数值之间的数值，数值按指定间隔增加，并执行指定的块。";
Blockly.Msg["CONTROLS_IF_ELSEIF_TOOLTIP"] = "在这个if语句块中增加一个条件。";
Blockly.Msg["CONTROLS_IF_ELSE_TOOLTIP"] = "在这个if语句块中添加一个最终的，包括所有其余情况的条件。";
Blockly.Msg["CONTROLS_IF_HELPURL"] = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg["CONTROLS_IF_IF_TOOLTIP"] = "增加、删除或重新排列各节来重新配置这个if语句块。";
Blockly.Msg["CONTROLS_IF_MSG_ELSE"] = "否则";
Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"] = "否则如果";
Blockly.Msg["CONTROLS_IF_MSG_IF"] = "如果";
Blockly.Msg["CONTROLS_IF_TOOLTIP_1"] = "如果值为真，执行一些语句。";
Blockly.Msg["CONTROLS_IF_TOOLTIP_2"] = "如果值为真，则执行第一块语句。否则，则执行第二块语句。";
Blockly.Msg["CONTROLS_IF_TOOLTIP_3"] = "如果第一个值为真，则执行第一块的语句。否则，如果第二个值为真，则执行第二块的语句。";
Blockly.Msg["CONTROLS_IF_TOOLTIP_4"] = "如果第一个值为真，则执行第一块对语句。否则，如果第二个值为真，则执行语句的第二块。如果没有值为真，则执行最后一块的语句。";
Blockly.Msg["CONTROLS_REPEAT_HELPURL"] = "https://zh.wikipedia.org/wiki/For循环";
Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"] = "执行";
Blockly.Msg["CONTROLS_REPEAT_TITLE"] = "重复 %1 次";
Blockly.Msg["CONTROLS_REPEAT_TOOLTIP"] = "多次执行一些语句。";
Blockly.Msg["CONTROLS_WHILEUNTIL_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_UNTIL"] = "重复直到条件满足";
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_WHILE"] = "当条件满足时重复";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL"] = "只要值为假，就一直循环执行一些语句。";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_WHILE"] = "只要值为真，就一直循环执行一些语句。";
Blockly.Msg["DELETE_ALL_BLOCKS"] = "删除所有 %1 个块吗？";
Blockly.Msg["DELETE_BLOCK"] = "删除块";
Blockly.Msg["DELETE_VARIABLE"] = "删除变量“%1”";
Blockly.Msg["DELETE_VARIABLE_CONFIRMATION"] = "要删除对变量“%2”的%1个引用吗？";
Blockly.Msg["DELETE_X_BLOCKS"] = "删除 %1 个块";
Blockly.Msg["DIALOG_CANCEL"] = "取消";
Blockly.Msg["DIALOG_OK"] = "确认";
Blockly.Msg["DISABLE_BLOCK"] = "禁用块";
Blockly.Msg["DUPLICATE_BLOCK"] = "复制";
Blockly.Msg["DUPLICATE_COMMENT"] = "复制注释";
Blockly.Msg["ENABLE_BLOCK"] = "启用块";
Blockly.Msg["EXPAND_ALL"] = "展开块";
Blockly.Msg["EXPAND_BLOCK"] = "展开块";
Blockly.Msg["EXTERNAL_INPUTS"] = "外部输入";
Blockly.Msg["HELP"] = "帮助";
Blockly.Msg["INLINE_INPUTS"] = "单行输入";
Blockly.Msg["LISTS_CREATE_EMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
Blockly.Msg["LISTS_CREATE_EMPTY_TITLE"] = "创建空列表";
Blockly.Msg["LISTS_CREATE_EMPTY_TOOLTIP"] = "返回一个列表，长度为 0，不包含任何数据记录";
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TITLE_ADD"] = "列表";
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TOOLTIP"] = "增加、删除或重新排列各部分以此重新配置这个列表块。";
Blockly.Msg["LISTS_CREATE_WITH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg["LISTS_CREATE_WITH_INPUT_WITH"] = "创建列表";
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TOOLTIP"] = "将一个项添加到列表中。";
Blockly.Msg["LISTS_CREATE_WITH_TOOLTIP"] = "建立一个具有任意数量项目的列表。";
Blockly.Msg["LISTS_GET_INDEX_FIRST"] = "第一项";
Blockly.Msg["LISTS_GET_INDEX_FROM_END"] = "倒数第#项";
Blockly.Msg["LISTS_GET_INDEX_FROM_START"] = "#";
Blockly.Msg["LISTS_GET_INDEX_GET"] = "取得";
Blockly.Msg["LISTS_GET_INDEX_GET_REMOVE"] = "取得并移除";
Blockly.Msg["LISTS_GET_INDEX_LAST"] = "最后一项";
Blockly.Msg["LISTS_GET_INDEX_RANDOM"] = "随机的一项";
Blockly.Msg["LISTS_GET_INDEX_REMOVE"] = "移除";
Blockly.Msg["LISTS_GET_INDEX_TAIL"] = "";  // untranslated
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_FIRST"] = "返回列表中的第一项。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_FROM"] = "返回在列表中的指定位置的项。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_LAST"] = "返回列表中的最后一项。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_RANDOM"] = "返回列表中的随机一项。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST"] = "移除并返回列表中的第一项。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM"] = "移除并返回列表中的指定位置的项。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST"] = "移除并返回列表中的最后一项。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM"] = "移除并返回列表中的随机一项。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST"] = "移除列表中的第一项";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM"] = "移除在列表中的指定位置的项。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST"] = "移除列表中的最后一项";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM"] = "删除列表中的随机一项。";
Blockly.Msg["LISTS_GET_SUBLIST_END_FROM_END"] = "到倒数第#项";
Blockly.Msg["LISTS_GET_SUBLIST_END_FROM_START"] = "到第#项";
Blockly.Msg["LISTS_GET_SUBLIST_END_LAST"] = "到最后一项";
Blockly.Msg["LISTS_GET_SUBLIST_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
Blockly.Msg["LISTS_GET_SUBLIST_START_FIRST"] = "获取子列表，从第一项";
Blockly.Msg["LISTS_GET_SUBLIST_START_FROM_END"] = "获取子列表，从倒数第#项";
Blockly.Msg["LISTS_GET_SUBLIST_START_FROM_START"] = "获取子列表，从第#项";
Blockly.Msg["LISTS_GET_SUBLIST_TAIL"] = "";  // untranslated
Blockly.Msg["LISTS_GET_SUBLIST_TOOLTIP"] = "复制列表中指定的部分。";
Blockly.Msg["LISTS_INDEX_FROM_END_TOOLTIP"] = "%1是最后一项。";
Blockly.Msg["LISTS_INDEX_FROM_START_TOOLTIP"] = "%1是第一项。";
Blockly.Msg["LISTS_INDEX_OF_FIRST"] = "寻找第一次出现的项";
Blockly.Msg["LISTS_INDEX_OF_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
Blockly.Msg["LISTS_INDEX_OF_LAST"] = "寻找最后一次出现的项";
Blockly.Msg["LISTS_INDEX_OF_TOOLTIP"] = "返回在列表中的第一/最后一个匹配项的索引值。如果找不到项目则返回%1。";
Blockly.Msg["LISTS_INLIST"] = "在列表中";
Blockly.Msg["LISTS_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
Blockly.Msg["LISTS_ISEMPTY_TITLE"] = "%1是空的";
Blockly.Msg["LISTS_ISEMPTY_TOOLTIP"] = "如果改列表为空，则返回真。";
Blockly.Msg["LISTS_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg["LISTS_LENGTH_TITLE"] = "%1的长度";
Blockly.Msg["LISTS_LENGTH_TOOLTIP"] = "返回列表的长度。";
Blockly.Msg["LISTS_REPEAT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg["LISTS_REPEAT_TITLE"] = "建立列表使用项 %1 重复 %2 次";
Blockly.Msg["LISTS_REPEAT_TOOLTIP"] = "建立包含指定重复次数的值的列表。";
Blockly.Msg["LISTS_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#reversing-a-list";  // untranslated
Blockly.Msg["LISTS_REVERSE_MESSAGE0"] = "倒转%1";
Blockly.Msg["LISTS_REVERSE_TOOLTIP"] = "倒转一个列表，返回副本。";
Blockly.Msg["LISTS_SET_INDEX_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg["LISTS_SET_INDEX_INPUT_TO"] = "值为";
Blockly.Msg["LISTS_SET_INDEX_INSERT"] = "插入在";
Blockly.Msg["LISTS_SET_INDEX_SET"] = "设置";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST"] = "在列表的起始处添加该项。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_FROM"] = "在列表中指定位置插入项。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_LAST"] = "在列表的末尾处添加该项。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM"] = "在列表的随机位置插入该项。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_FIRST"] = "设置列表中的第一项。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_FROM"] = "设置在列表中指定位置的项。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_LAST"] = "设置列表中的最后一项。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_RANDOM"] = "设置列表中的随机一项。";
Blockly.Msg["LISTS_SORT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";  // untranslated
Blockly.Msg["LISTS_SORT_ORDER_ASCENDING"] = "升序";
Blockly.Msg["LISTS_SORT_ORDER_DESCENDING"] = "降序";
Blockly.Msg["LISTS_SORT_TITLE"] = "排序%1 %2 %3";
Blockly.Msg["LISTS_SORT_TOOLTIP"] = "排序一个列表，返回副本。";
Blockly.Msg["LISTS_SORT_TYPE_IGNORECASE"] = "按字母（忽略大小写）";
Blockly.Msg["LISTS_SORT_TYPE_NUMERIC"] = "按数字";
Blockly.Msg["LISTS_SORT_TYPE_TEXT"] = "按字母";
Blockly.Msg["LISTS_SPLIT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";  // untranslated
Blockly.Msg["LISTS_SPLIT_LIST_FROM_TEXT"] = "从文本制作列表";
Blockly.Msg["LISTS_SPLIT_TEXT_FROM_LIST"] = "将列表合并为文本";
Blockly.Msg["LISTS_SPLIT_TOOLTIP_JOIN"] = "加入文本列表至一个文本，由分隔符分隔。";
Blockly.Msg["LISTS_SPLIT_TOOLTIP_SPLIT"] = "将文本按指定的分隔符拆分为文本组成的列表。";
Blockly.Msg["LISTS_SPLIT_WITH_DELIMITER"] = "分隔符：";
Blockly.Msg["LOGIC_BOOLEAN_FALSE"] = "false";
Blockly.Msg["LOGIC_BOOLEAN_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg["LOGIC_BOOLEAN_TOOLTIP"] = "返回 true 或 false。";
Blockly.Msg["LOGIC_BOOLEAN_TRUE"] = "true";
Blockly.Msg["LOGIC_COMPARE_HELPURL"] = "https://zh.wikipedia.org/wiki/不等";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_EQ"] = "如果两个输入结果相等，则返回真。";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GT"] = "如果第一个输入结果比第二个大，则返回真。";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GTE"] = "如果第一个输入结果大于或等于第二个输入结果，则返回真。";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LT"] = "如果第一个输入结果比第二个小，则返回真。";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LTE"] = "如果第一个输入结果小于或等于第二个输入结果，则返回真。";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_NEQ"] = "如果两个输入结果不相等，则返回真。";
Blockly.Msg["LOGIC_NEGATE_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
Blockly.Msg["LOGIC_NEGATE_TITLE"] = "非 %1";
Blockly.Msg["LOGIC_NEGATE_TOOLTIP"] = "如果输入结果为false，则返回true；如果输入结果为true，则返回false。";
Blockly.Msg["LOGIC_NULL"] = "空";
Blockly.Msg["LOGIC_NULL_HELPURL"] = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
Blockly.Msg["LOGIC_NULL_TOOLTIP"] = "返回空值。";
Blockly.Msg["LOGIC_OPERATION_AND"] = "并且";
Blockly.Msg["LOGIC_OPERATION_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg["LOGIC_OPERATION_OR"] = "或";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_AND"] = "如果两个输入结果都为真，则返回真。";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_OR"] = "如果至少有一个输入结果为真，则返回真。";
Blockly.Msg["LOGIC_TERNARY_CONDITION"] = "断言";
Blockly.Msg["LOGIC_TERNARY_HELPURL"] = "https://zh.wikipedia.org/wiki/条件运算符";
Blockly.Msg["LOGIC_TERNARY_IF_FALSE"] = "如果为 false";
Blockly.Msg["LOGIC_TERNARY_IF_TRUE"] = "如果为 true";
Blockly.Msg["LOGIC_TERNARY_TOOLTIP"] = "检查“断言”里的条件语句。如果条件为真，则返回“如果为真”的值，否则，则返回“如果为假”的值。";
Blockly.Msg["MATH_ADDITION_SYMBOL"] = "+";  // untranslated
Blockly.Msg["MATH_ARITHMETIC_HELPURL"] = "https://zh.wikipedia.org/wiki/算术";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_ADD"] = "返回两个数值的和。";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_DIVIDE"] = "返回两个数值的商。";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MINUS"] = "返回两个数值的差。";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MULTIPLY"] = "返回两个数值的乘积。";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_POWER"] = "返回以第一个数值为底数，以第二个数值为幂的结果。";
Blockly.Msg["MATH_ATAN2_HELPURL"] = "https://zh.wikipedia.org/wiki/反正切2";
Blockly.Msg["MATH_ATAN2_TITLE"] = "点(x:%1,y:%2)的方位角";
Blockly.Msg["MATH_ATAN2_TOOLTIP"] = "返回点（X，Y）的反正切值，范围为-180到180度。";
Blockly.Msg["MATH_CHANGE_HELPURL"] = "https://zh.wikipedia.org/wiki/加法";
Blockly.Msg["MATH_CHANGE_TITLE"] = "将 %1 增加 %2";
Blockly.Msg["MATH_CHANGE_TOOLTIP"] = "为变量“%1”增加一个数值。";
Blockly.Msg["MATH_CONSTANT_HELPURL"] = "https://zh.wikipedia.org/wiki/数学常数";
Blockly.Msg["MATH_CONSTANT_TOOLTIP"] = "返回一个常见常量：π (3.141…)、e (2.718…)、φ (1.618…)、根号2 (1.414…)、根号二分之一 (0.707…)或∞ (无穷大)。";
Blockly.Msg["MATH_CONSTRAIN_HELPURL"] = "https://en.wikipedia.org/wiki/Clamping_(graphics)";  // untranslated
Blockly.Msg["MATH_CONSTRAIN_TITLE"] = "将 %1 限制在 最低 %2 到最高 %3 之间";
Blockly.Msg["MATH_CONSTRAIN_TOOLTIP"] = "将一个数值限制在两个指定的数值范围（含边界）之间。";
Blockly.Msg["MATH_DIVISION_SYMBOL"] = "÷";  // untranslated
Blockly.Msg["MATH_IS_DIVISIBLE_BY"] = "可被整除";
Blockly.Msg["MATH_IS_EVEN"] = "是偶数";
Blockly.Msg["MATH_IS_NEGATIVE"] = "是负数";
Blockly.Msg["MATH_IS_ODD"] = "是奇数";
Blockly.Msg["MATH_IS_POSITIVE"] = "是正数";
Blockly.Msg["MATH_IS_PRIME"] = "是质数";
Blockly.Msg["MATH_IS_TOOLTIP"] = "检查一个数值是否是偶数、奇数、质数、自然数、正数、负数或者是否能被某数整除。返回真或假。";
Blockly.Msg["MATH_IS_WHOLE"] = "是整数";
Blockly.Msg["MATH_MODULO_HELPURL"] = "https://zh.wikipedia.org/wiki/模除";
Blockly.Msg["MATH_MODULO_TITLE"] = "取 %1 ÷ %2 的余数";
Blockly.Msg["MATH_MODULO_TOOLTIP"] = "返回这两个数字相除后的余数。";
Blockly.Msg["MATH_MULTIPLICATION_SYMBOL"] = "×";  // untranslated
Blockly.Msg["MATH_NUMBER_HELPURL"] = "https://zh.wikipedia.org/wiki/数";
Blockly.Msg["MATH_NUMBER_TOOLTIP"] = "一个数值。";
Blockly.Msg["MATH_ONLIST_HELPURL"] = "";  // untranslated
Blockly.Msg["MATH_ONLIST_OPERATOR_AVERAGE"] = "列表平均值";
Blockly.Msg["MATH_ONLIST_OPERATOR_MAX"] = "列表最大值";
Blockly.Msg["MATH_ONLIST_OPERATOR_MEDIAN"] = "列表中位数";
Blockly.Msg["MATH_ONLIST_OPERATOR_MIN"] = "列表最小值";
Blockly.Msg["MATH_ONLIST_OPERATOR_MODE"] = "列表中的众数";
Blockly.Msg["MATH_ONLIST_OPERATOR_RANDOM"] = "列表中的随机一项";
Blockly.Msg["MATH_ONLIST_OPERATOR_STD_DEV"] = "列表的标准差";
Blockly.Msg["MATH_ONLIST_OPERATOR_SUM"] = "列表中数值的和";
Blockly.Msg["MATH_ONLIST_TOOLTIP_AVERAGE"] = "返回列表中的数值的平均值。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MAX"] = "返回列表中最大值。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MEDIAN"] = "返回列表中数值的中位数。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MIN"] = "返回列表中最小值。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MODE"] = "返回列表中的出现次数最多的项的列表。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_RANDOM"] = "从列表中返回一个随机的元素。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_STD_DEV"] = "返回列表的标准差。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_SUM"] = "返回列表中的所有数值的和。";
Blockly.Msg["MATH_POWER_SYMBOL"] = "^";  // untranslated
Blockly.Msg["MATH_RANDOM_FLOAT_HELPURL"] = "https://zh.wikipedia.org/wiki/随机数生成器";
Blockly.Msg["MATH_RANDOM_FLOAT_TITLE_RANDOM"] = "随机小数";
Blockly.Msg["MATH_RANDOM_FLOAT_TOOLTIP"] = "返回一个从0.0（含）到1.0（不含）之间的随机数。";
Blockly.Msg["MATH_RANDOM_INT_HELPURL"] = "https://zh.wikipedia.org/wiki/随机数生成器";
Blockly.Msg["MATH_RANDOM_INT_TITLE"] = "从 %1 到 %2 范围内的随机整数";
Blockly.Msg["MATH_RANDOM_INT_TOOLTIP"] = "返回一个限制在两个指定数值的范围（含边界）之间的随机整数。";
Blockly.Msg["MATH_ROUND_HELPURL"] = "https://zh.wikipedia.org/wiki/数值修约";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUND"] = "四舍五入";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDDOWN"] = "向下舍入";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDUP"] = "向上舍入";
Blockly.Msg["MATH_ROUND_TOOLTIP"] = "数字向上或向下舍入。";
Blockly.Msg["MATH_SINGLE_HELPURL"] = "https://zh.wikipedia.org/wiki/平方根";
Blockly.Msg["MATH_SINGLE_OP_ABSOLUTE"] = "绝对值";
Blockly.Msg["MATH_SINGLE_OP_ROOT"] = "平方根";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ABS"] = "返回一个数值的绝对值。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_EXP"] = "返回e的n次幂。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LN"] = "返回一个数值的自然对数。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LOG10"] = "返回一个数值的以10为底的对数。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_NEG"] = "返回一个数值的相反数。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_POW10"] = "返回10的n次幂。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ROOT"] = "返回一个数的平方根。";
Blockly.Msg["MATH_SUBTRACTION_SYMBOL"] = "-";  // untranslated
Blockly.Msg["MATH_TRIG_ACOS"] = "反余玄";
Blockly.Msg["MATH_TRIG_ASIN"] = "反正弦";
Blockly.Msg["MATH_TRIG_ATAN"] = "反正切";
Blockly.Msg["MATH_TRIG_COS"] = "余弦";
Blockly.Msg["MATH_TRIG_HELPURL"] = "https://zh.wikipedia.org/wiki/三角函数";
Blockly.Msg["MATH_TRIG_SIN"] = "正弦";
Blockly.Msg["MATH_TRIG_TAN"] = "正切";
Blockly.Msg["MATH_TRIG_TOOLTIP_ACOS"] = "返回一个数值的反余弦值。";
Blockly.Msg["MATH_TRIG_TOOLTIP_ASIN"] = "返回一个数值的反正弦值。";
Blockly.Msg["MATH_TRIG_TOOLTIP_ATAN"] = "返回一个数值的反正切值。";
Blockly.Msg["MATH_TRIG_TOOLTIP_COS"] = "返回指定角度的余弦值（非弧度）。";
Blockly.Msg["MATH_TRIG_TOOLTIP_SIN"] = "返回指定角度的正弦值（非弧度）。";
Blockly.Msg["MATH_TRIG_TOOLTIP_TAN"] = "返回指定角度的正切值（非弧度）。";
Blockly.Msg["NEW_COLOUR_VARIABLE"] = "创建颜色变量...";
Blockly.Msg["NEW_NUMBER_VARIABLE"] = "创建数字变量...";
Blockly.Msg["NEW_STRING_VARIABLE"] = "创建字符串变量...";
Blockly.Msg["NEW_VARIABLE"] = "创建变量...";
Blockly.Msg["NEW_VARIABLE_TITLE"] = "新变量的名称：";
Blockly.Msg["NEW_VARIABLE_TYPE_TITLE"] = "新变量的类型：";
Blockly.Msg["ORDINAL_NUMBER_SUFFIX"] = "";  // untranslated
Blockly.Msg["PROCEDURES_ALLOW_STATEMENTS"] = "允许声明";
Blockly.Msg["PROCEDURES_BEFORE_PARAMS"] = "与：";
Blockly.Msg["PROCEDURES_CALLNORETURN_HELPURL"] = "https://zh.wikipedia.org/wiki/子程序";
Blockly.Msg["PROCEDURES_CALLNORETURN_TOOLTIP"] = "运行用户定义的函数“%1”。";
Blockly.Msg["PROCEDURES_CALLRETURN_HELPURL"] = "https://zh.wikipedia.org/wiki/子程序";
Blockly.Msg["PROCEDURES_CALLRETURN_TOOLTIP"] = "运行用户定义的函数“%1”，并使用它的输出值。";
Blockly.Msg["PROCEDURES_CALL_BEFORE_PARAMS"] = "与：";
Blockly.Msg["PROCEDURES_CREATE_DO"] = "创建“%1”";
Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"] = "描述该功能...";
Blockly.Msg["PROCEDURES_DEFNORETURN_DO"] = "";  // untranslated
Blockly.Msg["PROCEDURES_DEFNORETURN_HELPURL"] = "https://zh.wikipedia.org/wiki/子程序";
Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"] = "做点什么";
Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"] = "至";
Blockly.Msg["PROCEDURES_DEFNORETURN_TOOLTIP"] = "创建一个不带输出值的函数。";
Blockly.Msg["PROCEDURES_DEFRETURN_HELPURL"] = "https://zh.wikipedia.org/wiki/子程序";
Blockly.Msg["PROCEDURES_DEFRETURN_RETURN"] = "返回";
Blockly.Msg["PROCEDURES_DEFRETURN_TOOLTIP"] = "创建一个有输出值的函数。";
Blockly.Msg["PROCEDURES_DEF_DUPLICATE_WARNING"] = "警告：此函数具有重复参数。";
Blockly.Msg["PROCEDURES_HIGHLIGHT_DEF"] = "突出显示函数定义";
Blockly.Msg["PROCEDURES_IFRETURN_HELPURL"] = "http://c2.com/cgi/wiki?GuardClause";  // untranslated
Blockly.Msg["PROCEDURES_IFRETURN_TOOLTIP"] = "如果值为真，则返回第二个值。";
Blockly.Msg["PROCEDURES_IFRETURN_WARNING"] = "警告：这个块只能在函数内部使用。";
Blockly.Msg["PROCEDURES_MUTATORARG_TITLE"] = "输入名称：";
Blockly.Msg["PROCEDURES_MUTATORARG_TOOLTIP"] = "添加函数输入。";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TITLE"] = "输入";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TOOLTIP"] = "添加、移除或重新排此函数的输入。";
Blockly.Msg["REDO"] = "重做";
Blockly.Msg["REMOVE_COMMENT"] = "删除注释";
Blockly.Msg["RENAME_VARIABLE"] = "重命名变量...";
Blockly.Msg["RENAME_VARIABLE_TITLE"] = "将所有“%1”变量重命名为:";
Blockly.Msg["TEXT_APPEND_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg["TEXT_APPEND_TITLE"] = "在%1之后加上文本%2";
Blockly.Msg["TEXT_APPEND_TOOLTIP"] = "将一些文本追加到变量“%1”里。";
Blockly.Msg["TEXT_CHANGECASE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_LOWERCASE"] = "转为小写";
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_TITLECASE"] = "转为首字母大写";
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_UPPERCASE"] = "转为大写";
Blockly.Msg["TEXT_CHANGECASE_TOOLTIP"] = "用不同的大小写模式复制并返回这段文字。";
Blockly.Msg["TEXT_CHARAT_FIRST"] = "获取第一个字符";
Blockly.Msg["TEXT_CHARAT_FROM_END"] = "获取倒数第#个字符";
Blockly.Msg["TEXT_CHARAT_FROM_START"] = "获取第#个字符";
Blockly.Msg["TEXT_CHARAT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg["TEXT_CHARAT_LAST"] = "获取最后一个字符";
Blockly.Msg["TEXT_CHARAT_RANDOM"] = "获取随机一个字符";
Blockly.Msg["TEXT_CHARAT_TAIL"] = "";  // untranslated
Blockly.Msg["TEXT_CHARAT_TITLE"] = "在文本%1 里 %2";
Blockly.Msg["TEXT_CHARAT_TOOLTIP"] = "返回位于指定位置的字符。";
Blockly.Msg["TEXT_COUNT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#counting-substrings";  // untranslated
Blockly.Msg["TEXT_COUNT_MESSAGE0"] = "计算%1在%2里出现的次数";
Blockly.Msg["TEXT_COUNT_TOOLTIP"] = "计算在一段文本中，某个部分文本重复出现了多少次。";
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TOOLTIP"] = "将一个项添加到文本中。";
Blockly.Msg["TEXT_CREATE_JOIN_TITLE_JOIN"] = "拼接";
Blockly.Msg["TEXT_CREATE_JOIN_TOOLTIP"] = "添加、移除或重新排列各节来重新配置这个文本块。";
Blockly.Msg["TEXT_GET_SUBSTRING_END_FROM_END"] = "到倒数第#个字符";
Blockly.Msg["TEXT_GET_SUBSTRING_END_FROM_START"] = "到第#个字符";
Blockly.Msg["TEXT_GET_SUBSTRING_END_LAST"] = "到最后一个字符";
Blockly.Msg["TEXT_GET_SUBSTRING_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg["TEXT_GET_SUBSTRING_INPUT_IN_TEXT"] = "从文本";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FIRST"] = "获取子串，从第一个字符";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FROM_END"] = "获取子串，从倒数第#个字符";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FROM_START"] = "获取子串，从第#个字符";
Blockly.Msg["TEXT_GET_SUBSTRING_TAIL"] = "";  // untranslated
Blockly.Msg["TEXT_GET_SUBSTRING_TOOLTIP"] = "返回文本中指定的一部分。";
Blockly.Msg["TEXT_INDEXOF_HELPURL"] = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg["TEXT_INDEXOF_OPERATOR_FIRST"] = "寻找第一次出现的文本";
Blockly.Msg["TEXT_INDEXOF_OPERATOR_LAST"] = "寻找最后一次出现的文本";
Blockly.Msg["TEXT_INDEXOF_TITLE"] = "在文本 %1 里 %2  %3";
Blockly.Msg["TEXT_INDEXOF_TOOLTIP"] = "返回第一个文本段在第二个文本段中的第一/最后一个匹配项的起始位置。如果未找到，则返回%1。";
Blockly.Msg["TEXT_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg["TEXT_ISEMPTY_TITLE"] = "%1是空的";
Blockly.Msg["TEXT_ISEMPTY_TOOLTIP"] = "如果给定的文本为空，则返回真。";
Blockly.Msg["TEXT_JOIN_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg["TEXT_JOIN_TITLE_CREATEWITH"] = "创建文本，内容：";
Blockly.Msg["TEXT_JOIN_TOOLTIP"] = "通过串起任意数量的项以建立一段文本。";
Blockly.Msg["TEXT_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg["TEXT_LENGTH_TITLE"] = "%1的长度";
Blockly.Msg["TEXT_LENGTH_TOOLTIP"] = "返回给定文本的字母数（包括空格）。";
Blockly.Msg["TEXT_PRINT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg["TEXT_PRINT_TITLE"] = "输出%1";
Blockly.Msg["TEXT_PRINT_TOOLTIP"] = "输出指定的文字、数字或其他值。";
Blockly.Msg["TEXT_PROMPT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg["TEXT_PROMPT_TOOLTIP_NUMBER"] = "要求用户输入数字。";
Blockly.Msg["TEXT_PROMPT_TOOLTIP_TEXT"] = "要求用户输入一些文本。";
Blockly.Msg["TEXT_PROMPT_TYPE_NUMBER"] = "要求输入数字，并显示提示消息";
Blockly.Msg["TEXT_PROMPT_TYPE_TEXT"] = "要求输入文本，并显示提示消息";
Blockly.Msg["TEXT_REPLACE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#replacing-substrings";  // untranslated
Blockly.Msg["TEXT_REPLACE_MESSAGE0"] = "把%3中的%1替换为%2";
Blockly.Msg["TEXT_REPLACE_TOOLTIP"] = "在一段文本中，将出现过的某部分文本都替换掉。";
Blockly.Msg["TEXT_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#reversing-text";  // untranslated
Blockly.Msg["TEXT_REVERSE_MESSAGE0"] = "倒转文本%1";
Blockly.Msg["TEXT_REVERSE_TOOLTIP"] = "将文本中各个字符的顺序倒转。";
Blockly.Msg["TEXT_TEXT_HELPURL"] = "https://zh.wikipedia.org/wiki/字符串";
Blockly.Msg["TEXT_TEXT_TOOLTIP"] = "一个字、词语或一行文本。";
Blockly.Msg["TEXT_TRIM_HELPURL"] = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg["TEXT_TRIM_OPERATOR_BOTH"] = "消除其两侧的空白";
Blockly.Msg["TEXT_TRIM_OPERATOR_LEFT"] = "消除其左侧的空白";
Blockly.Msg["TEXT_TRIM_OPERATOR_RIGHT"] = "消除其右侧的空白";
Blockly.Msg["TEXT_TRIM_TOOLTIP"] = "从某一端或同时从两端删除多余的空白，并返回这段文字的一个副本。";
Blockly.Msg["TODAY"] = "今天";
Blockly.Msg["UNDO"] = "撤销";
Blockly.Msg["UNNAMED_KEY"] = "未命名";
Blockly.Msg["VARIABLES_DEFAULT_NAME"] = "i";
Blockly.Msg["VARIABLES_GET_CREATE_SET"] = "创建“设定%1”";
Blockly.Msg["VARIABLES_GET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg["VARIABLES_GET_TOOLTIP"] = "返回此变量的值。";
Blockly.Msg["VARIABLES_SET"] = "赋值 %1 为 %2";
Blockly.Msg["VARIABLES_SET_CREATE_GET"] = "创建“获得%1”";
Blockly.Msg["VARIABLES_SET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg["VARIABLES_SET_TOOLTIP"] = "设置此变量，以使它和输入值相等。";
Blockly.Msg["VARIABLE_ALREADY_EXISTS"] = "名字叫“%1”的变量已经存在了。";
Blockly.Msg["VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE"] = "名字叫“%1”的变量已经有了另一个类型：“%2”。";
Blockly.Msg["VARIABLE_ALREADY_EXISTS_FOR_A_PARAMETER"] = "A variable named '%1' already exists as a parameter in the procedure '%2'.";  // untranslated
Blockly.Msg["WORKSPACE_ARIA_LABEL"] = "Blockly工作区";
Blockly.Msg["WORKSPACE_COMMENT_DEFAULT_TEXT"] = "说点什么...";
Blockly.Msg["CONTROLS_FOREACH_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_FOR_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_IF_ELSEIF_TITLE_ELSEIF"] = Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"];
Blockly.Msg["CONTROLS_IF_ELSE_TITLE_ELSE"] = Blockly.Msg["CONTROLS_IF_MSG_ELSE"];
Blockly.Msg["CONTROLS_IF_IF_TITLE_IF"] = Blockly.Msg["CONTROLS_IF_MSG_IF"];
Blockly.Msg["CONTROLS_IF_MSG_THEN"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_WHILEUNTIL_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TITLE"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["LISTS_GET_INDEX_HELPURL"] = Blockly.Msg["LISTS_INDEX_OF_HELPURL"];
Blockly.Msg["LISTS_GET_INDEX_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["LISTS_GET_SUBLIST_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["LISTS_INDEX_OF_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["LISTS_SET_INDEX_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["MATH_CHANGE_TITLE_ITEM"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["PROCEDURES_DEFRETURN_COMMENT"] = Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"];
Blockly.Msg["PROCEDURES_DEFRETURN_DO"] = Blockly.Msg["PROCEDURES_DEFNORETURN_DO"];
Blockly.Msg["PROCEDURES_DEFRETURN_PROCEDURE"] = Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"];
Blockly.Msg["PROCEDURES_DEFRETURN_TITLE"] = Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"];
Blockly.Msg["TEXT_APPEND_VARIABLE"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TITLE_ITEM"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];

Blockly.Msg["LOGIC_HUE"] = "210";
Blockly.Msg["LOOPS_HUE"] = "120";
Blockly.Msg["MATH_HUE"] = "230";
Blockly.Msg["TEXTS_HUE"] = "160";
Blockly.Msg["LISTS_HUE"] = "260";
Blockly.Msg["COLOUR_HUE"] = "20";
Blockly.Msg["VARIABLES_HUE"] = "330";
Blockly.Msg["VARIABLES_DYNAMIC_HUE"] = "310";
Blockly.Msg["PROCEDURES_HUE"] = "290";



// Custom
Blockly.Msg["VARIABLES_SET"] = "宣告 %1 %2 成 %3";
Blockly.Msg["VARIABLES_SET_LOCAL"] = "设定 %1 成 %2";
Blockly.Msg["ADD_VARIABLE"] = "建立变数…";

Blockly.Msg["MYSEARCH"] = "搜寻";
Blockly.Msg["MYSEARCH_QUERY"] = "搜寻积木";
Blockly.Msg["MYSEARCH_PROMPT"] = "请输入积木文字关键字";
Blockly.Msg["MYSEARCH_HUE"] = "210";
Blockly.Msg["MYSEARCH_OPENBLOCKTOOLBOX"] = "开启积木目录";

Blockly.Msg["MYSWITCH_TITLE"] = "开关";
Blockly.Msg["MYSWITCH_VALUE"] = "值";
Blockly.Msg["MYSWITCH_CONDITION"] = "比对";
Blockly.Msg["MYSWITCH_CASE"] = "如果等于";
Blockly.Msg["MYSWITCH_STATEMENT"] = "执行";
Blockly.Msg["MYSWITCH_DEFAULT"] = "预设执行";
Blockly.Msg["MYSWITCH_ELSE"] = "预设";

return Blockly.Msg;
}));
